feature_flag_definition {
  id: LEARNER_STUDY_ANALYTICS
  default_is_enabled: true
}
feature_flag_definition {
  id: SPOTLIGHT_UI
  default_is_enabled: true
}
feature_flag_definition {
  id: MULTIPLE_CLASSROOMS
  default_is_enabled: true
}
feature_flag_definition {
  id: ONBOARDING_FLOW_V2
  default_is_enabled: true
}
feature_flag_definition {
  id: LOAD_LESSON_PROTOS_FROM_ASSETS
  default_is_enabled: true
}
feature_flag_definition {
  id: LOAD_IMAGES_FROM_ASSETS
  default_is_enabled: true
}
feature_flag_definition {
  id: LESSON_PROGRESS_VISUALIZATION
  default_is_enabled: true
}
feature_flag_definition {
  id: STUDY_GUIDES
  default_is_enabled: true
}
feature_flag_definition {
  id: WORKED_EXAMPLES
  default_is_enabled: true
}
feature_flag_definition {
  id: APP_AND_OS_DEPRECATION
  default_is_enabled: true
}
