"""
Package for providing support for downloading platform parameter states from Oppia web.
"""

load("@io_bazel_rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "syncup",
    srcs = [
        "PlatformParameterSyncUpWorker.kt",
        "PlatformParameterSyncUpWorkerModule.kt",
        "PlatformParameterSyncUpWorkerScheduler.kt",
    ],
    visibility = ["//:oppia_api_visibility"],
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:oppia_logger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions:controller",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:controller",
        "//domain/src/main/java/org/oppia/android/domain/util:extensions",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:startup_worker_schedule_readiness_listener",
        "//utility",
    ],
)
