"""
Defines the latest version of the Oppia Android app.
"""

MAJOR_VERSION = 0
MINOR_VERSION = 6

OPPIA_DEV_KITKAT_VERSION_CODE = 10
OPPIA_DEV_VERSION_CODE = 11
OPPIA_ALPHA_KITKAT_VERSION_CODE = 12
OPPIA_ALPHA_VERSION_CODE = 13
