"""
Libraries for automating release operations, including uploading binaries to the Play Console
and distributing builds via Firebase App Distribution.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "play_console_client",
    srcs = ["PlayConsoleClient.kt"],
    visibility = ["//scripts:oppia_script_library_visibility"],
)

kt_jvm_library(
    name = "google_play_console_client",
    srcs = ["GooglePlayConsoleClient.kt"],
    visibility = ["//scripts:oppia_script_library_visibility"],
    deps = [
        ":play_console_client",
        "//scripts/src/java/org/oppia/android/scripts/release/model:track_response",
        "//scripts/src/java/org/oppia/android/scripts/release/remote:play_console_service",
        "//third_party:com_squareup_okhttp3_okhttp",
        "//third_party:com_squareup_retrofit2_converter-moshi",
        "//third_party:com_squareup_retrofit2_retrofit",
    ],
)

kt_jvm_library(
    name = "fake_play_console_client",
    testonly = True,
    srcs = ["FakePlayConsoleClient.kt"],
    visibility = ["//scripts:oppia_script_test_visibility"],
    deps = [":play_console_client"],
)

kt_jvm_library(
    name = "version_inversion_check",
    srcs = ["VersionInversionCheck.kt"],
    visibility = ["//scripts:oppia_script_library_visibility"],
    deps = [":play_console_client"],
)

kt_jvm_library(
    name = "pending_release_check",
    srcs = ["PendingReleaseCheck.kt"],
    visibility = ["//scripts:oppia_script_library_visibility"],
    deps = [":play_console_client"],
)
