# TODO(#1532): Rename file to 'BUILD' post-Gradle.
"""
Package for test-specific platform parameter utilities and helpers.
"""

load("@io_bazel_rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "test_module",
    testonly = True,
    srcs = [
        "TestPlatformParameterModule.kt",
    ],
    visibility = [
        "//:oppia_testing_visibility",
    ],
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:debug_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_impl",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter/testing:test_platform_parameter_config_retriever",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//utility",
        "//utility/src/main/java/org/oppia/android/util/extensions:context_extensions",
    ],
)

kt_android_library(
    name = "fake_debug_controller",
    testonly = True,
    srcs = [
        "FakePlatformParameterDebugController.kt",
    ],
    visibility = [
        "//:oppia_testing_visibility",
    ],
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:debug_module",
    ],
)
