"""
Tests for Oppia Android release automation scripts.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "DeriveVersionNameForCommitTest",
    srcs = ["DeriveVersionNameForCommitTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/common:command_executor",
        "//scripts/src/java/org/oppia/android/scripts/common:script_background_coroutine_dispatcher",
        "//scripts/src/java/org/oppia/android/scripts/release:derive_version_name_for_commit_lib",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)
