blank_issues_enabled: false
contact_links:
  - name: First-time contributor?
    url: https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android
    about: Follow these instructions to get started.
  - name: Oppia Community Support
    url: https://github.com/oppia/oppia-android/discussions
    about: Please ask and answer questions here.
