id: "13"
states {
  key: "End"
  value {
    name: "End"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    content {
      html: "<p>This is the end&nbsp;</p>"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
      }
    }
    interaction {
      id: "EndExploration"
      customization_args {
        key: "recommendedExplorationIds"
        value {
          schema_object_list {
          }
        }
      }
    }
  }
}
states {
  key: "ImageClickInput"
  value {
    name: "ImageClickInput"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_3"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_6"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_7"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_4"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_5"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_8"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_9"
      value {
      }
    }
    content {
      html: "<p>Our Solar System consists of nine planets orbiting around our sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune and Pluto. They range from huge gas giants to small icy dwarf planets.</p><p>\302\240</p><p>Click on the planets below to find out more about each one!</p>"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
      }
    }
    written_translations {
      key: "feedback_2"
      value {
      }
    }
    written_translations {
      key: "feedback_3"
      value {
      }
    }
    written_translations {
      key: "feedback_1"
      value {
      }
    }
    written_translations {
      key: "feedback_6"
      value {
      }
    }
    written_translations {
      key: "feedback_7"
      value {
      }
    }
    written_translations {
      key: "feedback_4"
      value {
      }
    }
    written_translations {
      key: "feedback_5"
      value {
      }
    }
    written_translations {
      key: "default_outcome"
      value {
      }
    }
    written_translations {
      key: "feedback_8"
      value {
      }
    }
    written_translations {
      key: "feedback_9"
      value {
      }
    }
    interaction {
      id: "ImageClickInput"
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>This is Mercury, a small metallic planet closest to the sun. Since it is so near to the sun, it only takes 88 days for it to travel one entire orbit, so a year on Mercury would only be 88 days long.</p>"
            content_id: "feedback_1"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Mercury"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>This is Venus, the second planet from the sun. It is the brightest planet in the Solar System, and can sometimes even be seen during the day. Though Mercury is nearer to the sun than Venus, Venus is the hottest planet in the Solar System, because its thick atmosphere of carbon dioxide traps heat on its surface.</p>"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Venus"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Earth! Our home planet is the third planet from the sun. Despite the vastness of the Solar System and the rest of space, it is the only place that we know life exists on. It is at just the right distance from the sun to ensure a comfortable temperature for us to exist in.</p>"
            content_id: "feedback_3"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Earth"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Mars is the fourth planet from the sun. It is often dubbed the \"red planet\" due to its color, which is a result of large quantities of iron oxide on its surface. It has a thin atmosphere of carbon dioxide and ice caps on either end, and has two small irregularly-shaped moons called Phobos and Deimos.</p>"
            content_id: "feedback_4"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Mars>"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Jupiter, the fifth planet from the sun, is a huge planet that is 2.5 times heavier than all of the other planets in our Solar System combined. It is mostly formed out of thick gases around a solid core. One famous feature on it is the \"Great Red Spot\", which is a huge storm on its surface that has raged for at least 350 years, and is large enough to swallow three entire Earths.</p>"
            content_id: "feedback_5"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Jupiter"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "End"
          feedback {
            html: "<p>Saturn, the sixth planet from the sun, is most well known for its beautiful rings of ice and dust orbiting around it. Like Jupiter, it is a gas giant, mostly made of layers of hydrogen which get progressively denser towards its solid core.\302\240</p>"
            content_id: "feedback_6"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Saturn"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Uranus is the seventh planet from the sun. It was the first planet that was discovered using a telescope, since it is normally too dim to be seen with the naked eye. It is the coldest planet, and is formed from layers of hydrogen gas enveloping a frigid core of rock and ice.</p>"
            content_id: "feedback_7"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Uranus"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Neptune is the eighth planet from the sun. It is an \"ice giant\", like Uranus, with an outer layer of hydrogen, helium, and methane enveloping an icy core. The methane in its atmosphere absorbs red light, giving it a beautiful blue color. It was first predicted to exist from gravitational calculations, and was only discovered by telescope later.</p>"
            content_id: "feedback_8"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Neptune"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ImageClickInput"
          feedback {
            html: "<p>Pluto was once considered the ninth planet from the sun, but has now been reclassified as a \"dwarf planet\". It is formed from ice and rock, and is even smaller than our moon. The first spacecraft to visit Pluto is due to reach in July 2015.</p>"
            content_id: "feedback_9"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              normalized_string: "Pluto"
            }
          }
          rule_type: "IsInRegion"
        }
      }
      default_outcome {
        dest_state_name: "ImageClickInput"
        feedback {
          html: "<p>This doesn\'t seem like the correct choice.Try Again</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "highlightRegionsOnHover"
        value {
          bool_value: false
        }
      }
      customization_args {
        key: "imageAndRegions"
        value {
          custom_schema_value {
            image_with_regions {
              image_path: "Screen Shot 2015-02-18 at 3.51.49 AM_height_400_width_816.png"
              label_regions {
                label: "Mercury"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.010981758
                      y: 0.09856376
                    }
                    lower_right {
                      x: 0.048717607
                      y: 0.17073357
                    }
                  }
                }
              }
              label_regions {
                label: "Venus"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.036925156
                      y: 0.17554489
                    }
                    lower_right {
                      x: 0.1006044
                      y: 0.2958279
                    }
                  }
                }
              }
              label_regions {
                label: "Earth"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.08645345
                      y: 0.1081864
                    }
                    lower_right {
                      x: 0.15484968
                      y: 0.22846942
                    }
                  }
                }
              }
              label_regions {
                label: "Mars"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.1477742
                      y: 0.17554489
                    }
                    lower_right {
                      x: 0.19258553
                      y: 0.2717713
                    }
                  }
                }
              }
              label_regions {
                label: "Jupiter"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.19022705
                      y: 0.06007319
                    }
                    lower_right {
                      x: 0.5723025
                      y: 0.81545055
                    }
                  }
                }
              }
              label_regions {
                label: "Saturn"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.2491893
                      y: 0.3679977
                    }
                    lower_right {
                      x: 0.9968308
                      y: 0.9934694
                    }
                  }
                }
              }
              label_regions {
                label: "Uranus"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.66428363
                      y: 0.05045055
                    }
                    lower_right {
                      x: 0.81522703
                      y: 0.35356376
                    }
                  }
                }
              }
              label_regions {
                label: "Neptune"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.824661
                      y: 0.021582626
                    }
                    lower_right {
                      x: 0.94022703
                      y: 0.25252602
                    }
                  }
                }
              }
              label_regions {
                label: "Pluto"
                region {
                  region_type: RECTANGLE
                  area {
                    upper_left {
                      x: 0.94022703
                      y: 0.2236581
                    }
                    lower_right {
                      x: 0.9779629
                      y: 0.2958279
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
init_state_name: "ImageClickInput"
objective: "learn how to arrange the sentence"
title: "Image Click Input Test Exploration"
language_code: "en"
