page_contents {
  html: "<p>Description of subtopic is here.</p>"
  content_id: "content"
}
recorded_voiceover {
  key: "content"
  value {
  }
}
written_translation {
  key: "content"
  value {
  }
}
written_translation {
  key: "title"
  value {
  }
}
skill_ids: "5RM9KPfQxobH"
skill_ids: "UxTGIJqaHMLa"
subtopic_thumbnail {
  background_color_rgb: 16741119
}
title {
  html: "Mixed Numbers"
  content_id: "title"
}
