id: "test_checkpointing_exploration_new_version"
states {
  key: "first_state"
  value {
    name: "first_state"
    content {
      html: "What is the value of PI to 3 significant digits?"
      content_id: "content"
    }
    interaction {
      id: "NumericInput"
      answer_groups {
        outcome {
          dest_state_name: "second_state"
          feedback {
            html: "Correct answer"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              real: 3.14
            }
          }
          rule_type: "Equals"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "first_state"
          feedback {
            html: "Answer is too precise"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              real: 3.14159
            }
          }
          rule_type: "Equals"
        }
      }
      solution {
        interaction_id: "NumericInput"
        explanation {
        }
      }
      hint {
        hint_content {
          html: "PI can be approximated to 3 correct digits by computing 22/7."
          content_id: "hint_0"
        }
      }
      default_outcome {
        dest_state_name: "first_state"
        feedback {
          html: "Wrong answer"
          content_id: "feedback_0"
        }
      }
    }
  }
}
states {
  key: "second_state"
  value {
    name: "second_state"
    content {
      html: "Click on the continue button"
      content_id: "content"
    }
    interaction {
      id: "Continue"
      default_outcome {
        dest_state_name: "end"
        feedback {
          html: "Feedback for continue button"
          content_id: "feedback_0"
        }
      }
    }
  }
}
states {
  key: "end"
  value {
    name: "end"
    content {
    }
    interaction {
      id: "EndExploration"
    }
  }
}
init_state_name: "first_state"
version: 2
translatable_title {
  html: "Exploration for checkpointing tests"
  content_id: "title"
}
description {
  content_id: "description"
}
