id: "test_exp_id_2"
states {
  key: "ItemSelectionMulti"
  value {
    name: "ItemSelectionMulti"
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>What are the primary colors of light?</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> \'amarelo\' \303\251 considerado uma cor prim\303\241ria no espectro de cores RYB, mas isso n\303\243o corresponde \303\240 luz. Tente novamente! </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\331\212\330\271\330\252\330\250\330\261 <p> \330\247\331\204\330\243\330\265\331\201\330\261 \331\204\331\210\331\206\330\247 \330\243\330\263\330\247\330\263\331\212\330\247 \331\201\331\212 \330\267\331\212\331\201 \331\204\331\210\331\206 RYB\330\214 \331\210\331\204\331\203\331\206 \331\207\330\260\330\247 \331\204\330\247 \331\212\330\252\331\210\330\247\331\201\331\202 \331\205\330\271 \330\247\331\204\330\266\331\210\330\241. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211! </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> \'Njano\' inachukuliwa kuwa rangi ya msingi katika wigo wa rangi ya RYB, lakini hiyo haihusiani na mwanga. Jaribu tena! </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<b> correto! </b>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<b> \330\265\330\255\331\212\330\255! </b>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<b> Sahihi! </b>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Quais s\303\243o as cores prim\303\241rias da luz? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\205\330\247 \331\207\331\212 \330\247\331\204\330\243\331\204\331\210\330\247\331\206 \330\247\331\204\330\243\330\263\330\247\330\263\331\212\330\251 \331\204\331\204\330\266\331\210\330\241\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Je! Ni rangi gani za msingi za mwanga? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Isso n\303\243o est\303\241 certo. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\207\330\260\330\247 \331\204\331\212\330\263 \330\265\330\255\331\212\330\255\330\247 \330\252\331\205\330\247\331\205\330\247. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Hiyo sio sawa kabisa. Jaribu tena. </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> vermelho </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\243\330\255\331\205\330\261 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> nyekundu </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> amarelo </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\330\243\330\265\331\201\330\261 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Njano </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> verde </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\243\330\256\330\266\330\261 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> kijani </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> azul </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\330\243\330\262\330\261\331\202 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Bluu</p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_4"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> laranja </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\330\250\330\261\330\252\331\202\330\247\331\204 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> machungwa </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_5"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> roxo </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\330\243\330\261\330\254\331\210\330\247\331\206\331\212 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> zambarau </p>"
          }
        }
      }
    }
    interaction {
      id: "ItemSelectionInput"
      answer_groups {
        outcome {
          dest_state_name: "NumberInput"
          feedback {
            html: "<b>Correct!</b>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              set_of_translatable_html_content_ids {
                content_ids {
                  content_id: "ca_choices_0"
                }
                content_ids {
                  content_id: "ca_choices_3"
                }
                content_ids {
                  content_id: "ca_choices_2"
                }
              }
            }
          }
          rule_type: "Equals"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "ItemSelectionMulti"
          feedback {
            html: "<p>\'Yellow\' is considered a primary color in the RYB color spectrum, but that doesn\'t correspond to light. Try again!</p>"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              set_of_translatable_html_content_ids {
                content_ids {
                  content_id: "ca_choices_1"
                }
              }
            }
          }
          rule_type: "ContainsAtLeastOneOf"
        }
      }
      default_outcome {
        dest_state_name: "ItemSelectionMulti"
        feedback {
          html: "<p>That\'s not quite right. Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "choices"
        value {
          schema_object_list {
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Red</p>"
                  content_id: "ca_choices_0"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Yellow</p>"
                  content_id: "ca_choices_1"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Green</p>"
                  content_id: "ca_choices_2"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Blue</p>"
                  content_id: "ca_choices_3"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Orange</p>"
                  content_id: "ca_choices_4"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Purple</p>"
                  content_id: "ca_choices_5"
                }
              }
            }
          }
        }
      }
      customization_args {
        key: "minAllowableSelectionCount"
        value {
          signed_int: 1
        }
      }
      customization_args {
        key: "maxAllowableSelectionCount"
        value {
          signed_int: 3
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "MultipleChoice"
  value {
    name: "MultipleChoice"
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>Which bird can sustain flight for long periods of time?</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Correto! Eagles pode sustentar o v\303\264o. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255! \331\212\331\205\331\203\331\206 \330\243\331\206 \331\212\330\257\330\271\331\205 \330\247\331\204\331\206\330\263\331\210\330\261 \330\247\331\204\330\261\330\255\331\204\330\251. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi! Tai zinaweza kuendeleza ndege. </p>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Qual p\303\241ssaro pode sustentar o v\303\264o por longos per\303\255odos de tempo? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\243\331\212 \330\267\330\247\330\246\330\261 \331\212\331\205\331\203\331\206 \330\243\331\206 \331\212\330\257\330\271\331\205 \330\247\331\204\330\261\330\255\331\204\330\251 \331\204\331\201\330\252\330\261\330\247\330\252 \330\267\331\210\331\212\331\204\330\251 \331\205\331\206 \330\247\331\204\330\262\331\205\331\206\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Ni ndege gani anayeweza kuendeleza ndege kwa muda mrefu? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Jaribu tena. </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Pinguim </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> penguin </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Penguin </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> frango </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\330\257\330\254\330\247\330\254 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Kuku </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> \303\241guia </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\331\204\331\206\330\263\330\261 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Tai</p>"
          }
        }
      }
    }
    interaction {
      id: "MultipleChoiceInput"
      answer_groups {
        outcome {
          dest_state_name: "ItemSelectionMinOne"
          feedback {
            html: "<p>Correct! Eagles can sustain flight.</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              non_negative_int: 2
            }
          }
          rule_type: "Equals"
        }
      }
      default_outcome {
        dest_state_name: "MultipleChoice"
        feedback {
          html: "<p>Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "choices"
        value {
          schema_object_list {
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Penguin</p>"
                  content_id: "ca_choices_0"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Chicken</p>"
                  content_id: "ca_choices_1"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>Eagle</p>"
                  content_id: "ca_choices_2"
                }
              }
            }
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "Fractions"
  value {
    name: "Fractions"
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "hint_6"
      value {
      }
    }
    recorded_voiceovers {
      key: "solution"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>What fraction represents half of something?</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto! </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255! </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi! </p>"
          }
        }
      }
    }
    written_translations {
      key: "hint_6"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Lembre-se de que duas metades, quando adicionadas, fa\303\247a um todo. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\252\330\260\331\203\330\261 \330\243\331\206 \331\206\330\265\331\201\331\212\331\212\331\206\330\214 \330\271\331\206\330\257 \330\245\330\266\330\247\331\201\330\252\331\207 \331\205\330\271\330\247\330\214 \331\202\331\205 \330\250\330\245\330\254\330\261\330\247\330\241 \331\210\330\247\330\255\330\257\330\251 \331\203\330\247\331\205\331\204\330\251. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Kumbuka kuwa nusu mbili, zinapoongezwa pamoja, fanya moja. maandishi-na-thamani = \"& amp; quot; test_skill_id_1 kadi ya dhana & amp; quot;\">"
          }
        }
      }
    }
    written_translations {
      key: "solution"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> metade de algo tem uma parte no numerador para cada duas partes no denominador. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\206\330\265\331\201 \330\264\331\212\330\241 \331\212\330\255\330\252\331\210\331\212 \330\271\331\204\331\211 \330\254\330\262\330\241 \331\210\330\247\330\255\330\257 \331\201\331\212 \330\247\331\204\330\250\330\263\330\267 \331\204\331\203\331\204 \331\202\330\263\331\205\331\212\331\206 \331\201\331\212 \330\247\331\204\331\205\331\202\330\247\331\205. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Nusu ya kitu kina sehemu moja katika nambari kwa kila sehemu mbili kwenye dhehebu. ; \" maandishi-na-thamani = \"& amp; quot; test_skill_id_1 kadi ya dhana & amp; quot;\">"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Que fra\303\247\303\243o representa metade de alguma coisa? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\205\330\247 \330\247\331\204\331\203\330\263\330\261 \331\212\331\205\330\253\331\204 \331\206\330\265\331\201 \330\264\331\212\330\241 \331\205\330\247\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Ni sehemu gani inayowakilisha nusu ya kitu? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Essa resposta n\303\243o est\303\241 correta. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\252\331\204\331\203 \330\247\331\204\330\245\330\254\330\247\330\250\330\251 \330\272\331\212\330\261 \330\265\330\255\331\212\330\255\330\251. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Jibu hilo sio sahihi. Jaribu tena. </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_placeholder_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "Inserir uma fra\303\247\303\243o."
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\330\245\330\257\330\256\330\247\331\204 \330\247\331\204\331\203\330\263\330\261."
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Ingiza sehemu."
          }
        }
      }
    }
    interaction {
      id: "FractionInput"
      answer_groups {
        outcome {
          dest_state_name: "MultipleChoice"
          feedback {
            html: "<p>Correct!</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "f"
            value {
              fraction {
                numerator: 1
                denominator: 2
              }
            }
          }
          rule_type: "IsExactlyEqualTo"
        }
        rule_specs {
         input {
          key: "x"
            value {
             signed_int: 1
              }
             }
           rule_type: "HasIntegerPartEqualTo"
         }
      }
      solution {
        answer_is_exclusive: true
        explanation {
          html: "<p>Half of something has one part in the numerator for every two parts in the denominator.</p><p>Click on this <oppia-noninteractive-skillreview skill_id-with-value=\"&amp;quot;test_skill_id_1&amp;quot;\" text-with-value=\"&amp;quot;test_skill_id_1 concept card&amp;quot;\"></oppia-noninteractive-skillreview>.</p>"
          content_id: "solution"
        }
        correct_answer {
          fraction {
            numerator: 1
            denominator: 2
          }
        }
      }
      hint {
        hint_content {
          html: "<p>Remember that two halves, when added together, make one whole.</p><p>Click on this <oppia-noninteractive-skillreview skill_id-with-value=\"&amp;quot;test_skill_id_1&amp;quot;\" text-with-value=\"&amp;quot;test_skill_id_1 concept card&amp;quot;\"></oppia-noninteractive-skillreview>.</p>"
          content_id: "hint_6"
        }
      }
      default_outcome {
        dest_state_name: "Fractions"
        feedback {
          html: "<p>That answer isn\'t correct. Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "allowNonzeroIntegerPart"
        value {
          bool_value: true
        }
      }
      customization_args {
        key: "customPlaceholder"
        value {
          custom_schema_value {
            subtitled_unicode {
              unicode_str: "Input a fraction."
              content_id: "ca_placeholder_0"
            }
          }
        }
      }
      customization_args {
        key: "allowImproperFraction"
        value {
          bool_value: true
        }
      }
      customization_args {
        key: "requireSimplestForm"
        value {
          bool_value: false
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "Continue"
  value {
    name: "Continue"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>Test exploration with interactions. <oppia-noninteractive-link text-with-value=\"&quot;Oppia&quot;\" url-with-value=\"&quot;https://oppia.github.io&quot;\"></oppia-noninteractive-link></p>"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Explora\303\247\303\243o de teste com intera\303\247\303\265es. <oppia-noninteractive-link text-with-value = \"& quot; oppia & quot;\" URL - com valor = \"& quot; https: //oppia.github.io&quot;\"> </oppia-noninteractive-link> </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\247\330\256\330\252\330\250\330\247\330\261 \330\247\331\204\330\247\330\263\330\252\331\203\330\264\330\247\331\201 \331\205\330\271 \330\247\331\204\330\252\331\201\330\247\330\271\331\204\330\247\330\252. <oppia-nonirtive-link \330\247\331\204\331\206\330\265 \331\205\330\271 \330\247\331\204\331\202\331\212\331\205\330\251 = \"& quot\330\233 oppia & quot\330\233\" \330\271\331\206\331\210\330\247\331\206 URL \331\205\330\271 \330\247\331\204\331\202\331\212\331\205\330\251 = \"& quot\330\233 https: //oppia.github.io&quot\330\233\"> </oppia-noninteractive-link> </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> uchunguzi wa uchunguzi na mwingiliano. <Opdia-noninteractive-link maandishi-na-thamani = \"& quot; Oppia & quot;\" url-na-thamani = \"& quot; https: //oppia.github.io&quot;\">"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "Continuando em frente."
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\330\247\330\263\330\252\331\205\330\261\330\247\330\261 \331\201\330\265\330\247\330\271\330\257\330\247."
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Kuendelea mbele."
          }
        }
      }
    }
    interaction {
      id: "Continue"
      default_outcome {
        dest_state_name: "Fractions"
        feedback {
          html: "Continuing onward."
          content_id: "default_outcome"
        }
        labelled_as_correct: true
      }
      customization_args {
        key: "buttonText"
        value {
          normalized_string: "Continue"
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "NumberInput"
  value {
    name: "NumberInput"
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_3"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    recorded_voiceovers {
      key: "hint_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "solution"
      value {
      }
    }
    content {
      html: "<p>What is 11 times 11?</p>"
      content_id: "content"
    }
    written_translations {
      key: "hint_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 11 * 11 pode ser reformulado como 11 * 10 e, em seguida, adicione 11 no final. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\331\212\331\205\331\203\331\206 \330\245\330\271\330\247\330\257\330\251 \330\265\331\212\330\247\330\272\330\251 <p> 11 * 11 \330\271\331\204\331\211 \330\243\331\206\331\207\330\247 11 * 10\330\214 \330\253\331\205 \330\243\330\266\331\201 11 \331\201\331\212 \330\247\331\204\331\206\331\207\330\247\331\212\330\251. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 11 * 11 inaweza kutolewa tena kama 11 * 10, kisha ongeza 11 mwishoni. </p>"
          }
        }
      }
    }
    written_translations {
      key: "solution"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 11 vezes 11 \303\251 121. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 11 \331\205\330\261\330\247\330\252 11 \331\207\331\210 121. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> mara 11 11 ni 121. </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o \303\251 bem. \303\211 realmente maior que isso. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\247\331\206\331\207\330\247 \331\201\331\212 \330\247\331\204\331\210\330\247\331\202\330\271 \330\243\331\203\330\250\330\261 \331\205\331\206 \330\260\331\204\331\203. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sio kabisa. Kwa kweli ni kubwa kuliko hiyo. Jaribu tena. </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o exatamente. \303\211 menos do que isso. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\247\331\206\331\207\330\247 \330\243\331\202\331\204 \331\205\331\206 \330\260\331\204\331\203. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sio kabisa. Ni chini ya hiyo. </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto! </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255! </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi! </p>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> O que \303\251 11 vezes 11? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\205\330\247 \331\207\331\210 11 \331\205\330\261\330\251 11\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Ni nini mara 11? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Alguma coisa deu errado. A resposta \303\251 121 - tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\255\330\257\330\253 \330\256\330\267\330\243 \331\205\330\247. \330\247\331\204\330\254\331\210\330\247\330\250 \331\207\331\210 121 - \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Kuna kitu kilienda vibaya. Jibu ni 121-Jaribu tena. </p>"
          }
        }
      }
    }
    interaction {
      id: "NumericInput"
      answer_groups {
        outcome {
          dest_state_name: "RatioInput"
          feedback {
            html: "<p>Correct!</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              real: 121.0
            }
          }
          rule_type: "Equals"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "NumberInput"
          feedback {
            html: "<p>Not quite. It\'s actually larger than that. Try again.</p>"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              real: 121.0
            }
          }
          rule_type: "IsLessThan"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "NumberInput"
          feedback {
            html: "<p>Not quite. It\'s less than that.</p>"
            content_id: "feedback_3"
          }
        }
        rule_specs {
          input {
            key: "x"
            value {
              real: 121.0
            }
          }
          rule_type: "IsGreaterThan"
        }
      }
      solution {
        answer_is_exclusive: true
        explanation {
          html: "<p>11 times 11 is 121.</p>"
          content_id: "solution"
        }
        correct_answer {
          real: 121.0
        }
      }
      hint {
        hint_content {
          html: "<p>11 * 11 can be rephrased as 11 * 10, then add 11 at the end.</p>"
          content_id: "hint_1"
        }
      }
      default_outcome {
        dest_state_name: "NumberInput"
        feedback {
          html: "<p>Something went wrong. The answer is 121--try again.</p>"
          content_id: "default_outcome"
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "RatioInput"
  value {
    name: "RatioInput"
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_3"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is:</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o, isso n\303\243o parece correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\330\247 \331\212\330\250\330\257\331\210 \331\207\330\260\330\247 \330\272\331\212\330\261 \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Hapana hii haionekani kuwa sawa </p>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Dois n\303\272meros s\303\243o respectivamente 20% e 50% mais que um terceiro n\303\272mero. A propor\303\247\303\243o dos dois n\303\272meros \303\251: </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\261\331\202\331\205\331\212\331\206 \330\271\331\204\331\211 \330\247\331\204\330\252\331\210\330\247\331\204\331\212 20\331\252 \331\210 50\331\252 \330\243\331\203\330\253\330\261 \331\205\331\206 \330\261\331\202\331\205 \330\253\330\247\331\204\330\253. \331\206\330\263\330\250\330\251 \330\247\331\204\330\243\330\261\331\202\330\247\331\205\331\212\331\206 \331\207\331\212: </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Nambari mbili ni 20% na 50% zaidi ya idadi ya tatu. Uwiano wa nambari mbili ni: </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o \303\251 correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\272\331\212\330\261 \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> sio sahihi </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_placeholder_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "Digite no formato de x: y"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\330\243\330\257\330\256\331\204 \330\250\330\252\331\206\330\263\331\212\331\202 X: Y"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Ingiza katika umbizo la x:y"
          }
        }
      }
    }
    written_translations {
      key: "hint_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Se voc\303\252 o configurou pela primeira vez como uma s\303\251rie de equa\303\247\303\265es, pode ser mais f\303\241cil resolver: a = 1,2x, b = 1,5x, raz\303\243o = a/b =? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\245\330\260\330\247 \331\202\331\205\330\252 \330\250\330\245\330\271\330\257\330\247\330\257\331\207\330\247 \331\204\330\243\331\210\331\204 \331\205\330\261\330\251 \331\203\330\263\331\204\330\263\331\204\330\251 \331\205\331\206 \330\247\331\204\331\205\330\271\330\247\330\257\331\204\330\247\330\252 \330\214 \331\201\331\202\330\257 \331\212\331\203\331\210\331\206 \331\205\331\206 \330\247\331\204\330\243\330\263\331\207\331\204 \330\255\331\204: a = 1.2x \330\214 b = 1.5x \330\214 ratio = a/b =\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Ikiwa utaiweka kwanza kama safu ya hesabu, inaweza kuwa rahisi kusuluhisha: a = 1.2x, b = 1.5x, uwiano = a/b =? </p>"
          }
        }
      }
    }
    written_translations {
      key: "solution"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> a = 1,2x, b = 1,5x, raz\303\243o = a/b = (1,2x)/(1,5x) = 1.2/1.5 = 12/15 = 4/5 -> 4: 5. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> a = 1.2x \330\214 b = 1.5x \330\214 \331\206\330\263\330\250\330\251 = a/b = (1.2x)/(1.5x) = 1.2/1.5 = 12/15 = 4/5 -> 4: 5. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> a = 1.2x, b = 1.5x, uwiano = a/b = (1.2x)/(1.5x) = 1.2/1.5 = 12/15 = 4/5 -> 4: 5. </p>"
          }
        }
      }
    }
    interaction {
      id: "RatioExpressionInput"
      answer_groups {
        outcome {
          dest_state_name: "RatioInput"
          feedback {
            html: "<p>No this doesn\'t seem correct</p>"
            content_id: "feedback_1"
          }
        }
        rule_specs {
          input {
            key: "y"
            value {
              non_negative_int: 3
            }
          }
          rule_type: "HasNumberOfTermsEqualTo"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "Text"
          feedback {
            html: "<p>Correct</p>"
            content_id: "feedback_2"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              ratio_expression {
                ratio_component: 4
                ratio_component: 5
              }
            }
          }
          rule_type: "Equals"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "Text"
          feedback {
            html: "<p>Correct</p>"
            content_id: "feedback_3"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              ratio_expression {
                ratio_component: 8
                ratio_component: 10
              }
            }
          }
          rule_type: "IsEquivalent"
        }
      }
      solution {
        explanation {
          html: "<p>A = 1.2x, B = 1.5x, ratio = A/B = (1.2x)/(1.5x) = 1.2/1.5 = 12/15 = 4/5 -> 4:5.</p>"
          content_id: "solution"
        }
        correct_answer {
          ratio_expression {
            ratio_component: 4
            ratio_component: 5
          }
        }
      }
      hint {
        hint_content {
          html: "<p>If you first set it up as a series of equations, it may be easier to solve: A = 1.2x, B = 1.5x, ratio = A/B = ?</p>"
          content_id: "hint_1"
        }
      }
      default_outcome {
        dest_state_name: "RatioInput"
        feedback {
          html: "<p>Not correct</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "numberOfTerms"
        value {
          signed_int: 0
        }
      }
      customization_args {
        key: "placeholder"
        value {
          custom_schema_value {
            subtitled_unicode {
              unicode_str: "Enter in format of x:y"
              content_id: "ca_placeholder_0"
            }
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "Text"
  value {
    name: "Text"
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>In which language does Oppia mean \'to learn\'?</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto! </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255! </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi! </p>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Em que a linguagem significa \"aprender\"? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\201\331\212 \330\243\331\212 \331\204\330\272\330\251 \330\252\330\271\331\206\331\212 Oppia \"\330\247\331\204\330\252\330\271\331\204\331\205\"\330\237 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Je! Onpia inamaanisha \'kujifunza\'? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o exatamente. Tente novamente (ou talvez use um mecanismo de pesquisa). </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211 (\330\243\331\210 \330\261\330\250\331\205\330\247 \330\247\330\263\330\252\330\256\330\257\331\205 \331\205\330\255\330\261\331\203 \330\250\330\255\330\253). </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sio kabisa. Jaribu tena (au labda utumie injini ya utaftaji). </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_placeholder_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "Digite um idioma"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\330\243\330\257\330\256\331\204 \331\204\330\272\330\251"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Ingiza lugha"
          }
        }
      }
    }
    written_translations {
      key: "43df2897-0a03-4d1f-b892-9e1d251af5c9"
      value {
        translation_mapping {
          key: "pt"
          value {
            html_list {
              html: "finlandesa"
            }
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html_list {
              html: "\330\247\331\204\331\201\331\206\331\204\331\206\330\257\331\212\330\251"
            }
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html_list {
              html: "Kifini"
            }
          }
        }
      }
    }
    written_translations {
      key: "hint_1"
      value {
        translation_mapping {
          key: "ar"
          value {
            html: "\330\247\331\204\330\250\331\204\330\257 \330\250\330\247\331\204\331\202\330\261\330\250 \331\205\331\206 \330\247\331\204\331\206\330\261\331\210\331\212\330\254."
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Nchi iko karibu na Norway."
          }
        }
        translation_mapping {
          key: "pt"
          value {
            html: "O pa\303\255s est\303\241 perto da Noruega."
          }
        }
      }
    }
    written_translations {
      key: "solution"
      value {
        translation_mapping {
          key: "ar"
          value {
            html: "\330\247\331\204\330\254\331\210\330\247\330\250 \331\207\331\210 \"\330\247\331\204\331\201\331\206\331\204\331\206\330\257\331\212\"."
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Jibu ni \'Kifini\'."
          }
        }
        translation_mapping {
          key: "pt"
          value {
            html: "A resposta \303\251 \'finlandesa\'."
          }
        }
      }
    }
    interaction {
      id: "TextInput"
      answer_groups {
        outcome {
          dest_state_name: "DragDropNoGroup"
          feedback {
            html: "<p>Correct!</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              translatable_set_of_normalized_string {
                content_id: "43df2897-0a03-4d1f-b892-9e1d251af5c9"
                normalized_strings: "finnish"
              }
            }
          }
          rule_type: "Equals"
        }
      }
      solution {
        answer_is_exclusive: true
        explanation {
          html: "The answer is \'finnish\'."
          content_id: "solution"
        }
        correct_answer {
          normalized_string: "finnish"
        }
      }
      hint {
        hint_content {
          html: "The country is near Norway."
          content_id: "hint_1"
        }
      }
      default_outcome {
        dest_state_name: "Text"
        feedback {
          html: "<p>Not quite. Try again (or maybe use a search engine).</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "rows"
        value {
          signed_int: 1
        }
      }
      customization_args {
        key: "placeholder"
        value {
          custom_schema_value {
            subtitled_unicode {
              unicode_str: "Enter a language"
              content_id: "ca_placeholder_0"
            }
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "ItemSelectionMinOne"
  value {
    name: "ItemSelectionMinOne"
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>What color does the \'G\' in \'RGB\' correspond to?</p>"
      content_id: "content"
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> correto! </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \330\265\330\255\331\212\330\255! </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sahihi! </p>"
          }
        }
      }
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Que cor o \'G\' em \'RGB\' corresponde a? </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\205\330\247 \331\207\331\210 \330\247\331\204\331\204\331\210\331\206 \"G\" \331\201\331\212 \"RGB\" \330\252\330\252\331\210\330\247\331\201\331\202 \331\205\330\271 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Je! \'G\' katika \'RGB\' inahusiana na rangi gani? </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o \303\251 bem. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Sio kabisa. Jaribu tena. </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> <strong> verde </strong> </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> <strong> \330\243\330\256\330\266\330\261 </strong> </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> <strong> kijani </strong> </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> <strong> vermelho </strong> </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> <strong> \330\243\330\255\331\205\330\261 </strong> </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> <strong> nyekundu </strong> </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> <strong> azul </strong> </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> <strong> \330\247\331\204\330\243\330\262\330\261\331\202 </strong> </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> <strong> bluu </strong> </p>"
          }
        }
      }
    }
    interaction {
      id: "ItemSelectionInput"
      answer_groups {
        outcome {
          dest_state_name: "ItemSelectionMulti"
          feedback {
            html: "<p>Correct!</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              set_of_translatable_html_content_ids {
                content_ids {
                  content_id: "ca_choices_0"
                }
              }
            }
          }
          rule_type: "Equals"
        }
      }
      default_outcome {
        dest_state_name: "ItemSelectionMinOne"
        feedback {
          html: "<p>Not quite. Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "choices"
        value {
          schema_object_list {
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p><strong>Green</strong></p>"
                  content_id: "ca_choices_0"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p><strong>Red</strong></p>"
                  content_id: "ca_choices_1"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p><strong>Blue</strong></p>"
                  content_id: "ca_choices_2"
                }
              }
            }
          }
        }
      }
      customization_args {
        key: "minAllowableSelectionCount"
        value {
          signed_int: 1
        }
      }
      customization_args {
        key: "maxAllowableSelectionCount"
        value {
          signed_int: 1
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "DragDropNoGroup"
  value {
    name: "DragDropNoGroup"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_3"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>Sort the following in descending order.</p>"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Classifique o seguinte em ordem decrescente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\201\330\261\330\262 \331\205\330\247 \331\212\331\204\331\212 \331\201\331\212 \330\252\330\261\330\252\331\212\330\250 \330\252\331\206\330\247\330\262\331\204\331\212. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Panga yafuatayo kwa mpangilio wa kushuka. </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Parece que voc\303\252 fez a ordem crescente </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\212\330\250\330\257\331\210 \330\243\331\206\331\203 \331\201\330\271\331\204\330\252 \330\247\331\204\331\206\330\270\330\247\331\205 \330\247\331\204\330\265\330\271\331\210\330\257\331\212 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Inaonekana kama ulifanya agizo la kupaa </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Isso n\303\243o parece certo para mim </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\207\330\260\330\247 \331\204\330\247 \331\212\330\250\330\257\331\210 \330\265\330\255\331\212\330\255\330\247 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Hii haionekani kuwa sawa kwangu </p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Isso \303\251 correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\207\330\260\330\247 \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Hiyo ni sahihi </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o \303\251 bem. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Sio kabisa. Jaribu tena.</p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,35 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.35 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.35 </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 3/5 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 3/5 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>3/5</p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,5 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.5 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.5 </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,46 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.46 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.46 </p>"
          }
        }
      }
    }
    interaction {
      id: "DragAndDropSortInput"
      answer_groups {
        outcome {
          dest_state_name: "DragDropGroup"
          feedback {
            html: "<p>That\'s correct</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              list_of_sets_of_translatable_html_content_ids {
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_1"
                  }
                }
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_2"
                  }
                }
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_3"
                  }
                }
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_0"
                  }
                }
              }
            }
          }
          rule_type: "IsEqualToOrdering"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "DragDropNoGroup"
          feedback {
            html: "<p>Seems like you did the ascending order</p>"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "y"
            value {
              non_negative_int: 1
            }
          }
          input {
            key: "x"
            value {
              translatable_html_content_id {
                content_id: "ca_choices_2"
              }
            }
          }
          rule_type: "HasElementXAtPositionY"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "DragDropNoGroup"
          feedback {
            html: "<p>This does not seem right to me</p>"
            content_id: "feedback_3"
          }
        }
        rule_specs {
          input {
            key: "y"
            value {
              translatable_html_content_id {
                content_id: "ca_choices_0"
              }
            }
          }
          input {
            key: "x"
            value {
              translatable_html_content_id {
                content_id: "ca_choices_3"
              }
            }
          }
          rule_type: "HasElementXBeforeElementY"
        }
      }
      default_outcome {
        dest_state_name: "DragDropNoGroup"
        feedback {
          html: "<p>Not quite. Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "allowMultipleItemsInSamePosition"
        value {
          bool_value: false
        }
      }
      customization_args {
        key: "choices"
        value {
          schema_object_list {
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.35</p>"
                  content_id: "ca_choices_0"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>3/5</p>"
                  content_id: "ca_choices_1"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.5</p>"
                  content_id: "ca_choices_2"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.46</p>"
                  content_id: "ca_choices_3"
                }
              }
            }
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "DragDropGroup"
  value {
    name: "DragDropGroup"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_2"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_3"
      value {
      }
    }
    recorded_voiceovers {
      key: "feedback_1"
      value {
      }
    }
    recorded_voiceovers {
      key: "default_outcome"
      value {
      }
    }
    content {
      html: "<p>Sort the following in descending order, putting equal items in the same position.</p>"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Classifique o seguinte em ordem decrescente, colocando itens iguais na mesma posi\303\247\303\243o. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\201\330\261\330\262 \331\205\330\247 \331\212\331\204\331\212 \331\201\331\212 \330\252\330\261\330\252\331\212\330\250 \330\252\331\206\330\247\330\262\331\204\331\212\330\214 \331\210\330\266\330\271 \330\247\331\204\330\271\331\206\330\247\330\265\330\261 \330\247\331\204\331\205\330\252\330\263\330\247\331\210\331\212\330\251 \331\201\331\212 \331\206\331\201\330\263 \330\247\331\204\331\205\331\210\330\266\330\271. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Panga zifuatazo kwa mpangilio wa kushuka, ukiweka vitu sawa katika nafasi sawa.</p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Parece que voc\303\252 fez em ordem crescente </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\212\330\250\330\257\331\210 \330\243\331\206\331\203 \331\201\330\271\331\204\330\252 \330\252\330\261\330\252\331\212\330\250\331\213\330\247 \330\252\330\265\330\247\330\271\330\257\331\212\331\213\330\247 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Inaonekana kama ulifanya agizo la kupanda</p>"
          }
        }
      }
    }
    written_translations {
      key: "feedback_3"
      value {
      }
    }
    written_translations {
      key: "feedback_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> Isso \303\251 correto </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\207\330\260\330\247 \330\265\330\255\331\212\330\255 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> Hiyo ni sahihi </p>"
          }
        }
      }
    }
    written_translations {
      key: "default_outcome"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> N\303\243o exatamente. Tente novamente. </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> \331\204\331\212\330\263 \330\252\331\205\330\247\331\205\330\247. \330\255\330\247\331\210\331\204 \331\205\330\261\330\251 \330\243\330\256\330\261\331\211. </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p>Sio kabisa. Jaribu tena.</p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_0"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 3/5 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 3/5 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 3/5 </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_1"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,6 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.6 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.6 </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_2"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,35 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.35 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.35 </p>"
          }
        }
      }
    }
    written_translations {
      key: "ca_choices_3"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "<p> 0,46 </p>"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "<p> 0.46 </p>"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "<p> 0.46 </p>"
          }
        }
      }
    }
    interaction {
      id: "DragAndDropSortInput"
      answer_groups {
        outcome {
          dest_state_name: "End"
          feedback {
            html: "<p>That\'s correct</p>"
            content_id: "feedback_1"
          }
          labelled_as_correct: true
        }
        rule_specs {
          input {
            key: "x"
            value {
              list_of_sets_of_translatable_html_content_ids {
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_0"
                  }
                  content_ids {
                    content_id: "ca_choices_1"
                  }
                }
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_3"
                  }
                }
                content_id_lists {
                  content_ids {
                    content_id: "ca_choices_2"
                  }
                }
              }
            }
          }
          rule_type: "IsEqualToOrdering"
        }
      }
      answer_groups {
        outcome {
          dest_state_name: "DragDropGroup"
          feedback {
            html: "<p>Seems like you did the ascending order</p>"
            content_id: "feedback_2"
          }
        }
        rule_specs {
          input {
            key: "y"
            value {
              non_negative_int: 1
            }
          }
          input {
            key: "x"
            value {
              translatable_html_content_id {
                content_id: "ca_choices_1"
              }
            }
          }
          rule_type: "HasElementXAtPositionY"
        }
      }
      default_outcome {
        dest_state_name: "DragDropGroup"
        feedback {
          html: "<p>Not quite. Try again.</p>"
          content_id: "default_outcome"
        }
      }
      customization_args {
        key: "allowMultipleItemsInSamePosition"
        value {
          bool_value: true
        }
      }
      customization_args {
        key: "choices"
        value {
          schema_object_list {
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>3/5</p>"
                  content_id: "ca_choices_0"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.6</p>"
                  content_id: "ca_choices_1"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.35</p>"
                  content_id: "ca_choices_2"
                }
              }
            }
            schema_object {
              custom_schema_value {
                subtitled_html {
                  html: "<p>0.46</p>"
                  content_id: "ca_choices_3"
                }
              }
            }
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
states {
  key: "End"
  value {
    name: "End"
    recorded_voiceovers {
      key: "content"
      value {
      }
    }
    content {
      html: "Congratulations, you have finished!"
      content_id: "content"
    }
    written_translations {
      key: "content"
      value {
        translation_mapping {
          key: "pt"
          value {
            html: "Parab\303\251ns, voc\303\252 terminou!"
          }
        }
        translation_mapping {
          key: "ar"
          value {
            html: "\330\252\331\207\330\247\331\206\331\212\331\206\330\247\330\214 \331\204\331\202\330\257 \330\247\331\206\330\252\331\207\331\212\330\252!"
          }
        }
        translation_mapping {
          key: "sw"
          value {
            html: "Hongera, umemaliza!"
          }
        }
      }
    }
    interaction {
      id: "EndExploration"
      customization_args {
        key: "recommendedExplorationIds"
        value {
          schema_object_list {
          }
        }
      }
    }
    linked_skill_id: "test_skill_id_0"
  }
}
init_state_name: "Continue"
language_code: "en"
written_translations {
  key: "title"
  value {
  }
}
written_translations {
  key: "description"
  value {
  }
}
translatable_title {
  html: "Prototype Exploration"
  content_id: "title"
}
description {
  html: "Demonstrate core interactions used in the Oppia prototype."
  content_id: "description"
}
