id: "test_topic_id_2"
translatable_title {
  html: "Third Test Topic"
  content_id: "title"
}
translatable_description {
  html: "A topic that\'s not yet ready to be played."
  content_id: "description"
}
