story_id: "test_story_id_2"
story_thumbnail {
  background_color_rgb: 11761905
}
chapters {
  exploration_id: "test_exp_id_4"
  chapter_thumbnail {
    background_color_rgb: 14061432
  }
  written_translations {
    key: "title"
    value {
    }
  }
  written_translations {
    key: "description"
    value {
    }
  }
  translatable_title {
    html: "Fifth Exploration"
    content_id: "title"
  }
  translatable_description {
    content_id: "description"
  }
}
written_translations {
  key: "title"
  value {
  }
}
translatable_story_name {
  html: "Other Interesting Story"
  content_id: "title"
}
