id: "test_topic_id_1"
name: "Second Test Topic"
description: "A topic considering the various implications of having especially long topic descriptions. These descriptions almost certainly need to wrap, which should be interesting in the UI (especially on small screens). Consider also that there may even be multiple points pertaining to a topic, some of which may require expanding the description section in order to read the whole topic description."
canonical_story_ids: "test_story_id_2"
is_published: true
topic_thumbnail {
}
