story_id: "wAMdg4oOClga"
story_thumbnail {
  background_color_rgb: 11786481
}
chapters {
  exploration_id: "2mzzFVDLuAj8"
  chapter_thumbnail {
    background_color_rgb: 14061432
  }
  written_translations {
    key: "title"
    value {
    }
  }
  written_translations {
    key: "description"
    value {
    }
  }
  translatable_title {
    html: "What is a Ratio?"
    content_id: "title"
  }
  translatable_description {
    content_id: "description"
  }
}
chapters {
  exploration_id: "5NWuolNcwH6e"
  chapter_thumbnail {
    background_color_rgb: 14088824
  }
  written_translations {
    key: "title"
    value {
    }
  }
  written_translations {
    key: "description"
    value {
    }
  }
  translatable_title {
    html: "Order is important"
    content_id: "title"
  }
  translatable_description {
    content_id: "description"
  }
}
written_translations {
  key: "title"
  value {
  }
}
translatable_story_name {
  html: "Ratios: Part 1"
  content_id: "title"
}
