story_id: "wANbh4oOClga"
story_name: "Matthew Goes to the Bakery"
story_thumbnail {
  background_color_rgb: 11786481
}
chapters {
  exploration_id: "umPkwp0L1M0-"
  chapter_thumbnail {
    background_color_rgb: 14061432
  }
  title: "What is a Fraction?"
  description: "Matthew learns about fractions."
}
chapters {
  exploration_id: "MjZzEVOG47_1"
  chapter_thumbnail {
    background_color_rgb: 14055672
  }
  title: "The Meaning of Equal Parts"
  description: "Matthew learns about equal parts in fractions."
}
