package org.oppia.android.scripts.lint

import org.oppia.android.scripts.common.BazelClient
import org.oppia.android.scripts.common.CommandExecutorImpl
import org.oppia.android.scripts.common.ScriptBackgroundCoroutineDispatcher
import java.io.File

fun main(vararg args: String) {
  require(args.size == 2) { "Usage: bazel run //scripts:buf -- </path/to/repo_root> <mode>" }
  val repoRoot = File(args[0]).absoluteFile.normalize().also {
    check(it.exists() && it.isDirectory) {
      "Expected provided repository root to be an existing directory: ${args[0]}."
    }
  }
  val mode = when (args[1]) {
    "check" -> Buf.Mode.CHECK
    "fix" -> Buf.Mode.FIX
    else -> error("Invalid run mode: ${args[1]}. Expected one of: 'check' or 'fix'.")
  }
  ScriptBackgroundCoroutineDispatcher().use { scriptBgDispatcher ->
    val commandExecutor = CommandExecutorImpl(scriptBgDispatcher)
    val bazelClient = BazelClient(repoRoot, commandExecutor)
    Buf(repoRoot, bazelClient).runBuf(mode)
  }
}

class Buf(private val repoRoot: File, private val bazelClient: BazelClient) {
  fun runBuf(mode: Mode) {
    val bufConfig = File("buf.yaml").also { generateBufConfiguration(it) }.absoluteFile.normalize()
    val rootDirs = PROTO_ROOTS.map { protoRootPath ->
      File(repoRoot, protoRootPath).absoluteFile.normalize().also {
        check(it.exists() && it.isDirectory) {
          "Configured proto root isn't an existing directory: $protoRootPath."
        }
      }
    }
    when (mode) {
      Mode.CHECK -> {
        if (!tryRunBuf(mode, rootDirs, bufConfig)) {
          println()
          error("Buf command failed. Re-run with 'fix' in order to auto-fix issues.")
        } else println("No proto lint issues found!")
      }
      Mode.FIX -> {
        if (!tryRunBuf(mode = Mode.CHECK, rootDirs, bufConfig, printOutput = false)) {
          // There are failures, try to fix them.
          if (tryRunBuf(mode, rootDirs, bufConfig, printOutput = false)) {
            println("Checking if autofix addressed everything...")
            println()
            if (!tryRunBuf(mode = Mode.CHECK, rootDirs, bufConfig)) {
              println()
              error("Failed to autofix all issues. Please fix them manually.")
            } else println("All issues were successfully auto-fixed!")
          } else error("Autofix command itself unexpectedly failed--try re-running with check.")
        } else println("Skipping fix--there are no failures.")
      }
    }
  }

  private fun tryRunBuf(
    mode: Mode,
    rootDirs: List<File>,
    bufConfig: File,
    printOutput: Boolean = true
  ): Boolean {
    return when (mode) {
      Mode.CHECK -> {
        // First, check lint on all root files. Second, check that all lint files match formatting.
        rootDirs.all { tryRunBufLint(it, bufConfig, printOutput) } &&
          rootDirs.all { tryRunBufFormatCheck(it, printOutput) }
      }
      Mode.FIX -> rootDirs.all { tryRunBufFormatFix(it, printOutput) }
    }
  }

  private fun tryRunBufLint(rootDir: File, bufConfig: File, printOutput: Boolean): Boolean {
    val (exitCode, outputLines) = bazelClient.run(
      BUF_BINARY_TARGET,
      "lint",
      rootDir.path,
      "--config",
      bufConfig.path,
      "--disable-symlinks",
      allowFailures = true
    )
    if (printOutput) outputLines.forEach(::println)
    return exitCode == 0
  }

  private fun tryRunBufFormatCheck(rootDir: File, printOutput: Boolean): Boolean {
    val (exitCode, outputLines) = bazelClient.run(
      BUF_BINARY_TARGET,
      "format",
      rootDir.path,
      "--disable-symlinks",
      "--diff",
      "--exit-code",
      allowFailures = true
    )
    if (printOutput) outputLines.forEach(::println)
    return exitCode == 0
  }

  private fun tryRunBufFormatFix(rootDir: File, printOutput: Boolean): Boolean {
    val (exitCode, outputLines) = bazelClient.run(
      BUF_BINARY_TARGET,
      "format",
      rootDir.path,
      "--disable-symlinks",
      "--write",
      allowFailures = true
    )
    if (printOutput) outputLines.forEach(::println)
    return exitCode == 0
  }

  private fun generateBufConfiguration(destFile: File) {
    // Generates a v1 Buf configuration file (https://buf.build/docs/lint/overview/#configuration).
    destFile.writeText(
      """# Automatically generated by //scripts:buf.
version: v1
lint:
  use:${INCLUDED_LINT_CHECKS.joinToString(separator = "\n", prefix = "\n") { "    - $it" }}
  except:${EXCLUDED_LINT_CHECKS.joinToString(separator = "\n", prefix = "\n") { "    - $it" }}
"""
    )
  }

  enum class Mode(val subCommand: String) {
    CHECK("lint"),
    FIX("format")
  }

  private companion object {
    /** The individual proto directory roots in which to run Buf. */
    private val PROTO_ROOTS = listOf("model/src/main/proto", "scripts")

    /**
     * Lint checks that are to be enabled in Buf.
     *
     * 'DEFAULT' covers all checks from BASIC and MINIMAL, per https://docs.buf.build/lint-rules.
     */
    private val INCLUDED_LINT_CHECKS = listOf("DEFAULT")

    /**
     * Lint checks that are to be disabled in Buf.
     *
     * - Per https://buf.build/docs/lint/rules#package_directory_match package matching doesn't
     *   quite work correctly with how protos are set up in the codebase.
     * - Per https://buf.build/docs/lint/rules#package_version_suffix version suffixing is disabled
     *   since Android protos don't need to be versioned in how they're used.
     * - Default enum value prefixes (per https://buf.build/docs/lint/rules#default) are disabled
     *   since Java doesn't have the same namespace scoping restrictions on enums as C/C++ do, and
     *   this allows for shorter names.
     */
    private val EXCLUDED_LINT_CHECKS = listOf(
      "PACKAGE_DIRECTORY_MATCH", "PACKAGE_VERSION_SUFFIX", "ENUM_VALUE_PREFIX"
    )

    private const val BUF_BINARY_TARGET = "//third_party:buf_binary"
  }
}
