page_contents {
  html: "<p>Description of subtopic is here. <oppia-noninteractive-skillreview skill_id-with-value=\"&amp;quot;5RM9KPfQxobH&amp;quot;\" text-with-value=\"&amp;quot;This concept card demonstrates overall concept card functionality.&amp;quot;\"></oppia-noninteractive-skillreview></p>"
  content_id: "content"
}
recorded_voiceover {
  key: "content"
  value {
  }
}
written_translation {
  key: "title"
  value {
  }
}
written_translation {
  key: "content"
  value {
  }
}
skill_ids: "B39yK4cbHZYI"
skill_ids: "UxTGIJqaHMLa"
subtopic_thumbnail {
  background_color_rgb: 16741119
}
title {
  html: "Fractions of a group"
  content_id: "title"
}
