story_id: "wANbh4oOClga"
story_thumbnail {
  background_color_rgb: 11786481
}
chapters {
  exploration_id: "umPkwp0L1M0-"
  chapter_thumbnail {
    background_color_rgb: 14061432
  }
  written_translations {
    key: "title"
    value {
    }
  }
  written_translations {
    key: "description"
    value {
    }
  }
  translatable_title {
    html: "What is a Fraction?"
    content_id: "title"
  }
  translatable_description {
    html: "Matthew learns about fractions."
    content_id: "description"
  }
}
chapters {
  exploration_id: "MjZzEVOG47_1"
  chapter_thumbnail {
    background_color_rgb: 14055672
  }
  written_translations {
    key: "title"
    value {
    }
  }
  written_translations {
    key: "description"
    value {
    }
  }
  translatable_title {
    html: "The Meaning of Equal Parts"
    content_id: "title"
  }
  translatable_description {
    html: "Matthew learns about equal parts in fractions."
    content_id: "description"
  }
}
written_translations {
  key: "title"
  value {
  }
}
translatable_story_name {
  html: "Matthew Goes to the Bakery"
  content_id: "title"
}
