"""
Tests corresponding to libraries that help with Android Lint analysis.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "AndroidLintRunnerTest",
    srcs = ["AndroidLintRunnerTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/common/testing:fake_command_executor",
        "//scripts/src/java/org/oppia/android/scripts/lint:android_lint_runner",
        "//scripts/src/java/org/oppia/android/scripts/testing:test_bazel_workspace",
        "//testing:assertion_helpers",
        "//third_party:com_android_tools_lint_lint-tests",
        "//third_party:com_google_truth_truth",
    ],
)

kt_jvm_test(
    name = "LintAnalysisReporterTest",
    srcs = ["LintAnalysisReporterTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/lint:lint_reporter_lib",
        "//scripts/src/java/org/oppia/android/scripts/proto:android_lint_java_proto",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)

kt_jvm_test(
    name = "LintProjectDescriptionTest",
    srcs = ["LintProjectDescriptionTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/common:bazel_client",
        "//scripts/src/java/org/oppia/android/scripts/common/testing:fake_command_executor",
        "//scripts/src/java/org/oppia/android/scripts/lint:lint_project_description_lib",
        "//scripts/src/java/org/oppia/android/scripts/testing:test_bazel_workspace",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)

kt_jvm_test(
    name = "LintModelCreatorTest",
    srcs = ["LintModelCreatorTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/lint:lint_model_creator_lib",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)

kt_jvm_test(
    name = "LintCommonTest",
    srcs = ["LintCommonTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/lint:lint_common_lib",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)

kt_jvm_test(
    name = "LintCheckCatalogTest",
    srcs = ["LintCheckCatalogTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/lint:lint_check_catalog",
        "//testing:assertion_helpers",
        "//third_party:com_android_tools_lint_lint-checks",
        "//third_party:com_google_truth_truth",
    ],
)
