"""
Tests corresponding to libraries that help with Android Lint analysis.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "AndroidLintRunnerTest",
    srcs = ["AndroidLintRunnerTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/lint:android_lint_runner",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
    ],
)
