"""
Model classes for app-level behavior state.
"""

load("@io_bazel_rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "forced_activity_language_mode",
    srcs = ["ForcedActivityLanguageMode.kt"],
    visibility = [
        "//app:app_testing_visibility",
        "//app:app_visibility",
    ],
)
