syntax = "proto3";

package proto;

option java_package = "org.oppia.android.scripts.proto";
option java_multiple_files = true;

// Container for all Android Lint exemptions.
message AndroidLintExemptions {
  // List of exemptions applied per file.
  repeated AndroidLintExemption android_lint_exemption = 1;
}

// Represents a single exemption entry for a specific file.
message AndroidLintExemption {
  // File path for which exemptions are specified.
  string exempted_file_path = 1;
  // List of lint issues to ignore for this path.
  repeated LintIssueId lint_issue_id = 2;
}

// Enumerates all known, expected lint issues.
// Script should fail on unknown issues, prompting updates to this list.
enum LintIssueId {
  // Case when no ID is specified.
  ISSUE_UNSPECIFIED = 0;
  // Internal Errors in execution of Lint tool
  LINT_ERROR = 1;

  APP_BUNDLE_LOCALE_CHANGES = 2;
  AUTOFILL = 3;
  BACK_BUTTON = 4;
  CUSTOM_SPLASH_SCREEN = 5;
  DUPLICATE_STRINGS = 6;
  GRADLE_OVERRIDES = 7;
  IMPLIED_QUANTITY = 8;
  INCONSISTENT_LAYOUT = 9;
  KEYBOARD_INACCESSIBLE_WIDGET = 10;
  LABEL_FOR = 11;
  LOCKED_ORIENTATION_ACTIVITY = 12;
  MERGE_ROOT_FRAME = 13;
  MISSING_DEFAULT_RESOURCE = 14;
  MISSING_TRANSLATION = 15;
  MISSING_VERSION = 16;
  NEW_API = 17;
  NOTIFY_DATA_SET_CHANGED = 18;
  OBSOLETE_SDK_INT = 19;
  OVERDRAW = 20;
  REDUNDANT_LABEL = 21;
  REGISTERED = 22;
  RTL_SYMMETRY = 23;
  SELECTABLE_TEXT = 24;
  STRING_FORMAT_COUNT = 25;
  SUPPORT_ANNOTATION_USAGE = 26;
  SUSPICIOUS_INDENTATION = 27;
  SWITCH_INT_DEF = 28;
  SYNTHETIC_ACCESSOR = 29;
  TYPOGRAPHY_DASHES = 30;
  TYPOGRAPHY_QUOTES = 31;
  TYPOS = 32;
  UNKNOWN_ID_IN_LAYOUT = 33;
  UNKNOWN_NULLNESS = 34;
  UNUSED_ATTRIBUTE = 35;
  UNUSED_IDS = 36;
  UNUSED_RESOURCES = 37;
  USE_APP_TINT = 38;
  USE_COMPOUND_DRAWABLES = 39;
  USE_REQUIRE_INSTEAD_OF_GET = 40;
  USELESS_LEAF = 41;
  USELESS_PARENT = 42;
  VECTOR_PATH = 43;
  VECTOR_RASTER = 44;
}
