syntax = "proto3";

package proto;

option java_package = "org.oppia.android.scripts.proto";
option java_multiple_files = true;

// Container for all Android Lint exemptions.
message AndroidLintExemptions {
  // List of exemptions applied per file.
  repeated AndroidLintExemption android_lint_exemption = 1;
}

// Represents a single exemption entry for a specific file.
message AndroidLintExemption {
  // File path for which exemptions are specified.
  string exempted_file_path = 1;
  // List of lint issues to ignore for this path.
  repeated LintIssueId lint_issue_id = 2;
}

// Enumerates all known, expected lint issues.
// Script should fail on unknown issues, prompting updates to this list.
enum LintIssueId {
  // Case when no ID is specified.
  ISSUE_UNSPECIFIED = 0;
  // Internal Errors in execution of Lint tool
  LINT_ERROR = 1;

  APP_BUNDLE_LOCALE_CHANGES = 2;
  AUTOFILL = 3;
  BACK_BUTTON = 4;
  CUSTOM_SPLASH_SCREEN = 5;
  DUPLICATE_STRINGS = 6;
  GRADLE_OVERRIDES = 7;
  INCONSISTENT_LAYOUT = 9;
  KEYBOARD_INACCESSIBLE_WIDGET = 10;
  LOCKED_ORIENTATION_ACTIVITY = 12;
  MISSING_TRANSLATION = 15;
  MISSING_VERSION = 16;
  NOTIFY_DATA_SET_CHANGED = 18;
  OLD_TARGET_API = 19;
  OVERDRAW = 21;
  REDUNDANT_LABEL = 22;
  REGISTERED = 23;
  SELECTABLE_TEXT = 25;
  STRING_FORMAT_COUNT = 26;
  SWITCH_INT_DEF = 29;
  SYNTHETIC_ACCESSOR = 30;
  TYPOGRAPHY_DASHES = 31;
  TYPOGRAPHY_QUOTES = 32;
  UNKNOWN_NULLNESS = 35;
  UNUSED_ATTRIBUTE = 36;
  UNUSED_RESOURCES = 38;
  USE_COMPOUND_DRAWABLES = 40;
  VECTOR_PATH = 44;
  VECTOR_RASTER = 45;
}
