syntax = "proto3";

package proto;

option java_package = "org.oppia.android.scripts.proto";
option java_multiple_files = true;

// Container for all Android Lint exemptions.
message AndroidLintExemptions {
  // List of exemptions applied per file.
  repeated AndroidLintExemption android_lint_exemption = 1;
}

// Represents a single exemption entry for a specific file.
message AndroidLintExemption {
  // File path for which exemptions are specified.
  string exempted_file_path = 1;
  // List of lint issues to ignore for this path.
  repeated LintIssueId lint_issue_id = 2;
}

// Enumerates all known, expected lint issues.
// Script should fail on unknown issues, prompting updates to this list.
enum LintIssueId {
  // Case when no ID is specified.
  ISSUE_UNSPECIFIED = 0;
  // Internal Errors in execution of Lint tool
  LINT_ERROR = 1;

  APP_BUNDLE_LOCALE_CHANGES = 2;
  AUTOFILL = 3;
  BACK_BUTTON = 4;
  CUSTOM_SPLASH_SCREEN = 5;
  INCONSISTENT_LAYOUT = 6;
  KEYBOARD_INACCESSIBLE_WIDGET = 7;
  LOCKED_ORIENTATION_ACTIVITY = 8;
  MISSING_VERSION = 9;
  NOTIFY_DATA_SET_CHANGED = 10;
  OLD_TARGET_API = 11;
  OVERDRAW = 12;
  REDUNDANT_LABEL = 13;
  REGISTERED = 14;
  STRING_FORMAT_COUNT = 15;
  SWITCH_INT_DEF = 16;
  TYPOGRAPHY_DASHES = 17;
  TYPOGRAPHY_QUOTES = 18;
  USE_COMPOUND_DRAWABLES = 19;
  VECTOR_PATH = 20;
  VECTOR_RASTER = 21;
}
