"""
Test-only utilities for performance metrics logging.
"""

load("@io_bazel_rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "performance_metrics_assessor_test_module",
    testonly = True,
    srcs = ["PerformanceMetricsAssessorTestModule.kt"],
    visibility = ["//:oppia_testing_visibility"],
    deps = [
        "//:dagger",
        "//testing",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_assessor",
    ],
)
