"""
Tests for the library that provides log scheduling functionality.
"""

load("//:oppia_android_test.bzl", "oppia_android_test")

oppia_android_test(
    name = "MetricLogSchedulerModuleTest",
    srcs = ["MetricLogSchedulerModuleTest.kt"],
    custom_package = "org.oppia.android.domain.oppialogger.logscheduler",
    test_class = "org.oppia.android.domain.oppialogger.logscheduler.MetricLogSchedulerModuleTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:metric_log_scheduler_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
    ],
)

oppia_android_test(
    name = "MetricLogSchedulingWorkerSchedulerTest",
    srcs = ["MetricLogSchedulingWorkerSchedulerTest.kt"],
    custom_package = "org.oppia.android.domain.oppialogger.logscheduler",
    test_class = "org.oppia.android.domain.oppialogger.logscheduler.MetricLogSchedulingWorkerSchedulerTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:metric_log_scheduler_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:metric_log_scheduling_worker",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:scheduler",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_scheduler",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_work_manager_test_driver",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_worker_manager_test_initializer",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:androidx_work_work-runtime",
        "//third_party:androidx_work_work-testing",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
    ],
)

oppia_android_test(
    name = "MetricLogSchedulingWorkerTest",
    srcs = ["MetricLogSchedulingWorkerTest.kt"],
    custom_package = "org.oppia.android.domain.oppialogger.logscheduler",
    test_class = "org.oppia.android.domain.oppialogger.logscheduler.MetricLogSchedulingWorkerTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:metric_log_scheduler_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/logscheduler:metric_log_scheduling_worker",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_configuration_module",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_scheduler",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_work_manager_test_driver",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_worker_manager_test_initializer",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:androidx_work_work-runtime",
        "//third_party:androidx_work_work-testing",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_assessor_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
    ],
)
