package org.oppia.android.data.backends.gae.api

import android.app.Application
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import dagger.BindsInstance
import dagger.Component
import dagger.Module
import dagger.Provides
import data.src.main.java.org.oppia.android.data.backends.gae.testing.FeedbackReportingServiceTestOrchestrator
import okhttp3.mockwebserver.MockWebServer
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.oppia.android.data.backends.gae.RetrofitModule
import org.oppia.android.data.backends.gae.RetrofitServiceModule
import org.oppia.android.data.backends.gae.testing.NetworkConfigTestModule
import org.oppia.android.testing.robolectric.RobolectricModule
import org.oppia.android.testing.threading.TestDispatcherModule
import org.robolectric.annotation.Config
import org.robolectric.annotation.LooperMode
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Tests for [FeedbackReportingService] using [FeedbackReportingServiceTestOrchestrator].
 *
 * Note that this test largely verifies that the test infrastructure and Retrofit configurations for
 * the service are correct, as the service itself is generated by Retrofit.
 */
@RunWith(AndroidJUnit4::class)
@LooperMode(LooperMode.Mode.PAUSED)
@Config(application = FeedbackReportingServiceTest.TestApplication::class)
// Function name: test names are conventionally named with underscores.
@Suppress("FunctionName")
class FeedbackReportingServiceTest {
  @Inject lateinit var feedbackReportingService: FeedbackReportingService
  @Inject lateinit var serviceOrchestrator: FeedbackReportingServiceTestOrchestrator
  @Inject lateinit var mockWebServer: MockWebServer

  @Before
  fun setUp() {
    setUpTestApplicationComponent()
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_responseIsSuccess() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val report = serviceOrchestrator.loadGaeFeedbackReportFromTestData("feedback_reporting.json")
    val response = feedbackReportingService.postFeedbackReport(report).execute()

    assertThat(response.isSuccessful).isTrue()
  }

  @Test
  fun testService_postRequest_withResponseSetToFail_responseIsFailure() {
    serviceOrchestrator.setNextResponseAsServerError()

    val report = serviceOrchestrator.loadGaeFeedbackReportFromTestData("feedback_reporting.json")
    val response = feedbackReportingService.postFeedbackReport(report).execute()

    assertThat(response.isSuccessful).isFalse()
    assertThat(response.raw().code).isEqualTo(500)
  }

  @Test
  fun testService_postRequest_sendsToCorrectUrl() {
    serviceOrchestrator.setNextResponseAsServerError()

    val report = serviceOrchestrator.loadGaeFeedbackReportFromTestData("feedback_reporting.json")
    feedbackReportingService.postFeedbackReport(report).execute()

    val capturedRequest = mockWebServer.takeRequest()
    val requestUrl = capturedRequest.requestUrl?.toUrl()
    assertThat(requestUrl?.path).isEqualTo("/android_feedback_reporting/incoming_report")
  }

  @Test
  fun testService_postRequest_sendsCorrectReportBody() {
    serviceOrchestrator.setNextResponseAsServerError()

    val report = serviceOrchestrator.loadGaeFeedbackReportFromTestData("feedback_reporting.json")
    feedbackReportingService.postFeedbackReport(report).execute()

    val capturedRequest = serviceOrchestrator.takeGaeFeedbackReportRequest()
    assertThat(capturedRequest).isEqualTo(report)
  }

  private fun setUpTestApplicationComponent() {
    ApplicationProvider.getApplicationContext<TestApplication>().inject(this)
  }

  // TODO(#89): Move this to a common test application component.
  @Module
  class TestModule {
    @Provides
    @Singleton
    fun provideContext(application: Application): Context {
      return application
    }
  }

  // TODO(#89): Move this to a common test application component.
  @Singleton
  @Component(
    modules = [
      TestModule::class, RetrofitModule::class, RetrofitServiceModule::class,
      TestDispatcherModule::class, NetworkConfigTestModule::class, RobolectricModule::class
    ]
  )
  interface TestApplicationComponent {
    @Component.Builder
    interface Builder {
      @BindsInstance
      fun setApplication(application: Application): Builder

      fun build(): TestApplicationComponent
    }

    fun inject(test: FeedbackReportingServiceTest)
  }

  class TestApplication : Application() {
    private val component: TestApplicationComponent by lazy {
      DaggerFeedbackReportingServiceTest_TestApplicationComponent.builder()
        .setApplication(this)
        .build()
    }

    fun inject(test: FeedbackReportingServiceTest) = component.inject(test)
  }
}
