package org.oppia.android.data.backends.gae.api

import android.app.Application
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import dagger.BindsInstance
import dagger.Component
import dagger.Module
import dagger.Provides
import okhttp3.mockwebserver.MockWebServer
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.oppia.android.data.backends.gae.RetrofitModule
import org.oppia.android.data.backends.gae.RetrofitServiceModule
import org.oppia.android.util.properties.CustomPropertyRetrieverProdModule
import org.oppia.android.data.backends.gae.model.GaePlatformParameterValue
import org.oppia.android.data.backends.gae.model.GaePlatformParameterValue.BooleanValue
import org.oppia.android.data.backends.gae.model.GaePlatformParameterValue.IntValue
import org.oppia.android.data.backends.gae.model.GaePlatformParameterValue.StringValue
import org.oppia.android.data.backends.gae.testing.NetworkConfigTestModule
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator.Companion.REMOTE_PLATFORM_PARAMETERS_WITH_UNSUPPORTED_TYPE
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator.Companion.TEST_BOOLEAN_PARAM_NAME
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator.Companion.TEST_INTEGER_PARAM_NAME
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator.Companion.TEST_STRING_PARAM_NAME
import org.oppia.android.data.backends.gae.testing.PlatformParameterServiceTestOrchestrator.Companion.TEST_UNKNOWN_PARAM_NAME
import org.oppia.android.testing.robolectric.RobolectricModule
import org.oppia.android.testing.threading.TestDispatcherModule
import org.robolectric.annotation.Config
import org.robolectric.annotation.LooperMode
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Tests for [PlatformParameterService] using [PlatformParameterServiceTestOrchestrator].
 *
 * Note that this test largely verifies that the test infrastructure and Retrofit configurations for
 * the service are correct, as the service itself is generated by Retrofit.
 */
@RunWith(AndroidJUnit4::class)
@LooperMode(LooperMode.Mode.PAUSED)
@Config(application = PlatformParameterServiceTest.TestApplication::class)
// Function name: test names are conventionally named with underscores.
@Suppress("FunctionName")
class PlatformParameterServiceTest {
  @Inject lateinit var parameterService: PlatformParameterService
  @Inject lateinit var serviceOrchestrator: PlatformParameterServiceTestOrchestrator
  @Inject lateinit var mockWebServer: MockWebServer

  @Before
  fun setUp() {
    setUpTestApplicationComponent()
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_responseIsSuccess() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val response = parameterService.getPlatformParameters().execute()

    assertThat(response.isSuccessful).isTrue()
  }

  @Test
  fun testService_postRequest_withResponseSetToEmpty_returnsEmptyMap() {
    serviceOrchestrator.setNextResponseAsSuccess(parameterValues = emptyMap())

    val response = parameterService.getPlatformParameters().execute()

    val params = response.body()
    assertThat(params).isNotNull()
    assertThat(params).isEmpty()
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_returnsMapOfParameterValues() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val response = parameterService.getPlatformParameters().execute()

    val params = response.body()
    assertThat(params).isNotNull()
    assertThat(params).isNotEmpty()
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_returnsStringParameterValue() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val response = parameterService.getPlatformParameters().execute()

    val param = response.body()?.find { it.name == TEST_STRING_PARAM_NAME }?.value as? StringValue
    assertThat(param?.value).isEqualTo("test_string_param_value")
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_returnsIntegerParameterValue() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val response = parameterService.getPlatformParameters().execute()

    val param = response.body()?.find { it.name == TEST_INTEGER_PARAM_NAME }?.value as? IntValue
    assertThat(param?.value).isEqualTo(1)
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_returnsBooleanParameterValue() {
    serviceOrchestrator.setNextResponseAsSuccess()

    val response = parameterService.getPlatformParameters().execute()

    val param = response.body()?.find { it.name == TEST_BOOLEAN_PARAM_NAME }?.value as? BooleanValue
    assertThat(param?.value).isTrue()
  }

  @Test
  fun testService_postRequest_withResponseSetToSuccess_containsInvalidValue_returnsUnknownValue() {
    serviceOrchestrator.setNextResponseAsSuccess(REMOTE_PLATFORM_PARAMETERS_WITH_UNSUPPORTED_TYPE)

    val response = parameterService.getPlatformParameters().execute()

    // Invalid/unsupported parameter types should be correctly processed.
    val param = response.body()?.find { it.name == TEST_UNKNOWN_PARAM_NAME }
    assertThat(param).isEqualTo(GaePlatformParameterValue.UnsupportedValue)
  }

  @Test
  fun testService_postRequest_withResponseSetToFail_responseIsFailure() {
    serviceOrchestrator.setNextResponseAsServerError()

    val response = parameterService.getPlatformParameters().execute()

    assertThat(response.isSuccessful).isFalse()
    assertThat(response.raw().code).isEqualTo(500)
  }

  @Test
  fun testService_postRequest_sendsToCorrectUrl() {
    serviceOrchestrator.setNextResponseAsSuccess()

    parameterService.getPlatformParameters().execute()

    val capturedRequest = mockWebServer.takeRequest()
    val requestUrl = capturedRequest.requestUrl?.toUrl()
    assertThat(requestUrl?.path).isEqualTo("/platform_features_evaluation_handler")
  }

  @Test
  fun testService_postRequest_sendsVersionAndAndroidAppType() {
    serviceOrchestrator.setNextResponseAsSuccess()

    parameterService.getPlatformParameters().execute()

    val capturedRequest = mockWebServer.takeRequest()
    assertThat(capturedRequest.requestUrl?.queryParameter("app_version")).isEqualTo("1.2")
    assertThat(capturedRequest.requestUrl?.queryParameter("platform_type")).isEqualTo("Android")
  }

  private fun setUpTestApplicationComponent() {
    ApplicationProvider.getApplicationContext<TestApplication>().inject(this)
  }

  // TODO(#89): Move this to a common test application component.
  @Module
  class TestModule {
    @Provides
    @Singleton
    fun provideContext(application: Application): Context {
      return application
    }
  }

  // TODO(#89): Move this to a common test application component.
  @Singleton
  @Component(
    modules = [
      NetworkConfigTestModule::class,
      RetrofitModule::class,
      RetrofitServiceModule::class,
      CustomPropertyRetrieverProdModule::class,
      RobolectricModule::class,
      TestDispatcherModule::class,
      TestModule::class
    ]
  )
  interface TestApplicationComponent {
    @Component.Builder
    interface Builder {
      @BindsInstance
      fun setApplication(application: Application): Builder
      fun build(): TestApplicationComponent
    }

    fun inject(test: PlatformParameterServiceTest)
  }

  class TestApplication : Application() {
    private val component: TestApplicationComponent by lazy {
      DaggerPlatformParameterServiceTest_TestApplicationComponent.builder()
        .setApplication(this)
        .build()
    }

    fun inject(test: PlatformParameterServiceTest) = component.inject(test)
  }
}
