"""
Library for providing log uploading functionality to the Oppia android app.
"""

load("@io_bazel_rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "scheduler",
    srcs = ["LogReportWorkerScheduler.kt"],
    visibility = ["//domain:domain_testing_visibility"],
    deps = [
        ":worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:startup_worker_schedule_readiness_listener",
    ],
)

kt_android_library(
    name = "worker",
    srcs = ["LogUploadWorker.kt"],
    visibility = ["//domain:domain_testing_visibility"],
    deps = [
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:controller",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:data_controller",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:performance_metrics_controller",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions:controller",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//utility/src/main/java/org/oppia/android/util/logging:console_logger",
        "//utility/src/main/java/org/oppia/android/util/logging:event_logger",
        "//utility/src/main/java/org/oppia/android/util/logging:exception_logger",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_event_logger",
    ],
)

kt_android_library(
    name = "worker_module",
    srcs = ["LogReportWorkerModule.kt"],
    visibility = ["//:oppia_prod_module_visibility"],
    deps = [
        ":scheduler",
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:startup_listener",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
    ],
)
