"""
Tests for library that provides support for downloading platform parameter states from Oppia web.
"""

load("//:oppia_android_test.bzl", "oppia_android_test")

oppia_android_test(
    name = "PlatformParameterSyncUpWorkerModuleTest",
    srcs = ["PlatformParameterSyncUpWorkerModuleTest.kt"],
    custom_package = "org.oppia.android.domain.platformparameter.syncup",
    test_class = "org.oppia.android.domain.platformparameter.syncup.PlatformParameterSyncUpWorkerModuleTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter/syncup",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
    ],
)

oppia_android_test(
    name = "PlatformParameterSyncUpWorkerSchedulerTest",
    srcs = ["PlatformParameterSyncUpWorkerSchedulerTest.kt"],
    custom_package = "org.oppia.android.domain.platformparameter.syncup",
    test_class = "org.oppia.android.domain.platformparameter.syncup.PlatformParameterSyncUpWorkerSchedulerTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//data/src/main/java/org/oppia/android/data/backends/gae:retrofit_module",
        "//data/src/main/java/org/oppia/android/data/backends/gae/testing:network_config_test_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter/syncup",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_scheduler",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_work_manager_test_driver",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_worker_manager_test_initializer",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:androidx_work_work-runtime",
        "//third_party:androidx_work_work-testing",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_util_module",
        "//utility/src/main/java/org/oppia/android/util/properties:prod_module",
    ],
)

oppia_android_test(
    name = "PlatformParameterSyncUpWorkerTest",
    srcs = ["PlatformParameterSyncUpWorkerTest.kt"],
    custom_package = "org.oppia.android.domain.platformparameter.syncup",
    test_class = "org.oppia.android.domain.platformparameter.syncup.PlatformParameterSyncUpWorkerTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//data/src/main/java/org/oppia/android/data/backends/gae:retrofit_module",
        "//data/src/main/java/org/oppia/android/data/backends/gae/testing:network_config_test_module",
        "//data/src/main/java/org/oppia/android/data/backends/gae/testing:platform_parameter_service_test_orchestrator",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:cpu_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader:worker",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader:worker_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/platformparameter/syncup",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:oppia_worker",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_configuration_module",
        "//domain/src/main/java/org/oppia/android/domain/workmanager:work_manager_scheduler",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_work_manager_test_driver",
        "//domain/src/main/java/org/oppia/android/domain/workmanager/testing:oppia_worker_manager_test_initializer",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/firebase:test_authentication_module",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:androidx_work_work-runtime",
        "//third_party:androidx_work_work-testing",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
        "//utility/src/main/java/org/oppia/android/util/logging/firebase:debug_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_assessor_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics:performance_metrics_configurations_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_util_module",
        "//utility/src/main/java/org/oppia/android/util/properties:prod_module",
    ],
)
