"""
This package contains custom Bazel build configuration flags and settings for release automation.
"""

load("@bazel_skylib//rules:common_settings.bzl", "bool_flag", "string_flag")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load(
    "//config:download_assets.bzl",
    "update_pinned_lesson_versions",
)

exports_files(
    glob(["proguard/*.pro"]),
    visibility = ["//:oppia_binary_visibility"],
)

exports_files(
    glob(["lessons/*.textproto"]),
    visibility = ["//domain:domain_visibility"],
)

# Build-time boolean flag for enabling Firebase Analytics and Crashlytics collection.
bool_flag(
    name = "enable_firebase_analytics",
    build_setting_default = False,
    visibility = ["//:oppia_binary_visibility"],
)

# Build-time boolean flag for whether third-party license texts should be downloaded and included.
bool_flag(
    name = "download_license_texts",
    build_setting_default = False,
)

# Build-time boolean flag for whether the app's production Firebase configuration file should be
# downloaded and used.
bool_flag(
    name = "download_firebase_config",
    build_setting_default = False,
)

# Build setting to allow passing an arbitrary host path for the signing keystore file.
string_flag(
    name = "keystore_file",
    build_setting_default = "",
    visibility = ["//:oppia_binary_visibility"],
)

# Build setting to allow passing an arbitrary host path for the signing keystore password file.
string_flag(
    name = "keystore_password_file",
    build_setting_default = "",
    visibility = ["//:oppia_binary_visibility"],
)

# Build-time string flag that should contain the signing keystore's key alias.
string_flag(
    name = "key_alias",
    build_setting_default = "androiddebugkey",
    visibility = ["//:oppia_binary_visibility"],
)

# Build-time string flag that should contain the app's Firebase project ID (when
# download_firebase_config is also set to true).
string_flag(
    name = "firebase_project_id",
    build_setting_default = "oppia-android",
    visibility = ["//app:app_visibility"],
)

# Build-time string flag that should contain the app's Firebase app ID (when
# download_firebase_config is also set to true).
string_flag(
    name = "firebase_app_id",
    build_setting_default = "",
    visibility = ["//app:app_visibility"],
)

# Build setting to allow developers to pass their local GAE API key file.
string_flag(
    name = "proto_api_key_file",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

# Build-time string flag to specify which assets configuration to use (dev, alpha, or prod).
string_flag(
    name = "assets_type",
    build_setting_default = "dev",
    values = [
        "dev",
        "alpha",
        "prod",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "firebase_analytics_enabled",
    flag_values = {
        ":enable_firebase_analytics": "True",
    },
    visibility = ["//:oppia_binary_visibility"],
)

config_setting(
    name = "download_license_texts_enabled",
    flag_values = {
        ":download_license_texts": "True",
    },
    visibility = ["//app:app_visibility"],
)

config_setting(
    name = "download_firebase_config_enabled",
    flag_values = {
        ":download_firebase_config": "True",
    },
    visibility = ["//app:app_visibility"],
)

# Enabled when alpha assets are requested.
config_setting(
    name = "assets_type_alpha",
    flag_values = {
        ":assets_type": "alpha",
    },
    visibility = ["//visibility:public"],
)

# Enabled when production assets are requested.
config_setting(
    name = "assets_type_prod",
    flag_values = {
        ":assets_type": "prod",
    },
    visibility = ["//visibility:public"],
)

update_pinned_lesson_versions(
    name = "update_pinned_lesson_versions",
    download_config = select({
        "//config:assets_type_alpha": "@oppia_android_asset_pipeline//scripts:assets/alpha_download_config.textproto",
        "//config:assets_type_prod": "@oppia_android_asset_pipeline//scripts:assets/prod_download_config.textproto",
        "//conditions:default": "@oppia_android_asset_pipeline//scripts:assets/prod_download_config.textproto",
    }),
    pinned_versions = select({
        "//config:assets_type_alpha": "//config:lessons/alpha_pinned_lesson_versions.textproto",
        "//config:assets_type_prod": "//config:lessons/prod_pinned_lesson_versions.textproto",
        "//conditions:default": "//config:lessons/prod_pinned_lesson_versions.textproto",
    }),
    tags = ["manual"],
    testonly = True,
)
