package androidx.databinding;
// TODO(#1683): Remove when android_local_test works with data-binding.
/**
 * Generated code necessary to run tests with Bazel.
 *
 * Typically, this code is generated by Bazel and included in the srcs list when running tests.
 * However, the `enable_data_binding` flag somehow affects this process. For now, this file must be
 * included in the srcs list of any Bazel test in app module.
 */
public final class DataBinderMapperImpl extends MergedDataBinderMapper {
  DataBinderMapperImpl() {
    addMapper(new org.oppia.android.app.test.DataBinderMapperImpl());
  }
}
