package androidx.databinding;

// TODO(#1683): Remove when android_local_test works with data-binding.
/**
 * Generated code necessary to run tests with Bazel.
 * <p/>
 * Typically, this code is generated by Bazel and included in the srcs list when running tests.
 * However, even enabling data-binding for the test doesn't actually generate this file, and it's
 * needed at runtime when interacting with generated data-binding sources.
 */
public final class DataBinderMapperImpl extends MergedDataBinderMapper {

  DataBinderMapperImpl() {
    addMapper(new org.oppia.android.app.databinding.DataBinderMapperImpl());
  }
}
