"""
Tests corresponding to binary file checks, such as ensuring that no unexpected binary files
are present in the repository.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "BinaryFileCheckTest",
    srcs = ["BinaryFileCheckTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/binary:binary_file_check_lib",
        "//testing:assertion_helpers",
        "//third_party:com_google_truth_truth",
        "//third_party:org_jetbrains_kotlin_kotlin-test-junit",
    ],
)
