"""
Tests corresponding to asset transformation scripts.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "ImageRepairerTest",
    srcs = ["ImageRepairerTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/assets:image_repairer",
        "//third_party:com_google_truth_truth",
        "//third_party:org_jetbrains_kotlin_kotlin-test-junit",
    ],
)
