"""
Tests for app-level model classes.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "ForcedActivityLanguageModeTest",
    srcs = ["ForcedActivityLanguageModeTest.kt"],
    deps = [
        "//app/src/main/java/org/oppia/android/app/model:forced_activity_language_mode",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
    ],
)
