load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

package(
    default_visibility = ["//data:__pkg__"],
)

kt_android_library(
    name = "data",
    srcs = glob(["java/**/*.kt"]),
    deps = [
    ],
    manifest = "AndroidManifest.xml",
)
