#!/bin/sh

# INSTRUCTIONS:
# This script will run the pre-commit checks in the given order
# Ktlint
#

# this will run the ktlint check script
bash ktlint-pre-commit

# TODO() Add Bazel Linter to the project #1736
# TODO() Add Java Linter to the project #1735
# TODO() Add an XML Linter to the project #970
# TODO() Add Buf linter
