"""
Tests corresponding to GAE proto transformation utilities.
"""

load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "ProtoVersionProviderTest",
    srcs = ["ProtoVersionProviderTest.kt"],
    deps = [
        "//scripts/src/java/org/oppia/android/scripts/gae/proto:proto_version_provider",
        "//third_party:com_google_truth_truth",
        "//third_party:org_jetbrains_kotlin_kotlin-test-junit",
    ],
)
