file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "^import .+?support.+?$"
  failure_message: "AndroidX should be used instead of the support library"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "announceForAccessibility\\("
  failure_message: "Please use AccessibilityService instead."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityServiceImpl.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "announceForAccessibilityForView\\("
  failure_message: "When using announceForAccessibility, please add an exempt file in file_content_validation_checks.textproto."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/accessibility/FakeAccessibilityServiceTest.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityService.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityServiceImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/accessibility/FakeAccessibilityService.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "CoroutineWorker"
  failure_message: "For stable tests, prefer using ListenableWorker with an Oppia-managed dispatcher."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "SettableFuture"
  failure_message: "SettableFuture should only be used in pre-approved locations since it's easy to potentially mess up & lead to a hanging ListenableFuture. If using a Deferred, convert it to a ListenableFuture using asListenableFuture()."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "<include"
  failure_message: "Remove <include .../> tag from layouts and instead use the widget directly, e.g. AppBarLayout."
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "android:gravity=\"left\""
  failure_message: "Use android:gravity=\"start\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "android:gravity=\"right\""
  failure_message: "Use android:gravity=\"end\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "android:layout_gravity=\"left\""
  failure_message: "Use android:layout_gravity=\"start\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "android:layout_gravity=\"right\""
  failure_message: "Use android:layout_gravity=\"end\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "paddingLeft|paddingRight|drawableLeft|drawableRight|layout_alignLeft|layout_alignRight|layout_marginLeft|layout_marginRight|layout_alignParentLeft|layout_alignParentRight|layout_toLeftOf|layout_toRightOf|layout_constraintLeft_toLeftOf|layout_constraintLeft_toRightOf|layout_constraintRight_toLeftOf|layout_constraintRight_toRightOf|layout_goneMarginLeft|layout_goneMarginRight"
  failure_message: "Use start/end versions of layout properties, instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "app:barrierDirection=\"left\""
  failure_message: "Use app:barrierDirection=\"start\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "app:barrierDirection=\"right\""
  failure_message: "Use app:barrierDirection=\"end\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "motion:dragDirection=\"left\""
  failure_message: "Use motion:dragDirection=\"start\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "motion:dragDirection=\"right\""
  failure_message: "Use motion:dragDirection=\"end\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "motion:touchAnchorSide=\"left\""
  failure_message: "Use motion:touchAnchorSide=\"start\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "motion:touchAnchorSide=\"right\""
  failure_message: "Use motion:touchAnchorSide=\"end\", instead, for proper RTL support"
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/strings\\.xml"
  prohibited_content_regex: "Oppia"
  failure_message: "Oppia should never used directly in a string (since it shouldn't be translated). Instead, use a parameter & insert the string retrieved from app_name."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/strings\\.xml"
  prohibited_content_regex: "translatable=\"false\""
  failure_message: "Untranslatable strings should go in untranslated_strings.xml, instead."
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "<string name=\"[^\"]+\">"
  failure_message: "All strings outside strings.xml must be marked as not translatable, or moved to strings.xml."
  exempted_file_patterns: "app/src/main/res/values.*?/strings\\.xml"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "<plurals name=\"[^\"]+\">"
  failure_message: "All plurals outside strings.xml must be marked as not translatable, or moved to strings.xml."
  exempted_file_patterns: "app/src/main/res/values.*?/strings\\.xml"
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/strings\\.xml"
  prohibited_content_regex: "CDATA"
  failure_message: "CDATA isn't handled by Translatewiki correctly. Use escaped HTML, instead."
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "android.text.BidiFormatter"
  failure_message: "Do not use Android's BidiFormatter directly. Instead, use AndroidX's BidiFormatter for KitKat compatibility."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "androidx.core.text.BidiFormatter"
  failure_message: "Do not use AndroidX's BidiFormatter directly. Instead, use the wrapper utility OppiaBidiFormatter so that tests can verify that formatting actually occurs on select strings."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/robolectric/ShadowBidiFormatter.kt"
  exempted_file_name: "testing/src/test/java/org/oppia/android/testing/robolectric/ShadowBidiFormatterTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/OppiaBidiFormatterImpl.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "(format|getString|getStringArray|getQuantityString|getQuantityText|toLowerCase|toUpperCase|capitalize|decapitalize|lowercase|uppercase|replaceFirstChar)\\("
  failure_message: "String formatting and resource retrieval should go through AppLanguageResourceHandler, OppiaLocale.DisplayLocale, or OppiaLocale.MachineLocale depending on the context (see each class's documentation for details on when each should be used)."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/translation/AppLanguageResourceHandler.kt"
  exempted_file_name: "domain/src/main/java/org/oppia/android/domain/util/JsonExtensions.kt"
  exempted_file_name: "domain/src/main/java/org/oppia/android/domain/util/WorkDataExtensions.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/onboarding/AppStartupStateControllerTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/OppiaTestRunner.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/junit/ParameterizedMethod.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/time/FakeOppiaClock.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/extensions/BundleExtensions.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/DisplayLocaleImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/MachineLocaleImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/OppiaLocale.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt"
  exempted_file_patterns: "app/src/test/.+?Test\\.kt"
  exempted_file_patterns: "app/src/sharedTest/.+?Test\\.kt"
  exempted_file_patterns: "scripts/.+"
}
file_content_checks {
  file_path_regex: ".+?\\.java"
  prohibited_content_regex: "(format|getString|getStringArray|getQuantityString|getQuantityText|toLowerCase|toUpperCase)\\("
  failure_message: "String formatting and resource retrieval should go through AppLanguageResourceHandler, OppiaLocale.DisplayLocale, or OppiaLocale.MachineLocale depending on the context (see each class's documentation for details on when each should be used)."
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "ignoreCase\\s*?="
  failure_message: "Case-insensitive string operations should be performed using MachineLocale."
  exempted_file_patterns: "testing/src/main/.+?\\.kt"
  exempted_file_patterns: "scripts/.+"
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "(format|getString|getStringArray)\\("
  failure_message: "String formatting and resource retrieval in layouts should go through AppLanguageResourceHandler."
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "@string/[^\\s]+?\\("
  failure_message: "String formatting and quantity string building shouldn't be done directly through databinding. Instead, pass in AppLanguageResourceHandler from the view model or call a new function through the view model to compute the string. Both should use the handler's locale-safe formatting/quantity string methods."
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "@plurals/[^\\s]+?\\("
  failure_message: "String plurals shouldn't be constructed directly through databinding. Instead, pass in AppLanguageResourceHandler from the view model or call a new function through the view model to compute the string. Both should use the handler's locale-safe formatting/quantity string methods."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values.*?/strings\\.xml"
  prohibited_content_regex: "[^%]*%(\\d+\\$)?[A-Za-z&&[^s]]"
  failure_message: "Only string type specifiers should use for strings (to avoid runtime errors due to bidirectional wrapping requirements)."
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "\\sActivity\\("
  failure_message: "Activity should never be subclassed. Use AppCompatActivity, instead."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "\\sAppCompatActivity\\("
  failure_message: "Never subclass AppCompatActivity directly. Instead, use InjectableAppCompatActivity."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableAppCompatActivity.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/splash/SplashActivity.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/testing/.*?TestActivity.kt$"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/TextInputActionTestActivity.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "\\sInjectableAppCompatActivity\\("
  failure_message: "Never subclass InjectableAppCompatActivity directly. Instead, use InjectableSystemLocalizedAppCompatActivity or InjectableAutoLocalizedAppCompatActivity."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableSystemLocalizedAppCompatActivity.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableAutoLocalizedAppCompatActivity.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "\\sDialogFragment\\("
  failure_message: "DialogFragment should never be subclassed. Use InjectableDialogFragment, instead."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/fragment/InjectableDialogFragment.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?AndroidManifest\\.xml"
  prohibited_content_regex: "android:configChanges"
  failure_message: "Never explicitly handle configuration changes. Instead, use saved instance states for retaining state across rotations. For other types of configuration changes, follow up with the developer mailing list with how to proceed if you think this is a legitimate case."
}
file_content_checks {
  file_path_regex: ".+?\\.xml"
  prohibited_content_regex: "(android:drawableStart)|(android:drawableEnd)|(android:drawableTop)|(android:drawableBottom)|(android:src)"
  failure_message: "Drawable start/end/top/bottom & image source should use the compat versions, instead, e.g.: app:drawableStartCompat or app:srcCompat, to ensure that vector drawables can load properly in SDK <21 environments."
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "java.util.Optional"
  failure_message: "Prefer using com.google.common.base.Optional (Guava's Optional) since desugaring has some incompatibilities between Bazel & KitKat builds."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "java\\.util\\.Calendar"
  failure_message: "Don't use Calendar directly. Instead, use OppiaClock and/or OppiaLocale for calendar-specific operations."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/time/FakeOppiaClock.kt"
  exempted_file_name: "testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/MachineLocaleImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/system/OppiaClock.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "java\\.util\\.Date"
  failure_message: "Don't use Date directly. Instead, perform date-based operations using OppiaLocale."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/splash/SplashActivityTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/onboarding/AppStartupStateControllerTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/time/FakeOppiaClock.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/DisplayLocaleImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/system/OppiaClock.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/MachineLocaleImpl.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "java\\.text"
  failure_message: "Don't perform date/time formatting directly. Instead, use OppiaLocale."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/splash/SplashActivityTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/onboarding/AppStartupStateControllerTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/time/FakeOppiaClock.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/DisplayLocaleImpl.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/locale/MachineLocaleImpl.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "java\\.util\\.Locale"
  failure_message: "Don't use Locale directly. Instead, use LocaleController, or OppiaLocale & its subclasses."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/player/audio/LanguageDialogFragment.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AppVersionActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/parser/HtmlParserTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/parser/ListItemLeadingMarginSpanTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/splash/SplashActivityTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/junit/InitializeDefaultLocaleRule.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/junit/ParameterizedMethod.kt"
  exempted_file_name: "testing/src/main/java/org/oppia/android/testing/robolectric/ShadowBidiFormatter.kt"
  exempted_file_name: "testing/src/test/java/org/oppia/android/testing/robolectric/ShadowBidiFormatterTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/logging/firebase/FirebaseAnalyticsEventLogger.kt"
  exempted_file_patterns: "app/src/(?:((main)|(test)))/java/org/oppia/android/app/translation/.+?\\.kt"
  exempted_file_patterns: "domain/src/main/java/org/oppia/android/domain/locale/.+?\\.kt"
  exempted_file_patterns: "domain/src/test/java/org/oppia/android/domain/.+?\\.kt"
  exempted_file_patterns: "scripts/.+?\\.kt"
  exempted_file_patterns: "utility/src/(?:((main)|(test)))/java/org/oppia/android/util/locale/.+?\\.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "kotlin\\.properties\\.Delegates"
  failure_message: "Don't use Delegates; use a lateinit var or nullable primitive var default-initialized to null, instead. Delegates uses reflection internally, have a non-trivial initialization cost, and can cause breakages on KitKat devices. See #3939 for more context."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: "BUILD"
  prohibited_content_regex: "^proto_library\\("
  failure_message: "Don't use proto_library. Use oppia_proto_library instead."
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "OppiaParameterizedTestRunner"
  failure_message: "To use OppiaParameterizedTestRunner, please add an exemption to file_content_validation_checks.textproto and add an explanation for your use case in your PR description. Note that parameterized tests should only be used in special circumstances where a single behavior can be tested across multiple inputs, or for especially large test suites that can be trivially reduced."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/customview/interaction/MathExpressionInteractionsViewTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/splash/SplashActivityTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/translation/AppLanguageResourceHandlerTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/utility/math/MathExpressionAccessibilityUtilTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/algebraicexpressioninput/AlgebraicExpressionInputIsEquivalentToRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/algebraicexpressioninput/AlgebraicExpressionInputMatchesExactlyWithRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/algebraicexpressioninput/AlgebraicExpressionInputMatchesUpToTrivialManipulationsRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/mathequationinput/MathEquationInputIsEquivalentToRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/mathequationinput/MathEquationInputMatchesExactlyWithRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/mathequationinput/MathEquationInputMatchesUpToTrivialManipulationsRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/numericexpressioninput/NumericExpressionInputIsEquivalentToRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/numericexpressioninput/NumericExpressionInputMatchesExactlyWithRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/classify/rules/numericexpressioninput/NumericExpressionInputMatchesUpToTrivialManipulationsRuleClassifierProviderTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/onboarding/AppStartupStateControllerTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/oppialogger/analytics/FeatureFlagsLoggerTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLoggerTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/test/java/org/oppia/android/testing/logging/TestSyncStatusManagerTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/logging/EventBundleCreatorTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/logging/performancemetrics/PerformanceMetricsAssessorImplTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/ExpressionToComparableOperationConverterTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/MathExpressionExtensionsTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/MathExpressionParserTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/MathTokenizerTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/PolynomialExtensionsTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/math/RealExtensionsTest.kt"
  exempted_file_name: "utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/onboarding/DeprecationControllerTest.kt"
  exempted_file_patterns: "testing/src/main/java/org/oppia/android/testing/junit/.+?\\.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "android\\.content\\.ClipboardManager"
  failure_message: "Don't use Android's ClipboardManager directly. Instead, use ClipboardController."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/learneranalytics/ProfileAndDeviceIdFragmentTest.kt"
  exempted_file_name: "domain/src/main/java/org/oppia/android/domain/clipboard/ClipboardController.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/clipboard/ClipboardControllerTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/component_colors.xml|app/src/main/res/values/color_palette.xml"
  prohibited_content_regex: "name=.+(?<!_color).>@|name=.*[A-Z].*>@"
  failure_message: "All color declarations in component_color.xml and color_palette.xml should end with _color suffix following snake_case naming convention."
}
file_content_checks {
  file_path_regex: "app/src/main/res/layout.*?/.+?\\.xml"
  prohibited_content_regex: "@color/(?!component_color_).+|\"#\\p{XDigit}+\""
  failure_message: "Only colors from component_colors.xml may be used in layouts."
}
file_content_checks {
  file_path_regex: "app/src/main/res/drawable.*?/.+?\\.xml"
  prohibited_content_regex: "@color/(?!component_color_).+|\"#\\p{XDigit}+\""
  failure_message: "Only colors from component_colors.xml may be used in drawables except vector assets."
  exempted_file_patterns: "app/src/main/res/drawable.*?/(ic_|lesson_thumbnail_graphic_).+?\\.xml"
  exempted_file_patterns: "app/src/main/res/drawable/full_oppia_logo.xml"
  exempted_file_patterns: "app/src/main/res/drawable/learner_otter.xml"
  exempted_file_patterns: "app/src/main/res/drawable/otter.xml"
  exempted_file_patterns: "app/src/main/res/drawable/parent_teacher_otter.xml"
  exempted_file_patterns: "app/src/main/res/drawable/profile_image_shadow.xml"
  exempted_file_patterns: "app/src/main/res/drawable/rounded_white_background_with_shadow.xml"
  exempted_file_patterns: "app/src/main/res/drawable/selected_region_background.xml"
  exempted_file_patterns: "app/src/main/res/drawable/splash_page.xml"
  exempted_file_patterns: "app/src/main/res/drawable/survey_nps_radio_selected_color.xml"
  exempted_file_patterns: "app/src/main/res/drawable/survey_nps_radio_unselected_color.xml"
}
file_content_checks {
  file_path_regex: "app/src/main/java/org/oppia/android/app.?/.+(ActivityPresenter|FragmentPresenter|ViewPresenter|Activity|Fragment|View)\\.kt"
  prohibited_content_regex: "R.color.(?!component_color_).+"
  failure_message: "Only colors from component_colors.xml may be used in Kotlin Files (Activities, Fragments, Views and Presenters)."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/color_defs.xml"
  prohibited_content_regex: "name=.+(?<=color).>#|name=.*[A-Z].*>#"
  failure_message: "All color declarations in color_defs.xml should be named using snake_case convention and not contain color keyword."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/component_colors.xml|app/src/main/res/values/color_palette.xml"
  prohibited_content_regex: ".>#\\p{XDigit}+<\\/color>"
  failure_message: "Hex color declarations should only be in color_defs.xml and not in component_colors.xml or color_palette.xml"
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/color_defs.xml"
  prohibited_content_regex: "name=.+>@color\\/.+<"
  failure_message: "color_defs.xml should only have raw hex color declarations."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/component_colors.xml"
  prohibited_content_regex: "name=\"(?!component_color_).+\""
  failure_message: "All colors in component_colors.xml must start with 'component_color_'."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/color_palette.xml"
  prohibited_content_regex: "name=\"(?!color_palette_).+\""
  failure_message: "All colors in color_palette.xml must start with 'color_palette_'."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/color_defs.xml"
  prohibited_content_regex: "name=\"(?!color_def_).+\""
  failure_message: "All colors in color_defs.xml must start with 'color_def_'."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/component_colors.xml"
  prohibited_content_regex: "@color/(?!color_palette_).+"
  failure_message: "Only colors from color_palette.xml may be used in component_colors.xml."
}
file_content_checks {
  file_path_regex: "app/src/main/res/values/color_palette.xml"
  prohibited_content_regex: "@color/(?!color_def_).+"
  failure_message: "Only colors from color_defs.xml may be used in color_palette.xml."
}
file_content_checks {
  file_path_regex: ".+?ActivityTest.kt"
  failure_message: "You've not added a test for verifying the presence of a screen name for this activity. To do this, add a test named testActivity_createIntent_verifyScreenNameInIntent and verify that an appropriate screen name has been added to the activity's intent."
  exempted_file_patterns: "app/src/sharedTest/java/org/oppia/android/app/testing.+?\\.kt"
  exempted_file_patterns: "app/src/test/java/org/oppia/android/app/testing/activity.+?\\.kt"
  required_content_regex: "testActivity_createIntent_verifyScreenNameInIntent\\("
}
file_content_checks {
  file_path_regex: ".+?Activity.kt"
  failure_message: "Please add a Screen Name for this activity. To do this, add a value in the ScreenName enum of screens.proto and add that name to your activity using Intent.decorateWithScreenName(value) on the activity creation intent."
  exempted_file_name:"app/src/main/java/org/oppia/android/app/activity/InjectableAppCompatActivity.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableAutoLocalizedAppCompatActivity.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableSystemLocalizedAppCompatActivity.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/player/state/testing.+?\\.kt"
  exempted_file_patterns: "testing.+?\\.kt"
  required_content_regex: "decorateWithScreenName\\("
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "WorkManager.getInstance"
  failure_message: "Use AnalyticsStartupListener to retrieve an instance of WorkManager rather than fetching one using getInstance (as the latter may create a WorkManager if one isn't already present, and the application may intend to disable it)."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/application/AbstractOppiaApplication.kt"
  exempted_file_patterns: ".+?Test\\.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: ".+?\\.(post|postDelayed)[\\s]*(\\(|\\{).*?"
  failure_message: "Prefer avoiding post() and postDelayed() methods as they can can lead to subtle and difficult-to-debug crashes. Prefer using LifecycleSafeTimerFactory for most cases when an operation needs to run at a future time. For cases when state needs to be synchronized with a view, use doOnPreDraw or doOnLayout instead. For more context on the underlying issue, see: https://betterprogramming.pub/stop-using-post-postdelayed-in-your-android-views-9d1c8eeaadf2."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/topic/info/TopicInfoFragmentPresenter.kt"
  exempted_file_name: "app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt"
}
file_content_checks {
  file_path_regex: "app/src/main/AndroidManifest.xml"
  required_content_regex: "\\s*<meta-data\\s*android:name\\s*=\\s*\"firebase_analytics_collection_deactivated\"\\s*android:value\\s*=\\s*\"true\"\\s*/>\\s*"
  failure_message: "Firebase analytics collection should always be explicitly deactivated in develop."
}
file_content_checks {
  file_path_regex: "app/src/main/AndroidManifest.xml"
  required_content_regex: "\\s*<meta-data\\s*android:name\\s*=\\s*\"firebase_crashlytics_collection_enabled\"\\s*android:value\\s*=\\s*\"false\"\\s*/>\\s*"
  failure_message: "Firebase crashlytics collection should always be explicitly deactivated in develop."
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*[^\\*\\/]+?$"
  failure_message: "Badly formatted KDoc. KDocs should either fit entirely on one line, e.g. \"/** My KDoc. */\" or on multiple lines with the \"/**\" by itself. See other KDocs in the codebase for references."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*[^\\s].+?\\*\\/$"
  failure_message: "Badly formatted KDoc. Single-line KDocs should have one space after the \"/**\" and no other characters."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*\\s{2,}.+?\\*\\/$"
  failure_message: "Badly formatted KDoc. Single-line KDocs should have exactly one space after the \"/**\"."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*.+?[^\\s]\\*\\/$"
  failure_message: "Badly formatted KDoc. Single-line KDocs should always end with a single space before the final \"*/\"."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*.+?\\s{2,}\\*\\/$"
  failure_message: "Badly formatted KDoc. Single-line KDocs should always end with exactly one space before the final \"*/\"."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\*\\*/"
  failure_message: "Badly formatted KDoc or block comment. KDocs and block comments should only end with \"*/\"."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "@(param|property)\\s+\\["
  failure_message: "Badly formatted KDoc param or property at-clause: the name of the parameter or property should immediately follow the at-clause without any additional linking with brackets."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt$"
  prohibited_content_regex: "\\/\\*\\*[^\\*\\/]+?[^\\.\\s]\\s*\\*\\/$"
  failure_message: "Badly formatted KDoc. Single-line KDocs should end with punctuation."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?Test\\.kt"
  prohibited_content_regex: "androidx.test.rule.ActivityTestRule"
  failure_message: "ActivityTestRule is deprecated since it operates test activities in sometimes unsafe situations. Use ActivityScenario, instead."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AppVersionActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/completedstorylist/CompletedStoryListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/customview/LessonThumbnailImageViewTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkStoriesCompletedActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkStoriesCompletedFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/ViewEventLogsActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/faq/FAQSingleActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/faq/FaqListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/help/HelpActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/options/OptionsActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/options/ReadingTextSizeActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/AdminPinActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileRenameActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileRenameFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileResetPinActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileResetPinFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/story/StoryActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/survey/SurveyActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/survey/SurveyFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/thirdparty/LicenseListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/thirdparty/LicenseTextViewerActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/thirdparty/ThirdPartyDependencyListActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/topic/info/TopicInfoFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
}
file_content_checks {
  file_path_regex: ".+?Test\\.kt"
  prohibited_content_regex: "androidx.test.ext.junit.rules.ActivityScenarioRule"
  failure_message: "ActivityScenarioRule can result in order dependence when static state leaks across tests (such as static module variables), and can make staging much more difficult for platform parameters. Use ActivityScenario directly, instead."
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/learneranalytics/ProfileAndDeviceIdActivityTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/AppCompatCheckBoxBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/CircularProgressIndicatorAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/DrawableBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/MarginBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/StateAssemblerMarginBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/StateAssemblerPaddingBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/TextViewBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/databinding/ViewBindingAdaptersTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/devoptions/mathexpressionparser/MathExpressionParserFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/parser/HtmlParserTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt"
  exempted_file_name: "app/src/sharedTest/java/org/oppia/android/app/utility/RatioExtensionsTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/activity/ActivityIntentFactoriesTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/activity/route/ActivityRouterModuleTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/activity/route/ActivityRouterTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/parser/ListItemLeadingMarginSpanTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/parser/StringToRatioParserTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/translation/ActivityLanguageLocaleHandlerTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/translation/AppLanguageResourceHandlerTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/utility/datetime/DateTimeUtilTest.kt"
  exempted_file_name: "app/src/test/java/org/oppia/android/app/utility/math/MathExpressionAccessibilityUtilTest.kt"
  exempted_file_name: "domain/src/test/java/org/oppia/android/domain/oppialogger/analytics/ApplicationLifecycleObserverTest.kt"
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "testing/src/test/java/org/oppia/android/testing/espresso/TextInputActionTest.kt"
}
file_content_checks {
  file_path_regex: ".+?\\.kt"
  prohibited_content_regex: "computeIfAbsent\\("
  failure_message: "computeIfAbsent won't desugar and requires Java 8 support (SDK 24+). Suggest using an atomic Kotlin-specific solution, instead."
  exempted_file_name: "scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt"
  exempted_file_name: "utility/src/main/java/org/oppia/android/util/caching/testing/FakeAssetRepository.kt"
}
