exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationInjectorProvider.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationStartupListenerModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/RouteToProfileListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/notice/AutomaticAppDeprecationNoticeDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsStarter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFooterViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerItem.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/RouteToProfileProgressListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpItems.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/RouteToFAQListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/RouteToFAQSingleListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqItemViewModel/FAQContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqsingle/FAQSingleActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqsingle/FAQSingleActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToExplorationListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToRecentlyPlayedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToTopicListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToTopicPlayStoryListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/ComingSoonTopicsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/PromotedStoryListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/PromotedStoryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/topiclist/TopicSummaryClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/topiclist/TopicSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/DownloadsTabFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsTab.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/UpdatesTabFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboadingSlideViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenterV1.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingSlideFinalViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/RouteToProfileListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/ViewPagerSlide.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsReadingTextSizeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeSelectionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/RouteToAppLanguageListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/TextSizeItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/parser/StringToNumberParser.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/parser/StringToRatioParser.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/DefaultFontSizeStateListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/HintsAndSolutionExplorationManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/HintsAndSolutionExplorationManagerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/ConfettiConfig.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/DragDropSortInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/ImageRegionSelectionInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/SelectionInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContinueInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ImageRegionSelectionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/NumericInputViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/RatioExpressionInputInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/StateItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SubmittedAnswerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/TextInputViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ContinueNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/NextNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/PreviousNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ReplayButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ReturnToTopicNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/RouteToHintsAndSolutionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/StateKeyboardButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/SubmitNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/RestartPlayingSessionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/StopStatePlayingSessionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthEnum.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminPinActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminPinViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/RouteToAdminPinListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RouteToCompletedStoryListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RouteToOngoingTopicListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/DividerItemDecorator.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/IntentFactoryShimModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/ViewBindingShimModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/splash/SplashActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryFragmentScroller.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/storyitemviewmodel/StoryChapterSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/SurveyActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/SurveyOutroDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/SurveyViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/SurveyWelcomeDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/FreeFormItemsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/MarketFitItemsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/MultipleChoiceOptionContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/NpsItemsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/SurveyAnswerItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/UserTypeItemsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/AudioFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/AudioFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestDataModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/DragDropTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ExplorationTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HomeFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HomeTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegionSelectionTestFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegionSelectionTestFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/InputInteractionViewTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileChooserFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/SplashTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/SplashTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TestFontScaleConfigurationUtilActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TopicRevisionTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToConceptCardListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToQuestionPlayerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToRevisionCardListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToStoryListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicTab.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/info/TopicInfoFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/info/TopicInfoViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummarySelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ExpandedChapterListIndexListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/StorySummarySelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/HintsAndSolutionQuestionManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/HintsAndSolutionQuestionManagerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/RevisionSubtopicSelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughFragmentChangeListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughPages.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughEndPageChanger.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/WalkthroughTopicListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/WalkthroughTopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/topiclistviewmodel/WalkthroughTopicSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/welcome/WalkthroughWelcomeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/welcome/WalkthroughWelcomeViewModel.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/recyclerview/RecyclerViewMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/DragViewAction.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/DrawableMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/EspressoTestsMatchers.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/OrientationChangeAction.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/TabMatcher.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/api/FeedbackReportingService.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/audio/AudioPlayerController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/audio/CellularAudioDialogController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/ClassificationResult.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/GenericRuleClassifier.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/InteractionObjectTypeExtractorRepository.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/continueinteraction/ContinueModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgress.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/LogStorageModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorker.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionAssessmentProgress.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionConstantsProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionTrainingConstantsProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/survey/SurveyProgress.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/StoryProgressController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/util/JsonAssetRetriever.kt"
exempted_file_path: "domain/src/test/java/org/oppia/android/domain/classify/InteractionObjectTestBuilder.kt"
exempted_file_path: "instrumentation/src/java/org/oppia/android/instrumentation/application/TestApplicationComponent.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/RichTextViewMatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/ImageViewMatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/platformparameter/TestPlatformParameterModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatcherRobolectricImpl.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatchersEspressoImpl.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatchersRobolectricImpl.kt"
exempted_file_path: "testing/src/test/java/org/oppia/android/testing/threading/TestCoroutineDispatcherTestBase.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/LogLevel.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/html/ConceptCardTagHandler.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/ScalableVectorGraphic.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterValue.kt"
exempted_file_path: "utility/src/test/java/org/oppia/android/util/logging/SyncStatusManagerTestBase.kt"
