screen_name_presence_checks {
  file_path_regex: ".+?ActivityTest.kt"
  accepted_content_regex: "testActivity_createIntent_verifyScreenNameInIntent\\("
  failure_message: "Screen Name test not added."
  exempted_file_patterns: "app/src/sharedTest/java/org/oppia/android/app/testing.+?\\.kt"
  exempted_file_patterns: "app/src/test/java/org/oppia/android/app/testing/activity.+?\\.kt"
}
screen_name_presence_checks {
  file_path_regex: ".+?Activity.kt"
  accepted_content_regex: "^import .+?model.ScreenName.+?$"
  failure_message: "Screen Name not added."
  exempted_file_name: "app/src/main/java/org/oppia/android/app/activity/InjectableAppCompatActivity.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/testing.+?\\.kt"
  exempted_file_patterns: "app/src/main/java/org/oppia/android/app/player/state/testing.+?\\.kt"
  exempted_file_patterns: "testing.+?\\.kt"
}
