exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityComponentFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityIntentFactoriesModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityScope.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/InjectableAppCompatActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/LoadAppVersionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/RouteToAppVersionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/RouteToProfileListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAppInformationViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsGeneralViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsProfileViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ActivityComponentFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationContext.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationInjector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationInjectorProvider.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/ApplicationStartupListenerModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/application/OppiaApplication.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryListFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/SegmentedCircularProgressView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/VerticalDashedLineView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/interaction/FractionInputInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/interaction/NumericInputInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/interaction/RatioInputInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/interaction/TextInputInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/deprecation/AutomaticAppDeprecationNoticeDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/deprecation/AutomaticAppDeprecationNoticeDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/deprecation/DeprecationNoticeExitAppListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsStarter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsStarterImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsStarterModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsModifyLessonProgressViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsOverrideAppBehaviorsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsViewLogsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/ForceCrashButtonClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/testing/ForceNetworkTypeTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/ChapterSelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/ChapterSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/StorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/testing/MarkChaptersCompletedTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/StorySelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/StorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/testing/MarkStoriesCompletedTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/testing/MarkTopicsCompletedTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/TopicSelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/TopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/RouteToForceNetworkTypeListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/RouteToMarkChaptersCompletedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/RouteToMarkStoriesCompletedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/RouteToMarkTopicsCompletedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/RouteToViewEventLogsListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/testing/DeveloperOptionsTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/EventLogItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/testing/ViewEventLogsTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFooterViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerItem.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/drawer/RouteToProfileProgressListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponentBuilderInjector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponentBuilderModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponentFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/FragmentScope.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/InjectableDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/fragment/InjectableFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpItems.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/HelpListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/LoadFaqListFragmentListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/LoadLicenseListFragmentListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/LoadLicenseTextViewerFragmentListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/LoadThirdPartyDependencyListFragmentListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/RouteToFAQListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/RouteToThirdPartyDependencyListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/FAQListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/RouteToFAQSingleListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqItemViewModel/FAQContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqItemViewModel/FAQHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqItemViewModel/FAQItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/faq/faqsingle/FAQSingleActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseTextViewerActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseTextViewerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseTextViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/RouteToLicenseListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/RouteToLicenseTextListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/ThirdPartyDependencyItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/ThirdPartyDependencyListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/ThirdPartyDependencyListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/help/thirdparty/ThirdPartyDependencyListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/ExpandedHintListIndexListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsDividerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/HintsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/RevealHintListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/RevealSolutionDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/RevealSolutionInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/hintsandsolution/SolutionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/HomeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToExplorationListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToRecentlyPlayedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToTopicListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/RouteToTopicPlayStoryListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/UserAppHistoryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/ComingSoonTopicListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/ComingSoonTopicsListView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/ComingSoonTopicsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/promotedlist/PromotedStoryListView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingStoryClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingStoryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/recentlyplayed/SectionTitleViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/topiclist/AllTopicsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/home/topiclist/TopicSummaryClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/DownloadsTabFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/DownloadsTabFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsTab.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/MyDownloadsViewPagerAdapter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/UpdatesTabFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/mydownloads/UpdatesTabFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboadingSlideViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingNavigationListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingSlideFinalViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/OnboardingViewPagerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/RouteToProfileListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/onboarding/ViewPagerSlide.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/AppLanguageActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/AppLanguageFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/AudioLanguageActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/AudioLanguageFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LanguageItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LanguageRadioButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LanguageSelectionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LoadAppLanguageListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LoadAudioLanguageListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/LoadReadingTextSizeListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionControlsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsAppLanguageViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsAudioLanguageViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/OptionsReadingTextSizeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/ReadingTextSizeSelectionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/RouteToAppLanguageListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/RouteToAudioLanguageListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/RouteToReadingTextSizeListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/TextSizeItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/options/TextSizeRadioButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/parser/StringToNumberParser.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioUiManager.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/CellularAudioDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/CellularDataInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/LanguageDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/audio/LanguageInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/DefaultFontSizeStateListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationManagerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/ExplorationViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/HintsAndSolutionExplorationManagerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/HintsAndSolutionExplorationManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/exploration/HintsAndSolutionExplorationManagerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/ConfettiConfig.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/DragDropSortInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/SelectionInteractionView.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerErrorOrAvailabilityCheckReceiver.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContinueInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContinueNavigationButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FeedbackViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ImageRegionSelectionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/InteractionViewModelFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/InteractionViewModelModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/NextButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/NumericInputViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/PreviousButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/PreviousResponsesHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/RatioExpressionInputInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ReplayButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ReturnToTopicButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionContentViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/StateItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SubmitButtonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SubmittedAnswerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/TextInputViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ContinueNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/NextNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/PreviousNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/PreviousResponsesHeaderClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ReplayButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ReturnToTopicNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/RouteToHintsAndSolutionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/ShowHintAvailabilityListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/StateKeyboardButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/listener/SubmitNavigationButtonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/RestartPlayingSessionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/StopExplorationDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/ProgressDatabaseFullDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/UnsavedExplorationDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/StopStatePlayingSessionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/StopStatePlayingSessionWithSavedProgressListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthEnum.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminAuthViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminPinActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminPinViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AdminSettingsViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileRouteDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinDialogFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ResetPinViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/RouteToAdminPinListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureEditDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RouteToCompletedStoryListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/profileprogress/RouteToOngoingTopicListListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/DividerItemDecorator.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/DragAndDropItemFacilitator.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/OnDragEndedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/OnItemDragListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/recyclerview/StartSnapHelper.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditDeletionDialogFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditDialogInterface.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileListViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileRenameActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileRenameFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileRenameViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileResetPinActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileResetPinFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/settings/profile/ProfileResetPinViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/IntentFactoryShim.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/IntentFactoryShimImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/IntentFactoryShimModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/ViewBindingShim.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/ViewBindingShimImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/ViewBindingShimModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/shim/ViewComponentFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/splash/SplashActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/ExplorationSelectionListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryFragmentScroller.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/StoryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/storyitemviewmodel/StoryChapterSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/storyitemviewmodel/StoryHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/story/storyitemviewmodel/StoryItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/AudioFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/AudioFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestDataModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/BindableAdapterTestViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/DragDropTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ExplorationInjectionActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ExplorationTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ExplorationTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HomeFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HomeTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HomeTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/HtmlParserTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegionSelectionTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegionSelectionTestFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegionSelectionTestFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageViewBindingAdaptersTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/LessonThumbnailImageViewTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/LessonThumbnailImageViewTestFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/MarginBindingAdaptersTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileChooserFragmentTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileChooserFragmentTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/SplashTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/SplashTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/StateAssemblerMarginBindingAdaptersTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/StateAssemblerPaddingBindingAdaptersTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TestFontScaleConfigurationUtilActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TopicRevisionTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TopicRevisionTestActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/TopicTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ViewBindingAdaptersTestActivity.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/EnablePracticeTab.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/PracticeTabModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToConceptCardListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToQuestionPlayerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToResumeLessonListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToRevisionCardListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/RouteToStoryListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicTab.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/TopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/ViewPagerAdapter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/info/TopicInfoFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/info/TopicInfoViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummarySelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/ExpandedChapterListIndexListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/StorySummarySelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsTitleViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/SubtopicSelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/practiceitemviewmodel/TopicPracticeFooterViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/practiceitemviewmodel/TopicPracticeHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/practiceitemviewmodel/TopicPracticeItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/practice/practiceitemviewmodel/TopicPracticeSubtopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/HintsAndSolutionQuestionManagerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/HintsAndSolutionQuestionManagerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/HintsAndSolutionQuestionManagerListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerFragment.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/RevisionSubtopicSelector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revision/revisionitemviewmodel/TopicRevisionItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/ReturnToTopicClickListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/ActivityRecreator.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/ActivityRecreatorImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/ActivityRecreatorProdModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/AppLanguageActivityInjector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/AppLanguageActivityInjectorProvider.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/AppLanguageApplicationInjector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/AppLanguageApplicationInjectorProvider.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/translation/testing/ActivityRecreatorTestModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/FontScaleConfigurationUtil.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/KeyboardHelper.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/LifecycleSafeTimerFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/OnClickableAreaClickedListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/RegionClickEvent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/SplitScreenManager.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/utility/TextInputEditTextHelper.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponent.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponentBuilderInjector.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponentBuilderModule.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponentFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewComponentImpl.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/view/ViewScope.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/viewmodel/ObservableArrayList.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/viewmodel/ObservableViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/viewmodel/ViewModelBridgeFactory.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/viewmodel/ViewModelProvider.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivityListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivityPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughFragmentChangeListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughPageChanger.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughPages.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughEndPageChanger.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalListener.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/WalkthroughTopicItemViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/WalkthroughTopicListFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/WalkthroughTopicViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/topiclistviewmodel/WalkthroughTopicHeaderViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/topiclist/topiclistviewmodel/WalkthroughTopicSummaryViewModel.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/welcome/WalkthroughWelcomeFragmentPresenter.kt"
exempted_file_path: "app/src/main/java/org/oppia/android/app/walkthrough/welcome/WalkthroughWelcomeViewModel.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/recyclerview/RecyclerViewMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/ClickActions.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/DragViewAction.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/DrawableMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/EspressoTestsMatchers.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/FontSizeMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/OrientationChangeAction.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/ProgressMatcher.kt"
exempted_file_path: "app/src/sharedTest/java/org/oppia/android/app/utility/TabMatcher.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/BaseUrl.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/Constants.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/NetworkApiKey.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/OppiaRetrofit.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/XssiPrefix.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeAnswerGroup.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeClassroom.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeConceptCard.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeCustomizationArgs.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeExpSummary.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeExploration.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeExplorationContainer.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReport.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingAppContext.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingDeviceContext.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingEntryPoint.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingSystemContext.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeHint.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeInteractionInstance.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeOutcome.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeParamChange.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeParamSpec.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeQuestion.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeQuestionPlayer.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeRecordedVoiceovers.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeRuleSpec.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSkillContents.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSolution.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeState.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeStateClassifier.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeStory.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeStoryNode.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeStorySummary.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSubtitledHtml.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSubtopic.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSubtopicPageContents.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeSubtopicSummary.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeTopic.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeTopicSummary.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeUserSuppliedFeedback.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeVoiceover.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeWrittenTranslation.kt"
exempted_file_path: "data/src/main/java/org/oppia/android/data/backends/gae/model/GaeWrittenTranslations.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/ClassificationResult.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/GenericInteractionClassifier.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/InteractionClassifier.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/InteractionsModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/RuleClassifier.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/GenericRuleClassifier.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/InteractionObjectTypeExtractorRepository.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/RuleClassifierProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/RuleQualifiers.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/continueinteraction/ContinueModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXAtPositionYClassifierProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXBeforeElementYClassifierProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/imageClickInput/ImageClickInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/itemselectioninput/ItemSelectionInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/multiplechoiceinput/MultipleChoiceInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsRuleModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/numericinput/NumericInputRuleModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/ratioinput/RatioInputModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/classify/rules/textinput/TextInputRuleModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgress.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/exploration/ExplorationRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointState.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/feedbackreporting/FeedbackReportingModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/DelayShowAdditionalHintsFromWrongAnswerMillis.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/DelayShowAdditionalHintsMillis.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/DelayShowInitialHintMillis.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/HintsAndSolutionConfigFastShowTestModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/HintsAndSolutionConfigModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/hintsandsolution/HintHandler.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/locale/LocaleApplicationInjector.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/locale/LocaleApplicationInjectorProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/onboarding/ExpirationMetaDataRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/onboarding/ExpirationMetaDataRetrieverImpl.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/onboarding/ExpirationMetaDataRetrieverModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/onboarding/testing/ExpirationMetaDataRetrieverTestModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/onboarding/testing/FakeExpirationMetaDataRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/ApplicationStartupListener.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/LogStorageModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorkerModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterSingletonImpl.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterSingletonModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorkerFactory.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorkerModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionAssessmentCalculation.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionAssessmentProgress.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionConstantsProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionSessionMetrics.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/question/QuestionTrainingConstantsProvider.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/state/StateDeck.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/state/StateGraph.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/state/StateList.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/testing/oppialogger/loguploader/FakeLogUploader.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/ConceptCardRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/PrimeTopicAssetsController.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/PrimeTopicAssetsControllerImpl.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/PrimeTopicAssetsControllerModule.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/topic/RevisionCardRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/util/JsonAssetRetriever.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/util/JsonExtensions.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/util/WorkDataExtensions.kt"
exempted_file_path: "domain/src/main/java/org/oppia/android/domain/workmanager/WorkManagerConfigurationModule.kt"
exempted_file_path: "domain/src/test/java/org/oppia/android/domain/classify/InteractionObjectTestBuilder.kt"
exempted_file_path: "instrumentation/src/java/org/oppia/android/instrumentation/application/OppiaTestApplication.kt"
exempted_file_path: "instrumentation/src/java/org/oppia/android/instrumentation/application/TestApplicationComponent.kt"
exempted_file_path: "instrumentation/src/java/org/oppia/android/instrumentation/testing/EndToEndTestHelper.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/common/CommandExecutor.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/common/CommandResult.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/license/LicenseFetcher.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/license/LicenseFetcherImpl.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/license/model/CopyrightLicense.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/license/model/Dependency.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/maven/model/MavenListDependency.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/maven/model/MavenListDependencies.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/maven/model/MavenListDependencyTree.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/model/Issue.kt"
exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/model/Todo.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/AccessibilityTestRule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/AssertionHelpers.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/DisableAccessibilityChecks.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/OppiaTestAnnotations.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/OppiaTestRule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/OppiaTestRunner.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/RichTextViewMatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/TestImageLoaderModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/TestLogReportingModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/TextInputActionTestActivity.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/environment/TestEnvironmentConfig.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/GenericViewMatchers.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/ImageViewMatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/KonfettiViewMatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/junit/DefineAppLanguageLocaleContext.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/ComparableOperationListSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/FractionSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/MathExpressionSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/MathEquationSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/PolynomialSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/RealSubject.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/mockito/MockitoKotlinHelper.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/ApiMockLoader.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockClassroomService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockConceptCardService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockExplorationService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockFeedbackReportingService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockQuestionPlayerService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockStoryService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockSubtopicService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/MockTopicService.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/network/RetrofitTestModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/platformparameter/TestBooleanPlatformParameter.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/platformparameter/TestIntegerPlatformParameter.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/platformparameter/TestPlatformParameterModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/platformparameter/TestStringPlatformParameter.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/robolectric/IsOnRobolectric.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/robolectric/RobolectricModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/BackgroundTestDispatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/BlockingTestDispatcher.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatchers.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatchersEspressoImpl.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestCoroutineDispatchersRobolectricImpl.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/threading/TestDispatcherModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/time/FakeOppiaClockModule.kt"
exempted_file_path: "testing/src/main/java/org/oppia/android/testing/time/FakeSystemClock.kt"
exempted_file_path: "testing/src/test/java/org/oppia/android/testing/threading/TestCoroutineDispatcherTestBase.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityService.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityServiceImpl.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityProdModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/accessibility/AccessibilityTestModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/AssetRepository.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/AssetRepositoryImpl.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/CacheAssetsLocally.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/CachingModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/LoadImagesFromAssets.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/LoadLessonProtosFromAssets.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/TopicListToCache.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/caching/testing/CachingTestModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/data/AsyncDataSubscriptionManager.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/data/DataProvider.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/data/DataProvidersInjector.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/data/DataProvidersInjectorProvider.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/extensions/ContextExtensions.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/gcsresource/GcsResourceAnnotations.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/gcsresource/GcsResourceModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/locale/OppiaBidiFormatter.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/locale/OppiaLocale.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/EventLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/ExceptionLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/LogLevel.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/LogUploader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/LoggerModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/LoggingAnnotations.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/DebugEventLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/DebugLogReportingModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/FirebaseEventLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/FirebaseExceptionLogger.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/FirebaseLogUploader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/FirebaseLogUploaderModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/logging/firebase/LogReportingModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/math/FloatExtensions.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/math/FractionExtensions.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/networking/ConnectionStatus.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/networking/NetworkConnectionDebugUtil.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/networking/NetworkConnectionDebugUtilModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/networking/NetworkConnectionUtil.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/html/BulletTagHandler.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/html/ExplorationHtmlParserEntityType.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/html/HtmlParserEntityTypeModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/BitmapBlurTransformation.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/BitmapBlurrer.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/GlideImageLoader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/GlideImageLoaderModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageAssetFetcher.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageLoader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageParsingAnnotations.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageParsingModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageTargets.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/ImageTransformation.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/RepositoryGlideModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/RepositoryModelLoader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/TestGlideImageLoader.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/image/TextPictureDrawable.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/BlockPictureDrawable.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/BlockSvgDrawableTranscoder.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/ScalableVectorGraphic.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/SvgBlurTransformation.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/SvgDecoder.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/parser/svg/TextSvgDrawableTranscoder.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterValue.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/statusbar/StatusBarColor.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/system/OppiaClock.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/system/OppiaClockImpl.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/system/OppiaClockInjector.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/system/OppiaClockInjectorProvider.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/system/OppiaClockModule.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/threading/BackgroundDispatcher.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/threading/BlockingDispatcher.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/threading/ConcurrentCollections.kt"
exempted_file_path: "utility/src/main/java/org/oppia/android/util/threading/DispatcherModule.kt"
