todo_open_exemption {
  exempted_file_path: ".github/CODEOWNERS"
  line_number: 9
}
todo_open_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoOpenCheckTest.kt"
  line_number: 64
  line_number: 65
  line_number: 71
  line_number: 73
  line_number: 95
  line_number: 96
  line_number: 97
  line_number: 98
  line_number: 99
  line_number: 116
  line_number: 132
  line_number: 133
  line_number: 136
  line_number: 168
  line_number: 169
  line_number: 170
  line_number: 175
  line_number: 177
  line_number: 193
  line_number: 216
  line_number: 217
  line_number: 218
  line_number: 223
  line_number: 225
  line_number: 231
  line_number: 248
  line_number: 270
  line_number: 274
  line_number: 312
  line_number: 313
  line_number: 317
  line_number: 366
  line_number: 367
  line_number: 368
  line_number: 372
  line_number: 402

}
todo_open_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoCollectorTest.kt"
  line_number: 39
  line_number: 48
  line_number: 55
  line_number: 58
  line_number: 67
  line_number: 68
  line_number: 72
  line_number: 76
  line_number: 77
  line_number: 89
  line_number: 92
  line_number: 96
  line_number: 99
  line_number: 103
  line_number: 106
  line_number: 110
  line_number: 113
  line_number: 117
  line_number: 120
  line_number: 129
  line_number: 130
  line_number: 131
  line_number: 132
  line_number: 137
  line_number: 142
  line_number: 145
  line_number: 158
  line_number: 161
  line_number: 165
  line_number: 168
  line_number: 172
  line_number: 175
  line_number: 179
  line_number: 182
  line_number: 186
  line_number: 189
  line_number: 193
  line_number: 196
  line_number: 200
  line_number: 203
  line_number: 212
  line_number: 213
  line_number: 214
  line_number: 215
  line_number: 219
  line_number: 223
  line_number: 226
  line_number: 239
  line_number: 242
  line_number: 246
  line_number: 249
  line_number: 253
  line_number: 256
  line_number: 260
  line_number: 263
  line_number: 267
  line_number: 270
  line_number: 274
  line_number: 277
  line_number: 281
  line_number: 284
  line_number: 325
  line_number: 326
  line_number: 327
  line_number: 332
  line_number: 337
  line_number: 340
  line_number: 353
  line_number: 356
  line_number: 360
  line_number: 363
  line_number: 367
  line_number: 370
  line_number: 374
  line_number: 377
  line_number: 381
  line_number: 384
  line_number: 392
}
todo_open_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/TodoCollector.kt"
  line_number: 82
}
todo_open_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/TodoOpenCheck.kt"
  line_number: 97
}
todo_open_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/model/Todo.kt"
  line_number: 10
}
