todo_open_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoOpenCheckTest.kt"
  line_number: 67
  line_number: 68
  line_number: 74
  line_number: 76
  line_number: 98
  line_number: 99
  line_number: 100
  line_number: 101
  line_number: 102
  line_number: 136
  line_number: 137
  line_number: 140
  line_number: 173
  line_number: 174
  line_number: 175
  line_number: 180
  line_number: 182
  line_number: 221
  line_number: 222
  line_number: 223
  line_number: 228
  line_number: 230
  line_number: 236
  line_number: 275
  line_number: 279
  line_number: 317
  line_number: 318
  line_number: 322
  line_number: 371
  line_number: 372
  line_number: 373
  line_number: 377
}
todo_open_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoCollectorTest.kt"
  line_number: 33
  line_number: 34
  line_number: 35
  line_number: 36
  line_number: 37
  line_number: 38
  line_number: 39
  line_number: 40
  line_number: 41
  line_number: 42
  line_number: 43
  line_number: 44
  line_number: 45
  line_number: 46
  line_number: 47
  line_number: 48
  line_number: 49
  line_number: 50
  line_number: 51
  line_number: 52
  line_number: 53
  line_number: 54
  line_number: 55
  line_number: 56
  line_number: 57
  line_number: 63
  line_number: 64
  line_number: 73
  line_number: 76
  line_number: 80
  line_number: 83
  line_number: 87
  line_number: 90
  line_number: 94
  line_number: 97
  line_number: 101
  line_number: 104
  line_number: 108
  line_number: 111
  line_number: 115
  line_number: 118
  line_number: 122
  line_number: 125
  line_number: 129
  line_number: 132
  line_number: 136
  line_number: 139
  line_number: 143
  line_number: 146
  line_number: 150
  line_number: 153
  line_number: 157
  line_number: 160
  line_number: 164
  line_number: 167
  line_number: 171
  line_number: 174
  line_number: 178
  line_number: 181
  line_number: 185
  line_number: 188
  line_number: 192
  line_number: 195
  line_number: 199
  line_number: 202
  line_number: 206
  line_number: 209
  line_number: 213
  line_number: 216
  line_number: 220
  line_number: 223
  line_number: 227
  line_number: 230
  line_number: 234
  line_number: 237
  line_number: 241
  line_number: 244
  line_number: 248
  line_number: 255
  line_number: 258
  line_number: 262
  line_number: 265
  line_number: 274
  line_number: 275
  line_number: 279
  line_number: 283
  line_number: 284
  line_number: 296
  line_number: 299
  line_number: 303
  line_number: 306
  line_number: 310
  line_number: 313
  line_number: 317
  line_number: 320
  line_number: 324
  line_number: 327
  line_number: 336
  line_number: 337
  line_number: 338
  line_number: 339
  line_number: 344
  line_number: 349
  line_number: 352
  line_number: 365
  line_number: 368
  line_number: 372
  line_number: 375
  line_number: 379
  line_number: 382
  line_number: 386
  line_number: 389
  line_number: 393
  line_number: 396
  line_number: 400
  line_number: 403
  line_number: 407
  line_number: 410
  line_number: 419
  line_number: 420
  line_number: 421
  line_number: 422
  line_number: 426
  line_number: 430
  line_number: 433
  line_number: 446
  line_number: 449
  line_number: 453
  line_number: 456
  line_number: 460
  line_number: 463
  line_number: 467
  line_number: 470
  line_number: 474
  line_number: 477
  line_number: 481
  line_number: 484
  line_number: 488
  line_number: 491
  line_number: 532
  line_number: 533
  line_number: 534
  line_number: 539
  line_number: 544
  line_number: 547
  line_number: 548
  line_number: 549
  line_number: 550
  line_number: 551
  line_number: 552
  line_number: 553
  line_number: 554
  line_number: 555
  line_number: 556
  line_number: 557
  line_number: 558
  line_number: 559
  line_number: 560
  line_number: 561
  line_number: 562
  line_number: 563
  line_number: 564
  line_number: 565
  line_number: 566
  line_number: 567
  line_number: 568
  line_number: 569
  line_number: 575
  line_number: 588
  line_number: 591
  line_number: 595
  line_number: 598
  line_number: 602
  line_number: 605
  line_number: 609
  line_number: 612
  line_number: 616
  line_number: 619
  line_number: 627
  line_number: 636
  line_number: 645
  line_number: 654
  line_number: 663
  line_number: 672
  line_number: 681
  line_number: 690
  line_number: 699
  line_number: 708
  line_number: 717
  line_number: 726
  line_number: 735
  line_number: 744
  line_number: 753
  line_number: 762
  line_number: 771
  line_number: 780
  line_number: 789
  line_number: 798
  line_number: 807
  line_number: 816
  line_number: 826
  line_number: 827
  line_number: 828
  line_number: 836
  line_number: 839
  line_number: 843
  line_number: 846
  line_number: 850
  line_number: 853
  line_number: 862
  line_number: 863
  line_number: 864
  line_number: 873
  line_number: 876
  line_number: 880
  line_number: 883
  line_number: 887
  line_number: 890
  line_number: 899
  line_number: 900
  line_number: 901
}
todo_open_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoIssueResolvedCheckTest.kt"
  line_number: 71
  line_number: 73
  line_number: 79
  line_number: 95
  line_number: 97
  line_number: 103
  line_number: 131
  line_number: 133
  line_number: 139
  line_number: 143
  line_number: 145
  line_number: 146
  line_number: 177
  line_number: 179
  line_number: 185
  line_number: 189
  line_number: 191
  line_number: 192
}
todo_open_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/TodoCollector.kt"
  line_number: 82
}
todo_open_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/model/Todo.kt"
  line_number: 10
}

todo_open_exemption {
  exempted_file_path: "wiki/Coding-style-guide.md"
  line_number: 43
}

todo_open_exemption {
  exempted_file_path: "wiki/Static-Analysis-Checks.md"
  line_number: 170
  line_number: 178
  line_number: 183
  line_number: 187
  line_number: 191
  line_number: 193
  line_number: 208
  line_number: 218
  line_number: 221
  line_number: 224
  line_number: 227
  line_number: 230
}
