todo_exemption {
  exempted_file_path: ".github/CODEOWNERS"
  line_number: 9
}
todo_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoCheckTest.kt"
  line_number: 64
  line_number: 65
  line_number: 71
  line_number: 73
  line_number: 95
  line_number: 96
  line_number: 97
  line_number: 98
  line_number: 114
  line_number: 130
  line_number: 131
  line_number: 134
  line_number: 166
  line_number: 167
  line_number: 168
  line_number: 173
  line_number: 175
  line_number: 191
  line_number: 214
  line_number: 215
  line_number: 216
  line_number: 221
  line_number: 223
  line_number: 229
  line_number: 246
  line_number: 268
  line_number: 272
  line_number: 310
  line_number: 311
  line_number: 315
  line_number: 364
  line_number: 365
  line_number: 366
  line_number: 370
  line_number: 400
}
todo_exemption {
  exempted_file_path: "scripts/src/javatests/org/oppia/android/scripts/todo/TodoCollectorTest.kt"
  line_number: 39
  line_number: 58
  line_number: 67
  line_number: 68
  line_number: 69
  line_number: 74
  line_number: 79
  line_number: 82
  line_number: 97
  line_number: 104
  line_number: 111
  line_number: 118
  line_number: 125
  line_number: 132
  line_number: 141
  line_number: 142
  line_number: 146
  line_number: 150
  line_number: 151
  line_number: 166
  line_number: 173
  line_number: 180
  line_number: 187
  line_number: 194
}
todo_exemption {
  exempted_file_path: "scripts/src/java/org/oppia/android/scripts/todo/TodoCheck.kt"
  line_number: 104
}
