"""
Tests for survey logging functionality.
"""

load("//:oppia_android_test.bzl", "oppia_android_test")

oppia_android_test(
    name = "SurveyEventsLoggerTest",
    srcs = ["SurveyEventsLoggerTest.kt"],
    custom_package = "org.oppia.android.domain.oppialogger.survey",
    test_class = "org.oppia.android.domain.oppialogger.survey.SurveyEventsLoggerTest",
    test_manifest = "//domain:test_manifest",
    deps = [
        "//:dagger",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/analytics:prod_module",
        "//domain/src/main/java/org/oppia/android/domain/oppialogger/survey:survey_events_logger",
        "//testing",
        "//testing/src/main/java/org/oppia/android/testing/data:data_provider_test_monitor",
        "//testing/src/main/java/org/oppia/android/testing/logging:event_log_subject",
        "//testing/src/main/java/org/oppia/android/testing/logging:sync_status_test_module",
        "//testing/src/main/java/org/oppia/android/testing/platformparameter:test_module",
        "//testing/src/main/java/org/oppia/android/testing/robolectric:test_module",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_coroutine_dispatchers",
        "//testing/src/main/java/org/oppia/android/testing/threading:test_module",
        "//testing/src/main/java/org/oppia/android/testing/time:test_module",
        "//third_party:androidx_test_ext_junit",
        "//third_party:com_google_truth_truth",
        "//third_party:junit_junit",
        "//third_party:org_robolectric_robolectric",
        "//third_party:robolectric_android-all",
        "//utility/src/main/java/org/oppia/android/util/caching:asset_prod_module",
        "//utility/src/main/java/org/oppia/android/util/locale/testing:test_module",
        "//utility/src/main/java/org/oppia/android/util/logging/performancemetrics/testing:performance_metrics_assessor_test_module",
        "//utility/src/main/java/org/oppia/android/util/networking:debug_module",
    ],
)
