tracked_topic_info {
  id: "iX9kYCjnouWN"
  content_version: 60
  story_info {
    id: "RRVMHsZ5Mobh"
    content_version: 17
    chapter_info {
      exploration_id: "K645IfRNzpKy"
      exploration_content_version: 972
    }
    chapter_info {
      exploration_id: "Knvx24p24qPO"
      exploration_content_version: 868
    }
    chapter_info {
      exploration_id: "aAkDKVDR53cG"
      exploration_content_version: 1031
    }
    chapter_info {
      exploration_id: "avwshGklKLJE"
      exploration_content_version: 1111
    }
    chapter_info {
      exploration_id: "WwqLmeQEn9NK"
      exploration_content_version: 494
    }
  }
  subtopic_info {
    index: 1
    content_version: 2
  }
  subtopic_info {
    index: 2
    content_version: 4
  }
  subtopic_info {
    index: 3
    content_version: 2
  }
  subtopic_info {
    index: 4
    content_version: 2
  }
}
tracked_topic_info {
  id: "sWBXKH4PZcK6"
  content_version: 53
  story_info {
    id: "Qu6THxP29tOy"
    content_version: 19
    chapter_info {
      exploration_id: "OKxYhsWONHZV"
      exploration_content_version: 1564
    }
    chapter_info {
      exploration_id: "BJd7yHIxpqkq"
      exploration_content_version: 1110
    }
    chapter_info {
      exploration_id: "W0xq3jW5GzDF"
      exploration_content_version: 876
    }
    chapter_info {
      exploration_id: "53Ka3mQ6ra5A"
      exploration_content_version: 1268
    }
    chapter_info {
      exploration_id: "VKXd8qHsxLml"
      exploration_content_version: 870
    }
    chapter_info {
      exploration_id: "PsfDKdhd6Esz"
      exploration_content_version: 866
    }
    chapter_info {
      exploration_id: "9DITEN8BUEHw"
      exploration_content_version: 1143
    }
  }
  subtopic_info {
    index: 1
    content_version: 4
  }
  subtopic_info {
    index: 2
    content_version: 2
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
  subtopic_info {
    index: 5
    content_version: 2
  }
  subtopic_info {
    index: 3
    content_version: 2
  }
}
tracked_topic_info {
  id: "C4fqwrvqWpRm"
  content_version: 76
  story_info {
    id: "vfJDB3JAdwIx"
    content_version: 19
    chapter_info {
      exploration_id: "R7WpsSfmDQPV"
      exploration_content_version: 1668
    }
    chapter_info {
      exploration_id: "zIBYaqfDJrJC"
      exploration_content_version: 1458
    }
    chapter_info {
      exploration_id: "1904tpP0CYwY"
      exploration_content_version: 1503
    }
    chapter_info {
      exploration_id: "cQDibOXQbpi7"
      exploration_content_version: 1062
    }
    chapter_info {
      exploration_id: "MRJeVrKafW6G"
      exploration_content_version: 947
    }
    chapter_info {
      exploration_id: "hNOP3TwRJhsz"
      exploration_content_version: 1002
    }
    chapter_info {
      exploration_id: "zTg2hzTz37jP"
      exploration_content_version: 596
    }
  }
  subtopic_info {
    index: 1
    content_version: 3
  }
  subtopic_info {
    index: 2
    content_version: 2
  }
  subtopic_info {
    index: 3
    content_version: 2
  }
  subtopic_info {
    index: 4
    content_version: 2
  }
}
tracked_topic_info {
  id: "qW12maD4hiA8"
  content_version: 44
  story_info {
    id: "rqnxwceQyFnv"
    content_version: 20
    chapter_info {
      exploration_id: "8HTzQQUPiK5i"
      exploration_content_version: 564
    }
    chapter_info {
      exploration_id: "40a3vjmZ7Fwu"
      exploration_content_version: 887
    }
    chapter_info {
      exploration_id: "WulCxGAmGE61"
      exploration_content_version: 820
    }
    chapter_info {
      exploration_id: "lOU0XPC2BnE9"
      exploration_content_version: 859
    }
    chapter_info {
      exploration_id: "wE9pyaC5np3n"
      exploration_content_version: 624
    }
  }
  subtopic_info {
    index: 1
    content_version: 2
  }
  subtopic_info {
    index: 2
    content_version: 2
  }
  subtopic_info {
    index: 3
    content_version: 3
  }
}
tracked_topic_info {
  id: "0abdeaJhmfPm"
  content_version: 95
  story_info {
    id: "3M5VBajMccXO"
    content_version: 34
    chapter_info {
      exploration_id: "umPkwp0L1M0-"
      exploration_content_version: 838
    }
    chapter_info {
      exploration_id: "MjZzEVOG47_1"
      exploration_content_version: 819
    }
    chapter_info {
      exploration_id: "9trAQhj6uUC2"
      exploration_content_version: 811
    }
    chapter_info {
      exploration_id: "rfX8jNkPnA-1"
      exploration_content_version: 345
    }
    chapter_info {
      exploration_id: "0FBWxCE5egOw"
      exploration_content_version: 1179
    }
    chapter_info {
      exploration_id: "670bU6d9JGBh"
      exploration_content_version: 1079
    }
    chapter_info {
      exploration_id: "aHikhPlxYgOH"
      exploration_content_version: 1210
    }
    chapter_info {
      exploration_id: "-tMgcP1i_4au"
      exploration_content_version: 572
    }
    chapter_info {
      exploration_id: "zW39GLG_BdN2"
      exploration_content_version: 742
    }
    chapter_info {
      exploration_id: "Xa3B_io-2WI5"
      exploration_content_version: 857
    }
    chapter_info {
      exploration_id: "6Q6IyIDkjpYC"
      exploration_content_version: 1157
    }
    chapter_info {
      exploration_id: "osw1m5Q3jK41"
      exploration_content_version: 352
    }
    chapter_info {
      exploration_id: "seQ3nLNiIs7N"
      exploration_content_version: 33
    }
    chapter_info {
      exploration_id: "9Y8ElcYGvvDO"
      exploration_content_version: 34
    }
    chapter_info {
      exploration_id: "p95j2UZqlD2Q"
      exploration_content_version: 25
    }
    chapter_info {
      exploration_id: "GhSatoiom5Ab"
      exploration_content_version: 20
    }
    chapter_info {
      exploration_id: "uOgakaq1atad"
      exploration_content_version: 24
    }
  }
  subtopic_info {
    index: 1
    content_version: 2
  }
  subtopic_info {
    index: 2
    content_version: 2
  }
  subtopic_info {
    index: 3
    content_version: 2
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
  subtopic_info {
    index: 5
    content_version: 1
  }
  subtopic_info {
    index: 6
    content_version: 1
  }
  subtopic_info {
    index: 7
    content_version: 2
  }
  subtopic_info {
    index: 8
    content_version: 2
  }
  subtopic_info {
    index: 9
    content_version: 2
  }
  subtopic_info {
    index: 10
    content_version: 2
  }
}
tracked_topic_info {
  id: "dLmjjMDbCcrf"
  content_version: 72
  story_info {
    id: "JhiDkq01dqgC"
    content_version: 44
    chapter_info {
      exploration_id: "rDJojPOc0KgJ"
      exploration_content_version: 171
    }
    chapter_info {
      exploration_id: "kYSrbNDCv5sH"
      exploration_content_version: 387
    }
    chapter_info {
      exploration_id: "K89Hgj2qRSzw"
      exploration_content_version: 240
    }
    chapter_info {
      exploration_id: "lNpxiuqufPiw"
      exploration_content_version: 199
    }
    chapter_info {
      exploration_id: "Jbgc3MlRiY07"
      exploration_content_version: 325
    }
    chapter_info {
      exploration_id: "rwN3YPG9XWZa"
      exploration_content_version: 139
    }
    chapter_info {
      exploration_id: "nTMZwH7i0DdW"
      exploration_content_version: 361
    }
    chapter_info {
      exploration_id: "IrbGLTicm0BI"
      exploration_content_version: 127
    }
    chapter_info {
      exploration_id: "v8fonNnX4Ub1"
      exploration_content_version: 108
    }
    chapter_info {
      exploration_id: "ibeLZqbbjbKF"
      exploration_content_version: 206
    }
    chapter_info {
      exploration_id: "BDIln52yGfeH"
      exploration_content_version: 80
    }
    chapter_info {
      exploration_id: "SR1IKIdLxnm1"
      exploration_content_version: 28
    }
    chapter_info {
      exploration_id: "m1nvGABWeUoh"
      exploration_content_version: 100
    }
    chapter_info {
      exploration_id: "zNb0Bh27QtJ4"
      exploration_content_version: 202
    }
    chapter_info {
      exploration_id: "5I4srORrwjt2"
      exploration_content_version: 54
    }
    chapter_info {
      exploration_id: "aqJ07xrTFNLF"
      exploration_content_version: 167
    }
    chapter_info {
      exploration_id: "0X0KC9DXWwra"
      exploration_content_version: 109
    }
  }
  subtopic_info {
    index: 1
    content_version: 1
  }
  subtopic_info {
    index: 2
    content_version: 1
  }
  subtopic_info {
    index: 3
    content_version: 1
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
  subtopic_info {
    index: 5
    content_version: 1
  }
  subtopic_info {
    index: 6
    content_version: 1
  }
}
tracked_topic_info {
  id: "VjCpR1DB2MVN"
  content_version: 82
  story_info {
    id: "Aadv1RN3npAP"
    content_version: 24
    chapter_info {
      exploration_id: "l0S8zoUrVQNd"
      exploration_content_version: 101
    }
    chapter_info {
      exploration_id: "YnhDmpzewUYI"
      exploration_content_version: 91
    }
    chapter_info {
      exploration_id: "bWHHbghtVQKU"
      exploration_content_version: 52
    }
    chapter_info {
      exploration_id: "C8QUgzIETvRv"
      exploration_content_version: 84
    }
    chapter_info {
      exploration_id: "jgGYHzds2WeL"
      exploration_content_version: 71
    }
    chapter_info {
      exploration_id: "WuyjwUCVJuIn"
      exploration_content_version: 69
    }
    chapter_info {
      exploration_id: "bf9RrsgNWZmI"
      exploration_content_version: 65
    }
    chapter_info {
      exploration_id: "Gh6AzOEDLcz2"
      exploration_content_version: 73
    }
    chapter_info {
      exploration_id: "FMH1Ii1ztP4j"
      exploration_content_version: 56
    }
    chapter_info {
      exploration_id: "xtbP46LKl1uj"
      exploration_content_version: 50
    }
  }
  subtopic_info {
    index: 7
    content_version: 1
  }
  subtopic_info {
    index: 1
    content_version: 1
  }
  subtopic_info {
    index: 2
    content_version: 1
  }
  subtopic_info {
    index: 3
    content_version: 1
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
  subtopic_info {
    index: 5
    content_version: 1
  }
  subtopic_info {
    index: 6
    content_version: 1
  }
}
tracked_topic_info {
  id: "5g0nxGUmx5J5"
  content_version: 36
  story_info {
    id: "ialKSV0VYV0B"
    content_version: 10
    chapter_info {
      exploration_id: "2mzzFVDLuAj8"
      exploration_content_version: 988
    }
    chapter_info {
      exploration_id: "5NWuolNcwH6e"
      exploration_content_version: 761
    }
    chapter_info {
      exploration_id: "k2bQ7z5XHNbK"
      exploration_content_version: 1205
    }
    chapter_info {
      exploration_id: "tIoSb3HZFN6e"
      exploration_content_version: 838
    }
    chapter_info {
      exploration_id: "nLmUS6lbmvnl"
      exploration_content_version: 927
    }
    chapter_info {
      exploration_id: "Vgde5_ZVqrq5"
      exploration_content_version: 544
    }
    chapter_info {
      exploration_id: "RvopsvVdIb0J"
      exploration_content_version: 641
    }
    chapter_info {
      exploration_id: "zVbqxwck0KaC"
      exploration_content_version: 539
    }
  }
  subtopic_info {
    index: 1
    content_version: 1
  }
  subtopic_info {
    index: 2
    content_version: 2
  }
  subtopic_info {
    index: 3
    content_version: 1
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
}
tracked_topic_info {
  id: "F4vMtwKMS6jR"
  content_version: 51
  story_info {
    id: "gvf2KlV8A8ie"
    content_version: 19
    chapter_info {
      exploration_id: "W50hotX4h_Up"
      exploration_content_version: 405
    }
    chapter_info {
      exploration_id: "BlhHWkwlpOPL"
      exploration_content_version: 163
    }
    chapter_info {
      exploration_id: "Ui9Gnop0WhAW"
      exploration_content_version: 175
    }
    chapter_info {
      exploration_id: "iW85v9kiZyH2"
      exploration_content_version: 148
    }
    chapter_info {
      exploration_id: "ksezbx9FUWFh"
      exploration_content_version: 162
    }
    chapter_info {
      exploration_id: "5uvM7exYOqAI"
      exploration_content_version: 198
    }
  }
  subtopic_info {
    index: 1
    content_version: 1
  }
  subtopic_info {
    index: 2
    content_version: 1
  }
  subtopic_info {
    index: 3
    content_version: 1
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
}
tracked_topic_info {
  id: "5cbCOcglPdrn"
  content_version: 3
}
tracked_topic_info {
  id: "bdO7c687WBBW"
  content_version: 35
  story_info {
    id: "OVJ4RdjxbcAf"
    content_version: 15
    chapter_info {
      exploration_id: "MXlPhsCBPGVc"
      exploration_content_version: 68
    }
    chapter_info {
      exploration_id: "g2Nl0LCoGsBI"
      exploration_content_version: 39
    }
    chapter_info {
      exploration_id: "7NmXKQQ9tRmg"
      exploration_content_version: 37
    }
    chapter_info {
      exploration_id: "mJkyVkrrVUTx"
      exploration_content_version: 40
    }
    chapter_info {
      exploration_id: "DYl70Ox4P3TI"
      exploration_content_version: 26
    }
    chapter_info {
      exploration_id: "7a5WD0pE4UoC"
      exploration_content_version: 29
    }
    chapter_info {
      exploration_id: "sNbyN5XtLxPk"
      exploration_content_version: 24
    }
    chapter_info {
      exploration_id: "fMkbtaKCXtpx"
      exploration_content_version: 25
    }
  }
  subtopic_info {
    index: 1
    content_version: 2
  }
  subtopic_info {
    index: 4
    content_version: 1
  }
  subtopic_info {
    index: 2
    content_version: 1
  }
  subtopic_info {
    index: 3
    content_version: 1
  }
}
tracked_skill_info {
  id: "5UeFU80Yoaf7"
  content_version: 8
}
tracked_skill_info {
  id: "63HdyngqkSSV"
  content_version: 7
}
tracked_skill_info {
  id: "EK521D5vFNoI"
  content_version: 8
}
tracked_skill_info {
  id: "O0aZp94Aj8yG"
  content_version: 7
}
tracked_skill_info {
  id: "TFqov4gKVN1n"
  content_version: 7
}
tracked_skill_info {
  id: "asQSA9rXpdwu"
  content_version: 10
}
tracked_skill_info {
  id: "kNnNHaxmb0Db"
  content_version: 7
}
tracked_skill_info {
  id: "iSm2utLbGYmL"
  content_version: 7
}
tracked_skill_info {
  id: "DAMrlUjg9Gy9"
  content_version: 7
}
tracked_skill_info {
  id: "c2JtMYxrWfE8"
  content_version: 7
}
tracked_skill_info {
  id: "f12I5buviMdT"
  content_version: 8
}
tracked_skill_info {
  id: "nB6LbjFbgY6c"
  content_version: 9
}
tracked_skill_info {
  id: "1nl7FpQuOI1p"
  content_version: 11
}
tracked_skill_info {
  id: "w660Kcq1JQs7"
  content_version: 5
}
tracked_skill_info {
  id: "Ors0VEMksGe2"
  content_version: 10
}
tracked_skill_info {
  id: "NKzdLeaMwIEK"
  content_version: 6
}
tracked_skill_info {
  id: "5imG7w41L7cE"
  content_version: 14
}
tracked_skill_info {
  id: "s8G0W2e4iQkp"
  content_version: 9
}
tracked_skill_info {
  id: "KJaebRBJiPZh"
  content_version: 8
}
tracked_skill_info {
  id: "zDd03ZanXtH0"
  content_version: 11
}
tracked_skill_info {
  id: "eH2AaPobw8Un"
  content_version: 15
}
tracked_skill_info {
  id: "lN06xKDgfbUi"
  content_version: 8
}
tracked_skill_info {
  id: "9oZSgyxbbcmK"
  content_version: 10
}
tracked_skill_info {
  id: "jBDbW6ldbJ1a"
  content_version: 6
}
tracked_skill_info {
  id: "hJ7chGJahN6i"
  content_version: 11
}
tracked_skill_info {
  id: "ZQaeFNY0C56p"
  content_version: 13
}
tracked_skill_info {
  id: "QFI2y3aaqz0e"
  content_version: 10
}
tracked_skill_info {
  id: "pdmI5RdxkgeL"
  content_version: 9
}
tracked_skill_info {
  id: "vVmmTAiWEjzo"
  content_version: 7
}
tracked_skill_info {
  id: "dUuQT23NDYDN"
  content_version: 8
}
tracked_skill_info {
  id: "r2RKQnUe9ZLW"
  content_version: 7
}
tracked_skill_info {
  id: "a3QtIqWYO6WL"
  content_version: 8
}
tracked_skill_info {
  id: "aWHXi0W4i6ky"
  content_version: 8
}
tracked_skill_info {
  id: "okiapFJ3LBxu"
  content_version: 9
}
tracked_skill_info {
  id: "mHFrQ1KPZ8qN"
  content_version: 13
}
tracked_skill_info {
  id: "G0NsFwEahIZx"
  content_version: 13
}
tracked_skill_info {
  id: "OQUsLvCg6dAX"
  content_version: 8
}
tracked_skill_info {
  id: "9Mg793eaW88W"
  content_version: 10
}
tracked_skill_info {
  id: "OhnLR4G1eTEY"
  content_version: 8
}
tracked_skill_info {
  id: "zZv9Y0UBEzh8"
  content_version: 8
}
tracked_skill_info {
  id: "ZQo719isHrqc"
  content_version: 10
}
tracked_skill_info {
  id: "rMGp1aPEZb2F"
  content_version: 6
}
tracked_skill_info {
  id: "rdbaWCJPBWJl"
  content_version: 6
}
tracked_skill_info {
  id: "poHX7h4xsRmt"
  content_version: 6
}
tracked_skill_info {
  id: "ktOgitsvcI6a"
  content_version: 5
}
tracked_skill_info {
  id: "VUGdL5yab3tP"
  content_version: 7
}
tracked_skill_info {
  id: "royTfKs17ICM"
  content_version: 6
}
tracked_skill_info {
  id: "DD57VfWeaIx7"
  content_version: 6
}
tracked_skill_info {
  id: "Y9hbBPvAsvtN"
  content_version: 5
}
tracked_skill_info {
  id: "JzHVBJrLSHjW"
  content_version: 5
}
tracked_skill_info {
  id: "qS36ycdvut30"
  content_version: 5
}
tracked_skill_info {
  id: "akPxy431BuWI"
  content_version: 6
}
tracked_skill_info {
  id: "yrBiTOaLnSc8"
  content_version: 7
}
tracked_skill_info {
  id: "ww1YgH2a30p4"
  content_version: 9
}
tracked_skill_info {
  id: "YkkxwGw84Piz"
  content_version: 7
}
tracked_skill_info {
  id: "rBOtCQIzDYc9"
  content_version: 10
}
tracked_skill_info {
  id: "MPSxpawZuLFQ"
  content_version: 9
}
tracked_skill_info {
  id: "NKaHCvaKuIdu"
  content_version: 7
}
tracked_skill_info {
  id: "rOKiiDPHUQRs"
  content_version: 6
}
tracked_skill_info {
  id: "mxzlyhxrfvAu"
  content_version: 9
}
tracked_skill_info {
  id: "PgqWOs15cG6U"
  content_version: 9
}
tracked_skill_info {
  id: "FkU7His1znyO"
  content_version: 6
}
tracked_skill_info {
  id: "WWd2nNcclkYY"
  content_version: 10
}
tracked_skill_info {
  id: "PyX8O9zur0Uv"
  content_version: 7
}
tracked_skill_info {
  id: "zNz0ybnRRz2Y"
  content_version: 6
}
tracked_skill_info {
  id: "ujDYfYzaD8Nl"
  content_version: 7
}
tracked_skill_info {
  id: "rs6bRxj838Qa"
  content_version: 6
}
tracked_skill_info {
  id: "qqSpO8Stxp8x"
  content_version: 5
}
tracked_skill_info {
  id: "cgpKRSbROl9Z"
  content_version: 5
}
tracked_skill_info {
  id: "XeaJe19RYSZa"
  content_version: 8
}
tracked_skill_info {
  id: "R56CCKEGtJnv"
  content_version: 7
}
tracked_skill_info {
  id: "cVo8W3BrIhGK"
  content_version: 6
}
tracked_skill_info {
  id: "hwIizGYf8F5Z"
  content_version: 6
}
tracked_skill_info {
  id: "RaU3COcgqlfc"
  content_version: 5
}
tracked_skill_info {
  id: "XSeqJaQsrtjI"
  content_version: 5
}
tracked_skill_info {
  id: "oUCal0u4k9GA"
  content_version: 9
}
tracked_skill_info {
  id: "HOYGD5CEK89b"
  content_version: 5
}
tracked_skill_info {
  id: "jwSDa7Hdvjaj"
  content_version: 7
}
tracked_skill_info {
  id: "KhLIXiD7WeDj"
  content_version: 6
}
tracked_skill_info {
  id: "iiHgWcHtlbOr"
  content_version: 8
}
tracked_skill_info {
  id: "QB2gTQvp3hVZ"
  content_version: 5
}
tracked_skill_info {
  id: "VdApTH9VMvbH"
  content_version: 7
}
tracked_skill_info {
  id: "ntudbdPS66jm"
  content_version: 5
}
tracked_skill_info {
  id: "7GwBldRR3h5Y"
  content_version: 4
}
tracked_skill_info {
  id: "GeXO4b1g4qu4"
  content_version: 5
}
tracked_skill_info {
  id: "bbjGZPSsfEbX"
  content_version: 7
}
tracked_skill_info {
  id: "8v0n5DOmqpl6"
  content_version: 6
}
tracked_skill_info {
  id: "pq255eAazpC6"
  content_version: 5
}
tracked_skill_info {
  id: "59dtKuaWyNoY"
  content_version: 6
}
tracked_skill_info {
  id: "N6OZv3sjusK3"
  content_version: 6
}
tracked_skill_info {
  id: "vshbf5HHMMmT"
  content_version: 7
}
tracked_skill_info {
  id: "D8WL3dSrV8fI"
  content_version: 6
}
tracked_skill_info {
  id: "QgiUwulwiKQa"
  content_version: 5
}
tracked_skill_info {
  id: "p5RPzexH3do6"
  content_version: 5
}
tracked_skill_info {
  id: "bhnEJXziVvDL"
  content_version: 6
}
tracked_skill_info {
  id: "8RmNWlsBzZ2I"
  content_version: 7
}
tracked_skill_info {
  id: "Vta7z7exkbUP"
  content_version: 4
}
tracked_skill_info {
  id: "m2ybOPnaektb"
  content_version: 7
}
tracked_skill_info {
  id: "IWtp8fA4OT3P"
  content_version: 7
}
tracked_skill_info {
  id: "1MdfXcaWfLfG"
  content_version: 7
}
tracked_skill_info {
  id: "qyCzxqHM33fB"
  content_version: 5
}
tracked_skill_info {
  id: "aW4mlKQgCexJ"
  content_version: 6
}
tracked_skill_info {
  id: "3PbEX6LbJk6k"
  content_version: 5
}
tracked_skill_info {
  id: "pvwUNoYNAzFk"
  content_version: 5
}
tracked_skill_info {
  id: "uBtrXrhyglsW"
  content_version: 2
}
tracked_skill_info {
  id: "ixlztwRNBhn9"
  content_version: 10
}
tracked_skill_info {
  id: "oVUCajN6gcL2"
  content_version: 7
}
tracked_skill_info {
  id: "Y7cdklO4bKDa"
  content_version: 5
}
tracked_skill_info {
  id: "5NqhCAOjQ4Lo"
  content_version: 7
}
tracked_skill_info {
  id: "4ZWhkTj7gZba"
  content_version: 5
}
tracked_skill_info {
  id: "YEyUgjqfBv0n"
  content_version: 6
}
tracked_skill_info {
  id: "1aqcSr4KDxUa"
  content_version: 5
}
tracked_skill_info {
  id: "lIIsfDjDbQos"
  content_version: 5
}
tracked_skill_info {
  id: "z1oOhkibrnle"
  content_version: 5
}
tracked_skill_info {
  id: "kLewNeuVHK7W"
  content_version: 5
}
tracked_skill_info {
  id: "zIIrvs9ESTe6"
  content_version: 5
}
tracked_skill_info {
  id: "XacedNXqTcw4"
  content_version: 5
}
tracked_skill_info {
  id: "bqsC3tU48PSf"
  content_version: 5
}
tracked_skill_info {
  id: "VNRIGIbFu80W"
  content_version: 5
}
tracked_skill_info {
  id: "7dESeE9linHR"
  content_version: 5
}
tracked_skill_info {
  id: "ZNWuiFW3eYVg"
  content_version: 6
}
tracked_skill_info {
  id: "mMgIr0iyfta3"
  content_version: 7
}
tracked_skill_info {
  id: "N5avmNoEykbI"
  content_version: 6
}
tracked_skill_info {
  id: "MZ7Bk5JA6LEo"
  content_version: 5
}
tracked_skill_info {
  id: "ZTr3Ks22btXj"
  content_version: 7
}
tracked_skill_info {
  id: "KZFcg0a1WX3O"
  content_version: 6
}
tracked_skill_info {
  id: "JiWzGyKvlM2c"
  content_version: 9
}
tracked_skill_info {
  id: "yeNRiU5uPSHe"
  content_version: 4
}
tracked_skill_info {
  id: "X2KEGbxaZMJ0"
  content_version: 4
}
tracked_skill_info {
  id: "ZJP9bUUCwrjI"
  content_version: 6
}
tracked_skill_info {
  id: "oalHY7nLjL97"
  content_version: 8
}
tracked_skill_info {
  id: "Z7OhS0ayu07O"
  content_version: 8
}
tracked_skill_info {
  id: "BqFuTG0JOB9b"
  content_version: 14
}
tracked_skill_info {
  id: "QE9FNLOUF94r"
  content_version: 10
}
tracked_skill_info {
  id: "AXQofdF87iAJ"
  content_version: 10
}
tracked_skill_info {
  id: "ab0gm4mktxIT"
  content_version: 9
}
tracked_skill_info {
  id: "3wLajnYAaZ1L"
  content_version: 7
}
tracked_skill_info {
  id: "RIOH1Rbjqb91"
  content_version: 8
}
tracked_skill_info {
  id: "8r7mO8E895b1"
  content_version: 9
}
tracked_skill_info {
  id: "VjtMZUrbLf65"
  content_version: 8
}
tracked_skill_info {
  id: "fnqyE7S35gaE"
  content_version: 6
}
tracked_skill_info {
  id: "4smbctNSk2cr"
  content_version: 10
}
tracked_skill_info {
  id: "yCgpn8OjXMET"
  content_version: 8
}
tracked_skill_info {
  id: "6AhMkHcfZFdS"
  content_version: 7
}
tracked_skill_info {
  id: "wTww8o4yMqvL"
  content_version: 5
}
tracked_skill_info {
  id: "wvUvYfbd91Dh"
  content_version: 6
}
tracked_skill_info {
  id: "6aG8fos2y2tI"
  content_version: 8
}
tracked_skill_info {
  id: "bD3sajDo188l"
  content_version: 6
}
tracked_skill_info {
  id: "p3dQCHu4OkCr"
  content_version: 6
}
tracked_skill_info {
  id: "h5KljN9FIP7a"
  content_version: 14
}
tracked_skill_info {
  id: "djvXp6LHV46i"
  content_version: 4
}
tracked_skill_info {
  id: "IyqARavFFRpn"
  content_version: 4
}
tracked_skill_info {
  id: "z1TXVMwpal4e"
  content_version: 3
}
tracked_skill_info {
  id: "33p8RF3m5iN8"
  content_version: 3
}
tracked_skill_info {
  id: "PiVFnQarGPBQ"
  content_version: 3
}
tracked_skill_info {
  id: "4aWUr1OtkvqC"
  content_version: 3
}
tracked_skill_info {
  id: "4q6ja2MbehbE"
  content_version: 3
}
tracked_skill_info {
  id: "pVcGIXLFImIv"
  content_version: 5
}
tracked_skill_info {
  id: "f7W5jOG4PbHV"
  content_version: 6
}
tracked_skill_info {
  id: "2UVkM6W394tH"
  content_version: 6
}
tracked_skill_info {
  id: "PSYhh6BXHKnv"
  content_version: 5
}
tracked_skill_info {
  id: "D15tRkci9o5c"
  content_version: 6
}
tracked_skill_info {
  id: "jAMbDCZxnHb4"
  content_version: 4
}
tracked_skill_info {
  id: "F2i3mndaaiAt"
  content_version: 3
}
tracked_skill_info {
  id: "vGTxPqw3taby"
  content_version: 3
}
tracked_skill_info {
  id: "a81k6CLJoOT6"
  content_version: 3
}
tracked_skill_info {
  id: "JvyqptQge8Se"
  content_version: 5
}
tracked_skill_info {
  id: "PUlyLJWsIY1o"
  content_version: 5
}
tracked_skill_info {
  id: "AbwyG1aRW82g"
  content_version: 4
}
tracked_skill_info {
  id: "nUZrZ5rFzoh6"
  content_version: 2
}
tracked_skill_info {
  id: "sL9nqLaYnXDb"
  content_version: 4
}
tracked_skill_info {
  id: "AjzrZRxb9CU6"
  content_version: 6
}
tracked_skill_info {
  id: "uL8zXBwCd9D0"
  content_version: 6
}
tracked_skill_info {
  id: "g5xFIbJ3cs3e"
  content_version: 3
}
tracked_skill_info {
  id: "acOEn1mJxpbQ"
  content_version: 3
}
tracked_skill_info {
  id: "e644wN7vDUkn"
  content_version: 3
}
tracked_skill_info {
  id: "uNSFlseW3o7F"
  content_version: 4
}
tracked_skill_info {
  id: "ExZMpRr1jMxJ"
  content_version: 4
}
tracked_skill_info {
  id: "S1IAgTEqO4YG"
  content_version: 6
}
tracked_skill_info {
  id: "bBIpo3XCLO13"
  content_version: 3
}
tracked_skill_info {
  id: "SALxtMf9dh6H"
  content_version: 3
}
tracked_skill_info {
  id: "bkmpgbM4WzWo"
  content_version: 4
}
tracked_skill_info {
  id: "pDN147cftGnk"
  content_version: 4
}
tracked_skill_info {
  id: "DZdlhhambykY"
  content_version: 2
}
tracked_skill_info {
  id: "Kg9odbViYNhU"
  content_version: 4
}
tracked_skill_info {
  id: "KQ7ZH7le6U9m"
  content_version: 4
}
tracked_skill_info {
  id: "GxtUGQW5z0Nw"
  content_version: 1
}
tracked_skill_info {
  id: "agoXOXv3byfl"
  content_version: 2
}
tracked_skill_info {
  id: "WNjBh9TVx1cv"
  content_version: 3
}
tracked_skill_info {
  id: "AVwVIH2dZUur"
  content_version: 5
}
tracked_skill_info {
  id: "9VD60yhg3Bw6"
  content_version: 4
}
tracked_skill_info {
  id: "aa3aKg2eyfU5"
  content_version: 3
}
tracked_skill_info {
  id: "gIGajqYFUM2b"
  content_version: 2
}
tracked_skill_info {
  id: "gBgUXa3SVeP0"
  content_version: 2
}
tracked_skill_info {
  id: "5a5rmYyFyOlr"
  content_version: 2
}
tracked_skill_info {
  id: "Xb5IgrBJQTpo"
  content_version: 2
}
tracked_skill_info {
  id: "ENBmD8AKXrVS"
  content_version: 2
}
tracked_skill_info {
  id: "sTcQjsMuKt1D"
  content_version: 2
}
tracked_skill_info {
  id: "zMT19AUbRx7f"
  content_version: 2
}
tracked_skill_info {
  id: "QT67iLIRoHgq"
  content_version: 2
}
