tracked_topic_info {
  id: "iX9kYCjnouWN"
  content_version: 59
  story_info {
    id: "RRVMHsZ5Mobh"
    content_version: 17
    chapter_info {
      exploration_id: "K645IfRNzpKy"
      exploration_content_version: 968
    }
    chapter_info {
      exploration_id: "Knvx24p24qPO"
      exploration_content_version: 868
    }
    chapter_info {
      exploration_id: "aAkDKVDR53cG"
      exploration_content_version: 1026
    }
    chapter_info {
      exploration_id: "avwshGklKLJE"
      exploration_content_version: 1111
    }
    chapter_info {
      exploration_id: "WwqLmeQEn9NK"
      exploration_content_version: 494
    }
  }
  subtopic_info {
    index: 1
    content_version: 7
  }
  subtopic_info {
    index: 2
    content_version: 9
  }
  subtopic_info {
    index: 3
    content_version: 6
  }
  subtopic_info {
    index: 4
    content_version: 9
  }
}
tracked_topic_info {
  id: "sWBXKH4PZcK6"
  content_version: 53
  story_info {
    id: "Qu6THxP29tOy"
    content_version: 19
    chapter_info {
      exploration_id: "OKxYhsWONHZV"
      exploration_content_version: 1564
    }
    chapter_info {
      exploration_id: "BJd7yHIxpqkq"
      exploration_content_version: 1110
    }
    chapter_info {
      exploration_id: "W0xq3jW5GzDF"
      exploration_content_version: 875
    }
    chapter_info {
      exploration_id: "53Ka3mQ6ra5A"
      exploration_content_version: 1268
    }
    chapter_info {
      exploration_id: "VKXd8qHsxLml"
      exploration_content_version: 870
    }
    chapter_info {
      exploration_id: "PsfDKdhd6Esz"
      exploration_content_version: 866
    }
    chapter_info {
      exploration_id: "9DITEN8BUEHw"
      exploration_content_version: 1143
    }
  }
  subtopic_info {
    index: 1
    content_version: 10
  }
  subtopic_info {
    index: 2
    content_version: 8
  }
  subtopic_info {
    index: 4
    content_version: 5
  }
  subtopic_info {
    index: 5
    content_version: 5
  }
  subtopic_info {
    index: 3
    content_version: 7
  }
}
tracked_topic_info {
  id: "C4fqwrvqWpRm"
  content_version: 76
  story_info {
    id: "vfJDB3JAdwIx"
    content_version: 19
    chapter_info {
      exploration_id: "R7WpsSfmDQPV"
      exploration_content_version: 1667
    }
    chapter_info {
      exploration_id: "zIBYaqfDJrJC"
      exploration_content_version: 1458
    }
    chapter_info {
      exploration_id: "1904tpP0CYwY"
      exploration_content_version: 1503
    }
    chapter_info {
      exploration_id: "cQDibOXQbpi7"
      exploration_content_version: 1062
    }
    chapter_info {
      exploration_id: "MRJeVrKafW6G"
      exploration_content_version: 947
    }
    chapter_info {
      exploration_id: "hNOP3TwRJhsz"
      exploration_content_version: 1000
    }
    chapter_info {
      exploration_id: "zTg2hzTz37jP"
      exploration_content_version: 596
    }
  }
  subtopic_info {
    index: 1
    content_version: 10
  }
  subtopic_info {
    index: 2
    content_version: 10
  }
  subtopic_info {
    index: 3
    content_version: 13
  }
  subtopic_info {
    index: 4
    content_version: 12
  }
}
tracked_topic_info {
  id: "qW12maD4hiA8"
  content_version: 44
  story_info {
    id: "rqnxwceQyFnv"
    content_version: 20
    chapter_info {
      exploration_id: "8HTzQQUPiK5i"
      exploration_content_version: 557
    }
    chapter_info {
      exploration_id: "40a3vjmZ7Fwu"
      exploration_content_version: 873
    }
    chapter_info {
      exploration_id: "WulCxGAmGE61"
      exploration_content_version: 809
    }
    chapter_info {
      exploration_id: "lOU0XPC2BnE9"
      exploration_content_version: 855
    }
    chapter_info {
      exploration_id: "wE9pyaC5np3n"
      exploration_content_version: 622
    }
  }
  subtopic_info {
    index: 1
    content_version: 5
  }
  subtopic_info {
    index: 2
    content_version: 6
  }
  subtopic_info {
    index: 3
    content_version: 8
  }
}
tracked_topic_info {
  id: "0abdeaJhmfPm"
  content_version: 92
  story_info {
    id: "3M5VBajMccXO"
    content_version: 31
    chapter_info {
      exploration_id: "umPkwp0L1M0-"
      exploration_content_version: 838
    }
    chapter_info {
      exploration_id: "MjZzEVOG47_1"
      exploration_content_version: 819
    }
    chapter_info {
      exploration_id: "9trAQhj6uUC2"
      exploration_content_version: 811
    }
    chapter_info {
      exploration_id: "rfX8jNkPnA-1"
      exploration_content_version: 345
    }
    chapter_info {
      exploration_id: "0FBWxCE5egOw"
      exploration_content_version: 1179
    }
    chapter_info {
      exploration_id: "670bU6d9JGBh"
      exploration_content_version: 1079
    }
    chapter_info {
      exploration_id: "aHikhPlxYgOH"
      exploration_content_version: 1210
    }
    chapter_info {
      exploration_id: "-tMgcP1i_4au"
      exploration_content_version: 572
    }
    chapter_info {
      exploration_id: "zW39GLG_BdN2"
      exploration_content_version: 742
    }
    chapter_info {
      exploration_id: "Xa3B_io-2WI5"
      exploration_content_version: 857
    }
    chapter_info {
      exploration_id: "6Q6IyIDkjpYC"
      exploration_content_version: 1157
    }
    chapter_info {
      exploration_id: "osw1m5Q3jK41"
      exploration_content_version: 352
    }
    chapter_info {
      exploration_id: "seQ3nLNiIs7N"
      exploration_content_version: 33
    }
    chapter_info {
      exploration_id: "9Y8ElcYGvvDO"
      exploration_content_version: 34
    }
    chapter_info {
      exploration_id: "p95j2UZqlD2Q"
      exploration_content_version: 25
    }
    chapter_info {
      exploration_id: "GhSatoiom5Ab"
      exploration_content_version: 20
    }
    chapter_info {
      exploration_id: "uOgakaq1atad"
      exploration_content_version: 24
    }
  }
  subtopic_info {
    index: 1
    content_version: 4
  }
  subtopic_info {
    index: 2
    content_version: 8
  }
  subtopic_info {
    index: 3
    content_version: 6
  }
  subtopic_info {
    index: 4
    content_version: 4
  }
  subtopic_info {
    index: 5
    content_version: 4
  }
  subtopic_info {
    index: 6
    content_version: 4
  }
  subtopic_info {
    index: 7
    content_version: 5
  }
  subtopic_info {
    index: 8
    content_version: 5
  }
  subtopic_info {
    index: 9
    content_version: 5
  }
  subtopic_info {
    index: 10
    content_version: 5
  }
}
tracked_topic_info {
  id: "5g0nxGUmx5J5"
  content_version: 36
  story_info {
    id: "ialKSV0VYV0B"
    content_version: 10
    chapter_info {
      exploration_id: "2mzzFVDLuAj8"
      exploration_content_version: 988
    }
    chapter_info {
      exploration_id: "5NWuolNcwH6e"
      exploration_content_version: 761
    }
    chapter_info {
      exploration_id: "k2bQ7z5XHNbK"
      exploration_content_version: 1205
    }
    chapter_info {
      exploration_id: "tIoSb3HZFN6e"
      exploration_content_version: 838
    }
    chapter_info {
      exploration_id: "nLmUS6lbmvnl"
      exploration_content_version: 927
    }
    chapter_info {
      exploration_id: "Vgde5_ZVqrq5"
      exploration_content_version: 544
    }
    chapter_info {
      exploration_id: "RvopsvVdIb0J"
      exploration_content_version: 641
    }
    chapter_info {
      exploration_id: "zVbqxwck0KaC"
      exploration_content_version: 539
    }
  }
  subtopic_info {
    index: 1
    content_version: 4
  }
  subtopic_info {
    index: 2
    content_version: 5
  }
  subtopic_info {
    index: 3
    content_version: 4
  }
  subtopic_info {
    index: 4
    content_version: 8
  }
}
tracked_skill_info {
  id: "5UeFU80Yoaf7"
  content_version: 8
}
tracked_skill_info {
  id: "63HdyngqkSSV"
  content_version: 7
}
tracked_skill_info {
  id: "EK521D5vFNoI"
  content_version: 8
}
tracked_skill_info {
  id: "O0aZp94Aj8yG"
  content_version: 7
}
tracked_skill_info {
  id: "TFqov4gKVN1n"
  content_version: 7
}
tracked_skill_info {
  id: "asQSA9rXpdwu"
  content_version: 10
}
tracked_skill_info {
  id: "kNnNHaxmb0Db"
  content_version: 7
}
tracked_skill_info {
  id: "iSm2utLbGYmL"
  content_version: 7
}
tracked_skill_info {
  id: "DAMrlUjg9Gy9"
  content_version: 7
}
tracked_skill_info {
  id: "c2JtMYxrWfE8"
  content_version: 7
}
tracked_skill_info {
  id: "f12I5buviMdT"
  content_version: 8
}
tracked_skill_info {
  id: "nB6LbjFbgY6c"
  content_version: 9
}
tracked_skill_info {
  id: "1nl7FpQuOI1p"
  content_version: 11
}
tracked_skill_info {
  id: "w660Kcq1JQs7"
  content_version: 5
}
tracked_skill_info {
  id: "Ors0VEMksGe2"
  content_version: 10
}
tracked_skill_info {
  id: "NKzdLeaMwIEK"
  content_version: 6
}
tracked_skill_info {
  id: "5imG7w41L7cE"
  content_version: 13
}
tracked_skill_info {
  id: "s8G0W2e4iQkp"
  content_version: 9
}
tracked_skill_info {
  id: "KJaebRBJiPZh"
  content_version: 8
}
tracked_skill_info {
  id: "zDd03ZanXtH0"
  content_version: 11
}
tracked_skill_info {
  id: "eH2AaPobw8Un"
  content_version: 15
}
tracked_skill_info {
  id: "lN06xKDgfbUi"
  content_version: 8
}
tracked_skill_info {
  id: "9oZSgyxbbcmK"
  content_version: 10
}
tracked_skill_info {
  id: "jBDbW6ldbJ1a"
  content_version: 6
}
tracked_skill_info {
  id: "hJ7chGJahN6i"
  content_version: 11
}
tracked_skill_info {
  id: "ZQaeFNY0C56p"
  content_version: 13
}
tracked_skill_info {
  id: "QFI2y3aaqz0e"
  content_version: 10
}
tracked_skill_info {
  id: "pdmI5RdxkgeL"
  content_version: 9
}
tracked_skill_info {
  id: "vVmmTAiWEjzo"
  content_version: 7
}
tracked_skill_info {
  id: "dUuQT23NDYDN"
  content_version: 8
}
tracked_skill_info {
  id: "r2RKQnUe9ZLW"
  content_version: 7
}
tracked_skill_info {
  id: "a3QtIqWYO6WL"
  content_version: 8
}
tracked_skill_info {
  id: "aWHXi0W4i6ky"
  content_version: 8
}
tracked_skill_info {
  id: "okiapFJ3LBxu"
  content_version: 9
}
tracked_skill_info {
  id: "mHFrQ1KPZ8qN"
  content_version: 13
}
tracked_skill_info {
  id: "G0NsFwEahIZx"
  content_version: 13
}
tracked_skill_info {
  id: "OQUsLvCg6dAX"
  content_version: 8
}
tracked_skill_info {
  id: "9Mg793eaW88W"
  content_version: 10
}
tracked_skill_info {
  id: "OhnLR4G1eTEY"
  content_version: 8
}
tracked_skill_info {
  id: "zZv9Y0UBEzh8"
  content_version: 8
}
tracked_skill_info {
  id: "ZQo719isHrqc"
  content_version: 10
}
tracked_skill_info {
  id: "rMGp1aPEZb2F"
  content_version: 6
}
tracked_skill_info {
  id: "rdbaWCJPBWJl"
  content_version: 6
}
tracked_skill_info {
  id: "poHX7h4xsRmt"
  content_version: 6
}
tracked_skill_info {
  id: "ktOgitsvcI6a"
  content_version: 5
}
tracked_skill_info {
  id: "VUGdL5yab3tP"
  content_version: 7
}
tracked_skill_info {
  id: "royTfKs17ICM"
  content_version: 6
}
tracked_skill_info {
  id: "DD57VfWeaIx7"
  content_version: 6
}
tracked_skill_info {
  id: "Y9hbBPvAsvtN"
  content_version: 5
}
tracked_skill_info {
  id: "JzHVBJrLSHjW"
  content_version: 5
}
tracked_skill_info {
  id: "qS36ycdvut30"
  content_version: 5
}
tracked_skill_info {
  id: "akPxy431BuWI"
  content_version: 6
}
tracked_skill_info {
  id: "yrBiTOaLnSc8"
  content_version: 7
}
tracked_skill_info {
  id: "ww1YgH2a30p4"
  content_version: 9
}
tracked_skill_info {
  id: "YkkxwGw84Piz"
  content_version: 7
}
tracked_skill_info {
  id: "rBOtCQIzDYc9"
  content_version: 10
}
tracked_skill_info {
  id: "MPSxpawZuLFQ"
  content_version: 9
}
tracked_skill_info {
  id: "NKaHCvaKuIdu"
  content_version: 7
}
tracked_skill_info {
  id: "rOKiiDPHUQRs"
  content_version: 6
}
tracked_skill_info {
  id: "mxzlyhxrfvAu"
  content_version: 9
}
tracked_skill_info {
  id: "PgqWOs15cG6U"
  content_version: 9
}
tracked_skill_info {
  id: "FkU7His1znyO"
  content_version: 6
}
tracked_skill_info {
  id: "WWd2nNcclkYY"
  content_version: 10
}
tracked_skill_info {
  id: "PyX8O9zur0Uv"
  content_version: 7
}
tracked_skill_info {
  id: "zNz0ybnRRz2Y"
  content_version: 6
}
tracked_skill_info {
  id: "ujDYfYzaD8Nl"
  content_version: 7
}
tracked_skill_info {
  id: "rs6bRxj838Qa"
  content_version: 6
}
tracked_skill_info {
  id: "qqSpO8Stxp8x"
  content_version: 5
}
tracked_skill_info {
  id: "cgpKRSbROl9Z"
  content_version: 5
}
tracked_skill_info {
  id: "XeaJe19RYSZa"
  content_version: 8
}
tracked_skill_info {
  id: "R56CCKEGtJnv"
  content_version: 7
}
tracked_skill_info {
  id: "cVo8W3BrIhGK"
  content_version: 6
}
tracked_skill_info {
  id: "hwIizGYf8F5Z"
  content_version: 6
}
tracked_skill_info {
  id: "RaU3COcgqlfc"
  content_version: 5
}
tracked_skill_info {
  id: "XSeqJaQsrtjI"
  content_version: 5
}
tracked_skill_info {
  id: "oUCal0u4k9GA"
  content_version: 9
}
tracked_skill_info {
  id: "HOYGD5CEK89b"
  content_version: 5
}
tracked_skill_info {
  id: "jwSDa7Hdvjaj"
  content_version: 7
}
tracked_skill_info {
  id: "KhLIXiD7WeDj"
  content_version: 6
}
tracked_skill_info {
  id: "iiHgWcHtlbOr"
  content_version: 8
}
tracked_skill_info {
  id: "QB2gTQvp3hVZ"
  content_version: 5
}
tracked_skill_info {
  id: "VdApTH9VMvbH"
  content_version: 7
}
tracked_skill_info {
  id: "ntudbdPS66jm"
  content_version: 5
}
tracked_skill_info {
  id: "7GwBldRR3h5Y"
  content_version: 4
}
tracked_skill_info {
  id: "GeXO4b1g4qu4"
  content_version: 5
}
tracked_skill_info {
  id: "bbjGZPSsfEbX"
  content_version: 7
}
tracked_skill_info {
  id: "8v0n5DOmqpl6"
  content_version: 6
}
tracked_skill_info {
  id: "pq255eAazpC6"
  content_version: 5
}
tracked_skill_info {
  id: "59dtKuaWyNoY"
  content_version: 6
}
tracked_skill_info {
  id: "N6OZv3sjusK3"
  content_version: 6
}
tracked_skill_info {
  id: "vshbf5HHMMmT"
  content_version: 7
}
tracked_skill_info {
  id: "D8WL3dSrV8fI"
  content_version: 6
}
tracked_skill_info {
  id: "QgiUwulwiKQa"
  content_version: 5
}
tracked_skill_info {
  id: "p5RPzexH3do6"
  content_version: 5
}
tracked_skill_info {
  id: "bhnEJXziVvDL"
  content_version: 6
}
tracked_skill_info {
  id: "8RmNWlsBzZ2I"
  content_version: 7
}
tracked_skill_info {
  id: "Vta7z7exkbUP"
  content_version: 4
}
tracked_skill_info {
  id: "m2ybOPnaektb"
  content_version: 7
}
tracked_skill_info {
  id: "IWtp8fA4OT3P"
  content_version: 7
}
tracked_skill_info {
  id: "1MdfXcaWfLfG"
  content_version: 7
}
tracked_skill_info {
  id: "qyCzxqHM33fB"
  content_version: 5
}
tracked_skill_info {
  id: "aW4mlKQgCexJ"
  content_version: 6
}
tracked_skill_info {
  id: "3PbEX6LbJk6k"
  content_version: 5
}
tracked_skill_info {
  id: "pvwUNoYNAzFk"
  content_version: 5
}
tracked_skill_info {
  id: "uBtrXrhyglsW"
  content_version: 2
}
tracked_skill_info {
  id: "ixlztwRNBhn9"
  content_version: 10
}
tracked_skill_info {
  id: "6AhMkHcfZFdS"
  content_version: 7
}
tracked_skill_info {
  id: "wTww8o4yMqvL"
  content_version: 5
}
tracked_skill_info {
  id: "wvUvYfbd91Dh"
  content_version: 6
}
tracked_skill_info {
  id: "6aG8fos2y2tI"
  content_version: 8
}
tracked_skill_info {
  id: "bD3sajDo188l"
  content_version: 6
}
tracked_skill_info {
  id: "p3dQCHu4OkCr"
  content_version: 6
}
tracked_skill_info {
  id: "h5KljN9FIP7a"
  content_version: 14
}
