name: Flaky Test (Manual)

on:
  pull_request:

jobs:
  run-flaky-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Bazel
        uses: ./.github/actions/set-up-android-bazel-build-environment
        with:
          version: 6.5.0
      - name: Run test 100 times
        run: |
          bazel test --runs_per_test=100 app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest