name: Flaky Test (Manual)

on:
  pull_request:

jobs:
  run-flaky-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.5.0
      - name: Run test 100 times
        run: |
          bazel test //app/src/sharedTest/java/org/oppia/android/app/profileprogress:ProfileProgressFragmentTest --runs_per_test=100