name: JaCoCo Coverage

# Controls when the action will run. Triggers the workflow on pull request
# events or push events in the develop branch.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # Push events on develop branch
      - add-jacoco

# This workflow has the following jobs:
# robolectric_tests: Robolectric tests for all modules except the app module
# app_tests: Non-flaky Robolectric tests for the app module
jobs:
  robolectric_tests:
    name: Generate JaCoCo coverage report
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
     - uses: actions/checkout@v2
     - uses: actions/cache@v2
       id: cache
       with:
         path: ~/.gradle
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-jars-{{ checksum "build.gradle" }}

     - name: Set up JDK 1.9
       uses: actions/setup-java@v1
       with:
          java-version: 1.9

     - name: Install Dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       run: ./gradlew --full-stacktrace androidDependencies

       

     - name: Generate app module JaCoCo Coverage Report
       # We require 'sudo' to avoid an error of the existing android sdk. See https://github.com/actions/starter-workflows/issues/58
       run:  sudo ./gradlew --full-stacktrace app:jacocoCoverageReport
     - name: Upload app module JaCoCo Coverage Report
       uses: codecov/codecov-action@v1
       with:
        token: cea2720a-1021-4af7-a1e1-131895630631
        files: app/build/reports/jacoco/jacocoCoverageReport/jacocoCoverageReport.xml  
        name: oppia-android 


     - name: Generate domain module JaCoCo Coverage Report
       # We require 'sudo' to avoid an error of the existing android sdk. See https://github.com/actions/starter-workflows/issues/58
       run:  sudo ./gradlew --full-stacktrace domain:jacocoCoverageReport
     - name: Upload domain module JaCoCo Coverage Report
       uses: codecov/codecov-action@v1
       with:
        token: cea2720a-1021-4af7-a1e1-131895630631
        files: domain/build/reports/jacoco/jacocoCoverageReport/jacocoCoverageReport.xml   
        name: oppia-android 


     - name: Generate data module JaCoCo Coverage Report
       # We require 'sudo' to avoid an error of the existing android sdk. See https://github.com/actions/starter-workflows/issues/58
       run:  sudo ./gradlew --full-stacktrace data:jacocoCoverageReport
     - name: Upload data module JaCoCo Coverage Report
       uses: codecov/codecov-action@v1
       with:
        token: cea2720a-1021-4af7-a1e1-131895630631
        files: data/build/reports/jacoco/jacocoCoverageReport/jacocoCoverageReport.xml 
        name: oppia-android 


     - name: Generate testing module JaCoCo Coverage Report
       # We require 'sudo' to avoid an error of the existing android sdk. See https://github.com/actions/starter-workflows/issues/58
       run:  sudo ./gradlew --full-stacktrace testing:jacocoCoverageReport
     - name: Upload testing module JaCoCo Coverage Report
       uses: codecov/codecov-action@v1
       with:
        token: cea2720a-1021-4af7-a1e1-131895630631
        files: testing/build/reports/jacoco/jacocoCoverageReport/jacocoCoverageReport.xml
        name: oppia-android        


     - name: Generate utility module JaCoCo Coverage Report
       # We require 'sudo' to avoid an error of the existing android sdk. See https://github.com/actions/starter-workflows/issues/58
       run:  sudo ./gradlew --full-stacktrace utility:jacocoCoverageReport
     - name: Upload utility module JaCoCo Coverage Report
       uses: codecov/codecov-action@v1
       with:
        token: cea2720a-1021-4af7-a1e1-131895630631
        files: utility/build/reports/jacoco/jacocoCoverageReport/jacocoCoverageReport.xml
        name: oppia-android



         

       

     



