name: Deploy to Wiki
on:
  push:
    branches:
      - develop
    paths:
      - 'wiki/**'
  # Triggers this workflow when the wiki is changed
  # (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#gollum).
  gollum:

jobs:
  wiki-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        run: |
          git filter-branch --subdirectory-filter wiki/ -- --all
          git remote set-url origin https://github.com/oppia/oppia-android.wiki.git
          git checkout -b master
          git push origin master --force
